### ISSUE TITLE
MLX_LM: Memory usage much higher than expected

### ISSUE THREAD

**Issue by mark-lord** [ml-explore/mlx-examples#1025]
Running the following:

`mlx_lm.generate --model 'mlx-community/meta-llama-3.1-8b-instruct-4bit' --prompt '{10k tokens long prompt}' --max-kv-size-12000`

I would expect to get a memory usage somewhere around ~5gb as reported in this [tweet](https://x.com/awnihannun/status/1824541607468966289) - however, I'm getting approximately 26gb of app memory used and 6gb of wired memory compared to idle

Also doesn't seem to be an isolated issue, seen a similar report [here](https://www.reddit.com/r/LocalLLaMA/comments/1fz6z79/comment/lr3z369/?context=3) where Llama 3.2 3B MLX 4Bit with 16k context is using 15.22gb of memory, compared to 3.67gb used for the same model in 4bit GGUF.

Unfortunately not been able to figure out what might be causing this...

Steps to reproduce:

1. Install MLX_LM
2. Create a 10k token-long prompt (I just copy/pasted some random text until it reached 10k tokens in https://platform.openai.com/tokenizer, obviously slightly inaccurate but it's a ballpark)
3. Run `mlx_lm.generate --model 'mlx-community/meta-llama-3.1-8b-instruct-4bit' --prompt '{10k tokens long prompt}' --max-kv-size-12000` and copy/paste the 10k token prompt into the prompt field
4. Watch activity monitor soar to ~30gb used

Also getting the same behaviour in LMStudio - steps to reproduce are to install it, load up the Llama-3.1-8b-4bit model, then paste the same prompt there

**Comment by awni** [comment]
So I think this is the cache getting too big. The MLX cache is working against us here since we have basically no reuse during prompt processing. I think the right call is to just clear it after each prompt step. I will play around with that.

```
Toks 512, Peak 1890.264 (mb), Cache 111.603 (mb)
Toks 1024, Peak 2040.763 (mb), Cache 284.607 (mb)
Toks 1536, Peak 2137.263 (mb), Cache 500.862 (mb)
Toks 2048, Peak 2233.763 (mb), Cache 812.870 (mb)
Toks 2560, Peak 2330.263 (mb), Cache 1225.630 (mb)
Toks 3072, Peak 2426.763 (mb), Cache 1716.642 (mb)
Toks 3584, Peak 2523.263 (mb), Cache 2309.905 (mb)
Toks 4096, Peak 2619.763 (mb), Cache 2989.921 (mb)
Toks 4608, Peak 2716.263 (mb), Cache 3773.702 (mb)
Toks 5120, Peak 2812.763 (mb), Cache 4637.702 (mb)
Toks 5632, Peak 2909.263 (mb), Cache 5596.952 (mb)
Toks 6144, Peak 3005.763 (mb), Cache 6620.952 (mb)
Toks 6656, Peak 3102.263 (mb), Cache 7775.702 (mb)
Toks 7168, Peak 3198.763 (mb), Cache 9002.702 (mb)
Toks 7680, Peak 3295.263 (mb), Cache 10337.952 (mb)
Toks 8192, Peak 3391.763 (mb), Cache 11753.952 (mb)
Toks 8704, Peak 3488.263 (mb), Cache 13279.749 (mb)
Toks 9216, Peak 3584.763 (mb), Cache 14879.749 (mb)
```

**Comment by awni** [comment]
Clearing the cache during prompt processing seems to help a lot with this:

Before in activity monitor:

<img width="570" alt="Screenshot 2024-10-09 at 2 01 53 PM" src="https://github.com/user-attachments/assets/859550c8-b835-4b34-83a6-3f3b75c002af">

After in activity monitor:

<img width="621" alt="Screenshot 2024-10-09 at 2 02 26 PM" src="https://github.com/user-attachments/assets/9c4a6813-ab87-4e9a-9088-d2ce533f27ea">

**Comment by chigkim** [comment]
If you don't specify --max-kv-size, does it use the max context length from the model?

**Comment by awni** [comment]
No, it defaults to `None` and will grow indefinitely. It could be a nice feature to pull it from the model if available. Feel free to file an issue for that if it's you think it's useful.

**Comment by xpatronum** [comment]
> No, it defaults to `None` and will grow indefinitely. It could be a nice feature to pull it from the model if available. Feel free to file an issue for that if it's you think it's useful.

We get on M2 ultra with 192 gb of RAM very slow generation speed using [Llama 70b 8bit](https://huggingface.co/mlx-community/Hermes-3-Llama-3.1-70B-8bit). What are we doing wrong ?

```
python -m mlx_lm.generate --model mlx-community/Hermes-3-Llama-3.1-70B-8bit --prompt "Сгенерируй эссе на русском языке." --max-tokens 8096
```

Feel free to DM me via itarlinskiy@gmail.com for additional details.

**Comment by awni** [comment]
When the machine is under substantial memory pressure, large models can run very slow, in some cases 10x slower than what is typical. This is usually due to the system unwiring memory in an adversarial way.

We are investigating long-term clean solutions in MLX. However, there are a few temporary fixes you can try:

- Upgrading to OS 15. This usually helps on its own.

- Set some sysctls:

```bash
sudo sysctl iogpu.wired_lwm_mb=400000
sudo sysctl iogpu.wired_limit_mb=150000 
```

The above are set for a machine with 192GB. Set the first value to something very large to effectively disable it (e.g. twice the physical RAM of your machine). Set the second value to a number slightly less than the physical RAM of your machine.

- Rebooting usually helps

**Comment by xpatronum** [comment]
> When the machine is under substantial memory pressure, large models can run very slow, in some cases 10x slower than what is typical. This is usually due to the system unwiring memory in an adversarial way.
> 
> We are investigating long-term clean solutions in MLX. However, there are a few temporary fixes you can try:

Thank you for quick response and hot fix suggestions. I'll try and get back to u with the results.
