### ISSUE TITLE
Slow Speed Issue

### ISSUE THREAD

**Issue by chigkim** [ml-explore/mlx-examples#1029]
I ran the tests below on a Macbook Pro  with m3-max 64GB. MLX seems to run much slower than llama.cpp with flash attention enabled.

Is this speed just a result of flash attention not available in MLX? If so, it would be amazing to have flash attention!

I'm including the full commands and relevant logs below. Also here is my [Full prompt](https://pastebin.com/raw/U4fjjTuv) (from Wikipedia article).

Lcpp-fa = llama.cpp with flash attention.

Thanks!

| Quant | Engine | PP | TG |
| --- | --- | --- | --- |
| Q4_K_M | lcpp-fa | 385.56 | 32.00 |
| Q4_K_M | lcpp | 301.82 | 9.41 |
| 4bit | mlx | 421.59 | 23.43 |
| Q8_0 | lcpp-fa | 393.39 | 25.90 |
| Q8_0 | lcpp | 301.18 | 8.66 |
| 8bit | mlx | 401.616 | 19.02 |

```bash
./llama-cli -m ../models/Meta-Llama-3.1-8B-Instruct-Q4_K_M.gguf -c 33000 -n 1000 --temp 0.0 --top_p 0.9 --seed 1000 -fa -f ../text/llama-portugal.txt;say done
llama_perf_context_print: prompt eval time =   83343.35 ms / 32134 tokens (    2.59 ms per token,   385.56 tokens per second)
llama_perf_context_print:        eval time =   22626.14 ms /   724 runs   (   31.25 ms per token,    32.00 tokens per second)

./llama-cli -m ../models/Meta-Llama-3.1-8B-Instruct-Q4_K_M.gguf -c 33000 -n 1000 --temp 0.0 --top_p 0.9 --seed 1000 -f ../text/llama-portugal.txt;say done
llama_perf_context_print: prompt eval time =  106466.04 ms / 32134 tokens (    3.31 ms per token,   301.82 tokens per second)
llama_perf_context_print:        eval time =   88601.05 ms /   834 runs   (  106.24 ms per token,     9.41 tokens per second)

mlx_lm.generate --model mlx-community/Meta-Llama-3.1-8B-Instruct-4bit --max-kv-size 33000 --max-tokens 1000 --temp 0.0 --top-p 0.9 --seed 1000 --prompt  -<../text/portugal.txt;say done
Prompt: 32134 tokens, 421.590 tokens-per-sec
Generation: 554 tokens, 23.434 tokens-per-sec

./llama-cli -m ../models/Meta-Llama-3.1-8B-Instruct-Q8_0.gguf -c 33000 -n 1000 --temp 0.0 --top_p 0.9 --seed 1000 -fa -f ../text/llama-portugal.txt;say done
llama_perf_context_print: prompt eval time =   81683.80 ms / 32134 tokens (    2.54 ms per token,   393.39 tokens per second)
llama_perf_context_print:        eval time =   27257.10 ms /   706 runs   (   38.61 ms per token,    25.90 tokens per second)

./llama-cli -m ../models/Meta-Llama-3.1-8B-Instruct-Q8_0.gguf -c 33000 -n 1000 --temp 0.0 --top_p 0.9 --seed 1000 -f ../text/llama-portugal.txt;say done
llama_perf_context_print: prompt eval time =  106694.04 ms / 32134 tokens (    3.32 ms per token,   301.18 tokens per second)
llama_perf_context_print:        eval time =   90074.36 ms /   780 runs   (  115.48 ms per token,     8.66 tokens per second)

mlx_lm.generate --model mlx-community/Meta-Llama-3.1-8B-Instruct-8bit --max-kv-size 33000 --max-tokens 1000 --temp 0.0 --top-p 0.9 --seed 1000 --prompt  -<../text/portugal.txt;say done
Prompt: 32134 tokens, 401.616 tokens-per-sec
Generation: 788 tokens, 19.020 tokens-per-sec
```

**Comment by awni** [comment]
There's likely two factors here:

- There is an optimization in the latest MLX LM (in the main branch but not yet released) that improves memory use and might help in your case for very long prompts if the system is under memory pressure.

- Yes MLX does not have a fast fused attention yet. This is WIP and when it lands we should see a speedup especially for the long context cases.

**Comment by chigkim** [comment]
Thanks for the response!
Yea actually pulled from git this morning and installed from the  source, so the fix #1027 should be included in my test.
Looking forward to fast fused attention! :)

**Comment by awni** [comment]
FYI we sped up the fused attention in MLX 0.19.0. It should be noticeably faster though still a bit slower than llama.cpp at the very long sequence lengths.. there's still some optimizations to do there.

**Comment by awni** [comment]
> Should I created a separate issue?

If the behavior changed from 0.18.1 to 0.19 yes it would be good to file another issue for that. Maybe small changes due to numerics make sense but if it went from working to not working that doesn't sound good.

**Comment by awni** [comment]
@chigkim are you still having this issue?

**Comment by angeloskath** [comment]
@chigkim I would do another test in general with the latest mlx (meaning the one on `main` not on PyPI yet). On an M2 Ultra I get (the improvement should be less pronounced on the M3 Max)

```
lcpp-fa         37 tps
mlx-before-sdpa 27 tps
mlx-sdpa        32 tps
mlx-latest      54 tps
```

Moreover, I got looping with lcpp-fa when testing the `q4_k` so I think it is generally quite brittle at 4 bits with the long context. Either way you can also check if you still have looping now with the latest kernel.

**Comment by chigkim** [comment]
Interestingly, I've never seen the loop behavior with llama.cpp with q4_K_M. Which gguf did you use? I used:
https://huggingface.co/bartowski/Meta-Llama-3.1-8B-Instruct-GGUF

I just pulled both mlx as well as mlx_examples, and installed with `pip install -e .`.
Unfortunately, I don't see much improvement.
mlx: 211411faf2
mlx-lm: 0f135396ae

```bash
./llama-cli -m ../models/Meta-Llama-3.1-8B-Instruct-Q4_K_M.gguf -c 33000 -n 1000 --temp 0.0 --top_p 0.9 --seed 1000 -fa -f ../text/llama-portugal.txt;say done
llama_perf_context_print: prompt eval time =   81388.87 ms / 32163 tokens (    2.53 ms per token,   395.18 tokens per second)
llama_perf_context_print:        eval time =   24015.13 ms /   802 runs   (   29.94 ms per token,    33.40 tokens per second)

./llama-cli -m ../models/Meta-Llama-3.1-8B-Instruct-Q4_K_M.gguf -c 33000 -n 1000 --temp 0.0 --top_p 0.9 --seed 1000 -f ../text/llama-portugal.txt;say done
llama_perf_context_print: prompt eval time =  109641.06 ms / 32163 tokens (    3.41 ms per token,   293.35 tokens per second)
llama_perf_context_print:        eval time =   83881.20 ms /   795 runs   (  105.51 ms per token,     9.48 tokens per second)

mlx_lm.generate --model mlx-community/Meta-Llama-3.1-8B-Instruct-4bit --max-kv-size 33000 --max-tokens 1000 --temp 0.0 --top-p 0.9 --seed 1000 --prompt  -<../text/portugal.txt;say done
Prompt: 32134 tokens, 428.042 tokens-per-sec
Generation: 1000 tokens, 22.569 tokens-per-sec

./llama-cli -m ../models/Meta-Llama-3.1-8B-Instruct-Q8_0.gguf -c 33000 -n 1000 --temp 0.0 --top_p 0.9 --seed 1000 -fa -f ../text/llama-portugal.txt;say done
llama_perf_context_print: prompt eval time =   79022.07 ms / 32163 tokens (    2.46 ms per token,   407.01 tokens per second)
llama_perf_context_print:        eval time =   20289.20 ms /   538 runs   (   37.71 ms per token,    26.52 tokens per second)

./llama-cli -m ../models/Meta-Llama-3.1-8B-Instruct-Q8_0.gguf -c 33000 -n 1000 --temp 0.0 --top_p 0.9 --seed 1000 -f ../text/llama-portugal.txt;say done
llama_perf_context_print: prompt eval time =  105903.66 ms / 32163 tokens (    3.29 ms per token,   303.70 tokens per second)
llama_perf_context_print:        eval time =   95011.02 ms /   839 runs   (  113.24 ms per token,     8.83 tokens per second)

mlx_lm.generate --model mlx-community/Meta-Llama-3.1-8B-Instruct-8bit --max-kv-size 33000 --max-tokens 1000 --temp 0.0 --top-p 0.9 --seed 1000 --prompt -<../text/portugal.txt;say done
Prompt: 32159 tokens, 433.764 tokens-per-sec
Generation: 819 tokens, 18.505 tokens-per-sec
```

**Comment by awni** [comment]
That's interesting.. it seems a bit slower than MLX 0.20.0 🤔

**Comment by awni** [comment]
Btw, the latest MLX LM (0.20.1) should be faster. There was a performance bug for long context that slipped in recently. I get in the ~33 toks/sec range now for your benchmark.

**Comment by chigkim** [comment]
Ooo, finally getting the comparable speed as llama.cpp with flash attention!!!
Thank you so much!!!

```bash
mlx_lm.generate --model mlx-community/Meta-Llama-3.1-8B-Instruct-4bit --max-kv-size 33000 --max-tokens 1000 --temp 0.0 --top-p 0.9 --seed 1000 --prompt  -<../text/portugal.txt;say done
Prompt: 32134 tokens, 432.615 tokens-per-sec
Generation: 1000 tokens, 33.269 tokens-per-sec

mlx_lm.generate --model mlx-community/Meta-Llama-3.1-8B-Instruct-8bit --max-kv-size 33000 --max-tokens 1000 --temp 0.0 --top-p 0.9 --seed 1000 --prompt  -<../text/portugal.txt;say done
Prompt: 32159 tokens, 425.973 tokens-per-sec
Generation: 819 tokens, 25.236 tokens-per-sec
```

**Comment by chigkim** [comment]
Just to add, I tested Llama.CPP and MLX with various prompt sizes on my M3-Max 64GB. MLX seems to be consistently faster than Llama.cpp now! In average, MLX processes tokens 1.14x faster and generates tokens 1.12x faster!!!

* Both used the temperature 0.0, top_p 0.9, seed 1000.
* MLX-LM: 0.20.4
* MLX: 0.21.1
* Model: Llama-3.3-70B-Instruct-4bit
* Llama.cpp: b4326
* Model: llama-3.3-70b-instruct-q4_K_M
* Flash attention enabled

### MLX

| Prompt Tokens | Prompt Processing Speed | Generated Tokens | Token Generation Speed | Total Execution Time |
| --- | --- | --- | --- | --- |
| 260 | 75.871 | 309 | 9.351 | 48s |
| 689 | 83.567 | 760 | 9.366 | 1m42s |
| 1171 | 83.843 | 744 | 9.287 | 1m46s |
| 1635 | 83.239 | 754 | 9.222 | 1m53s |
| 2173 | 83.092 | 776 | 9.123 | 2m3s |
| 3228 | 81.068 | 744 | 8.970 | 2m15s |
| 4126 | 79.410 | 724 | 8.917 | 2m25s |
| 6096 | 76.796 | 752 | 8.724 | 2m57s |
| 8015 | 74.840 | 786 | 8.520 | 3m31s |
| 10088 | 72.363 | 887 | 8.328 | 4m18s |
| 12010 | 71.017 | 1139 | 8.152 | 5m20s |
| 14066 | 68.943 | 634 | 7.907 | 4m55s |
| 16003 | 67.948 | 459 | 7.779 | 5m5s |
| 18211 | 66.105 | 568 | 7.604 | 6m1s |
| 20236 | 64.452 | 625 | 7.423 | 6m49s |
| 22188 | 63.332 | 508 | 7.277 | 7m10s |
| 24246 | 61.424 | 462 | 7.121 | 7m50s |
| 26034 | 60.375 | 1178 | 7.019 | 10m9s |
| 28002 | 59.009 | 27 | 6.808 | 8m9s |
| 30136 | 58.080 | 27 | 6.784 | 8m53s |
| 32172 | 56.502 | 27 | 6.482 | 9m44s |

### Llama.CPP

| Prompt Tokens | Prompt Processing Speed | Generated Tokens | Token Generation Speed | Total Execution Time |
| --- | --- | --- | --- | --- |
| 258 | 67.86 | 599 | 8.15 | 1m32s |
| 687 | 66.65 | 1999 | 8.09 | 4m18s |
| 1169 | 72.12 | 581 | 7.99 | 1m30s |
| 1633 | 72.57 | 891 | 7.93 | 2m16s |
| 2171 | 71.87 | 799 | 7.87 | 2m13s |
| 3226 | 69.86 | 612 | 7.78 | 2m6s |
| 4124 | 68.39 | 825 | 7.72 | 2m48s |
| 6094 | 66.62 | 642 | 7.64 | 2m57s |
| 8013 | 65.17 | 863 | 7.48 | 4m |
| 10086 | 63.28 | 766 | 7.34 | 4m25s |
| 12008 | 62.07 | 914 | 7.34 | 5m19s |
| 14064 | 60.80 | 799 | 7.23 | 5m43s |
| 16001 | 59.50 | 714 | 7.00 | 6m13s |
| 18209 | 58.14 | 766 | 6.74 | 7m9s |
| 20234 | 56.88 | 786 | 6.60 | 7m57s |
| 22186 | 55.91 | 724 | 6.69 | 8m27s |
| 24244 | 55.04 | 772 | 6.60 | 9m19s |
| 26032 | 53.74 | 510 | 6.41 | 9m26s |
| 28000 | 52.68 | 768 | 6.23 | 10m57s |
| 30134 | 51.39 | 529 | 6.29 | 11m13s |
| 32170 | 50.32 | 596 | 6.13 | 12m19s |

Thanks!!!

**Comment by awni** [comment]
Awesome! Thanks for following up!

**Comment by chigkim** [comment]
I posted the result on Reddit, and people are complaining it's not a fair comparison. lol
People are saying q4_K_M in LCP is higher quant than MLX-4bit. Does MLX supports like different 4bit quant like 4.7bpw?

**Comment by chigkim** [comment]
When comparing q4_0 equivalent quant on Llama.cpp to MLX-4bit, in average, MLX processes tokens 1.03x faster, and generates tokens 1.02x faster.

| Engine | Quant | Prompt Tokens | Prompt Processing Speed | Generated Tokens | Token Generation Speed | Total Execution Time |
| --- | --- | --- | --- | --- | --- | --- |
| MLX | 4bit  | 260 | 75.871 | 309 | 9.351 | 48s |
| LCP | q4_0  | 260 | 73.86 | 1999 | 9.07 | 3m58s |
| LCP | q4_K_M  | 260 | 67.86 | 599 | 8.15 | 1m32s |
| MLX | 4bit  | 689 | 83.567 | 760 | 9.366 | 1m42s |
| LCP | q4_0  | 689 | 80.30 | 527 | 9.08 | 1m7s |
| LCP | q4_K_M  | 689 | 66.65 | 1999 | 8.09 | 4m18s |
| MLX | 4bit  | 1171 | 83.843 | 744 | 9.287 | 1m46s |
| LCP | q4_0  | 1171 | 80.94 | 841 | 9.03 | 1m48s |
| LCP | q4_K_M  | 1171 | 72.12 | 581 | 7.99 | 1m30s |
| MLX | 4bit  | 1635 | 83.239 | 754 | 9.222 | 1m53s |
| LCP | q4_0  | 1635 | 79.82 | 731 | 8.97 | 1m43s |
| LCP | q4_K_M  | 1635 | 72.57 | 891 | 7.93 | 2m16s |
| MLX | 4bit  | 2173 | 83.092 | 776 | 9.123 | 2m3s |
| LCP | q4_0  | 2173 | 78.71 | 857 | 8.90 | 2m5s |
| LCP | q4_K_M  | 2173 | 71.87 | 799 | 7.87 | 2m13s |
| MLX | 4bit  | 3228 | 81.068 | 744 | 8.970 | 2m15s |
| LCP | q4_0  | 3228 | 79.21 | 606 | 8.84 | 1m50s |
| LCP | q4_K_M  | 3228 | 69.86 | 612 | 7.78 | 2m6s |
| MLX | 4bit  | 4126 | 79.410 | 724 | 8.917 | 2m25s |
| LCP | q4_0  | 4126 | 77.72 | 522 | 8.67 | 1m54s |
| LCP | q4_K_M  | 4126 | 68.39 | 825 | 7.72 | 2m48s |
| MLX | 4bit  | 6096 | 76.796 | 752 | 8.724 | 2m57s |
| LCP | q4_0  | 6096 | 74.25 | 500 | 8.58 | 2m21s |
| LCP | q4_K_M  | 6096 | 66.62 | 642 | 7.64 | 2m57s |
| MLX | 4bit  | 8015 | 74.840 | 786 | 8.520 | 3m31s |
| LCP | q4_0  | 8015 | 72.11 | 495 | 8.30 | 2m52s |
| LCP | q4_K_M  | 8015 | 65.17 | 863 | 7.48 | 4m |
| MLX | 4bit  | 10088 | 72.363 | 887 | 8.328 | 4m18s |
| LCP | q4_0  | 10088 | 70.23 | 458 | 8.12 | 3m21s |
| LCP | q4_K_M  | 10088 | 63.28 | 766 | 7.34 | 4m25s |
| MLX | 4bit  | 12010 | 71.017 | 1139 | 8.152 | 5m20s |
| LCP | q4_0  | 12010 | 68.61 | 633 | 8.19 | 4m14s |
| LCP | q4_K_M  | 12010 | 62.07 | 914 | 7.34 | 5m19s |
| MLX | 4bit  | 14066 | 68.943 | 634 | 7.907 | 4m55s |
| LCP | q4_0  | 14066 | 67.21 | 595 | 8.06 | 4m44s |
| LCP | q4_K_M  | 14066 | 60.80 | 799 | 7.23 | 5m43s |
| MLX | 4bit  | 16003 | 67.948 | 459 | 7.779 | 5m5s |
| LCP | q4_0  | 16003 | 65.54 | 363 | 7.58 | 4m53s |
| LCP | q4_K_M  | 16003 | 59.50 | 714 | 7.00 | 6m13s |
| MLX | 4bit  | 18211 | 66.105 | 568 | 7.604 | 6m1s |
| LCP | q4_0  | 18211 | 63.93 | 749 | 7.46 | 6m27s |
| LCP | q4_K_M  | 18211 | 58.14 | 766 | 6.74 | 7m9s |
| MLX | 4bit  | 20236 | 64.452 | 625 | 7.423 | 6m49s |
| LCP | q4_0  | 20236 | 62.55 | 409 | 6.92 | 6m24s |
| LCP | q4_K_M  | 20236 | 56.88 | 786 | 6.60 | 7m57s |
| MLX | 4bit  | 22188 | 63.332 | 508 | 7.277 | 7m10s |
| LCP | q4_0  | 22188 | 61.24 | 572 | 7.33 | 7m22s |
| LCP | q4_K_M  | 22188 | 55.91 | 724 | 6.69 | 8m27s |
| MLX | 4bit  | 24246 | 61.424 | 462 | 7.121 | 7m50s |
| LCP | q4_0  | 24246 | 59.95 | 370 | 7.10 | 7m38s |
| LCP | q4_K_M  | 24246 | 55.04 | 772 | 6.60 | 9m19s |
| MLX | 4bit  | 26034 | 60.375 | 1178 | 7.019 | 10m9s |
| LCP | q4_0  | 26034 | 58.65 | 383 | 6.95 | 8m21s |
| LCP | q4_K_M  | 26034 | 53.74 | 510 | 6.41 | 9m26s |
| MLX | 4bit  | 28002 | 59.009 | 27 | 6.808 | 8m9s |
| LCP | q4_0  | 28002 | 57.52 | 692 | 6.79 | 9m51s |
| LCP | q4_K_M  | 28002 | 52.68 | 768 | 6.23 | 10m57s |
| MLX | 4bit  | 30136 | 58.080 | 27 | 6.784 | 8m53s |
| LCP | q4_0  | 30136 | 56.27 | 447 | 6.74 | 10m4s |
| LCP | q4_K_M  | 30136 | 51.39 | 529 | 6.29 | 11m13s |
| MLX | 4bit  | 32172 | 56.502 | 27 | 6.482 | 9m44s |
| LCP | q4_0  | 32172 | 54.68 | 938 | 6.73 | 12m10s |
| LCP | q4_K_M  | 32172 | 50.32 | 596 | 6.13 | 12m19s |

**Comment by awni** [comment]
Interesting! I'd love to know how quality compares between Q4_0 and Q4_K_M. Even though MLX 4-bit is about the same as Q4_0 in BPW, my understanding is MLX 4-bit is about the same as Q4_K_M in terms of quality but I can't say it with too much confidence.

Some benchmarks [here](https://aider.chat/2024/11/21/quantization.html) and [here](https://github.com/ml-explore/mlx-examples/pull/1132).

**Comment by chigkim** [comment]
Thanks so much for the links.

For fun and curiosity, I'll also run MMLU Pro benchmark against LCP q4K_M and MLX-4bit and report back! :)

My Reddit post is here if interested.

https://www.reddit.com/r/LocalLLaMA/comments/1hes7wm/speed_test_2_llamacpp_vs_mlx_with_llama3370b_and/

**Comment by chigkim** [comment]
The models I used were [bartowski/Llama-3.2-3B-Instruct-GGUF](https://huggingface.co/bartowski/Llama-3.2-3B-Instruct-GGUF) and [mlx-community/Llama-3.2-3B-Instruct-4bit](https://huggingface.co/mlx-community/Llama-3.2-3B-Instruct-4bit).

I opted for a smaller model because I assumed quantization would have a greater impact on smaller models. Plus, running the benchmark with 12k questions takes less time.

| Quant | overall | biology | business | chemistry | computer science | economics | engineering | health | history | law | math | philosophy | physics | psychology | other |
| ----- | ------- | ------- | -------- | --------- | ---------------- | --------- | ----------- | ------ | ------- | --- | ---- | ---------- | ------- | ---------- | ----- |
| MLX-4bit | 36.15 | 56.62 | 41.32 | 29.68 | 37.56 | 43.72 | 24.36 | 40.95 | 34.38 | 20.07 | 39.90 | 31.26 | 30.25 | 51.00 | 36.80 |
| GGUF-q4_K_M | 36.10 | 50.91 | 40.56 | 28.09 | 37.32 | 47.27 | 22.19 | 43.64 | 36.48 | 22.52 | 39.08 | 31.46 | 30.79 | 51.25 | 36.26 |

I posted a Reddit thread: https://www.reddit.com/r/LocalLLaMA/comments/1hgj0t6/mmlu_pro_mlx4bit_vs_ggufq4_k_m/

**Comment by awni** [comment]
Thanks for taking the time to run those. It's especially great to have third-party evaluations of different frameworks! It looks like MLX 4-bit is about the same quality as Q4_K_M which is what we expected.

**Comment by ilterpehlivan** [comment]
> 25.236 tokens

Hi, I am running the same test in Mac Mini 64GB Ram with latest version of MLX examples (`0.21.4`) but my result is much lower than what @chigkim observed! `33TPS vs 23TPS`
```
mlx_lm.generate --model mlx-community/Meta-Llama-3.1-8B-Instruct-4bit --max-kv-size 33000 --max-tokens 1000 --temp 0.0 --top-p 0.9 --seed 1000 --prompt -<prompt-test-portugal.txt;say done

==========
Prompt: 32159 tokens, 261.786 tokens-per-sec
Generation: 1000 tokens, 23.146 tokens-per-sec
Peak memory: 13.523 GB
```
@awni  Do you have any idea why my results are low ? Thanks

**Comment by awni** [comment]
I'm not sure what model Mac Mini you are running, but an M3 Max is going to be faster in generl.

**Comment by ilterpehlivan** [comment]
> I'm not sure what model Mac Mini you are running, but an M3 Max is going to be faster in generl.

thanks for quick response @awni  I have "Mac mini M4 Pro" which should be better than M3

**Comment by awni** [comment]
M3 Max should still be faster than M4 Pro. About 400 GB/s memory bandwidth vs ~275.

**Comment by chigkim** [comment]
Also make sure you have high the performance mode is selected for energy. Otherwise, it gets throttled like crazy. I'm not sure where the setting is located in Mac Mini, but it's in system settings > battery in MacBook Pro.

**Comment by ilterpehlivan** [comment]
> ttings > battery in MacBook Pro.

thanks @chigkim for the suggestion but changing the energy setting also did not help. 
It is clear that mac mini despite the M4 chip is not able to have enough compute power. Llama.cpp results also under your M3 test results :) I am adding here for reference in case someone else would be looking for `Mac Mini M4 Pro - 64GB`

```
# llama-cli -hf bartowski/Meta-Llama-3.1-8B-Instruct-GGUF:Q4_K_M -c 33000 -n 1000 --temp 0.0 --top_p 0.9 --seed 1000 -fa -f prompt-test-portugal.txt;say done
llama_perf_context_print: prompt eval time =  133879.21 ms / 32130 tokens (    4.17 ms per token,   239.99 tokens per second)
llama_perf_context_print:        eval time =   51449.51 ms /   999 runs   (   51.50 ms per token,    19.42 tokens per second)
llama_perf_context_print:       total time =  190204.23 ms / 33129 tokens
```
