### ISSUE TITLE
mlx-examples/lora /convert.py isn't properly handling HF pytorch model format

### ISSUE THREAD

**Issue by chimezie** [ml-explore/mlx-examples#104]
This overlaps somewhat with #35 and is probably an enhancement since the Wiki expects Mistral is downloaded from [mistral.ai](https://files.mistral-7b-v0-1.mistral.ai/mistral-7B-v0.1.tar), but it would be a useful one as the framework could be used with Hugging Face model files.

In particular, I'm trying to perform LoRa training on [mistralai/Mistral-7B-v0.1](https://huggingface.co/mistralai/Mistral-7B-v0.1) and failing on the initial example step of conversion

I was able to update the script to handle the 'sharded' pytorch model files (not the safetensor files) with this modification to the part of it that loads the weights (this, of course, assumes each .bin file is non-overlapping as suggested by the naming convention):

``` python
    from glob import glob
    weight_dict = {}
    for state_path in glob(str(torch_path / "pytorch_model-0000*.bin")):
        print("Weights from", state_path)
        state = torch.load(state_path)
        weight_dict.update(**{k: v.to(torch.float16).numpy() for k, v in state.items()})
    np.savez(str(mlx_path / "weights.npz"), weight_dict)
```

I immediately run into issues in the last part that copies the parameters.  It was looking for a **params.json** file and (via some minimal fussing) it looks like **config.json** might be the file it needs to refer to instead.  Looking in there, there is a **num_key_value_heads** entry, which might what is needed instead of the **n_heads** key the script expects.  However, this is as far as I got with the parameter copying logic.

**Comment by awni** [comment]
I'm actively working on #81 which should solve this. Closing this as duplicate.
