### ISSUE TITLE
Fine-Tuning Llama-3.2-1B with LoRA Failed

### ISSUE THREAD

**Issue by lhwong** [ml-explore/mlx-examples#1041]
Does Fine-Tuning with LoRA support Llama-3.2-1B? I go the following error 
ValueError: rope_scaling must contain keys {'factor', 'type'}

Details:
(env) lhwong@Liongs-MacBook-Pro lora % python3 lora.py \                 
  --train \
  --model meta-llama/Llama-3.2-1B \
  --data ~/Projects/AI/data \
  --batch-size 2 \
  --lora-layers 8 \
  --iters 1000
None of PyTorch, TensorFlow >= 2.0, or Flax have been found. Models won't be available and only tokenizers, configuration and file/data utilities can be used.
Loading pretrained model
Fetching 7 files: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 7/7 [00:00<00:00, 35717.92it/s]
Traceback (most recent call last):
  File "/Users/lhwong/Projects/AI/mlx-examples/lora/lora.py", line 336, in <module>
    model, tokenizer, _ = lora_utils.load(args.model, tokenizer_config)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/lhwong/Projects/AI/mlx-examples/lora/utils.py", line 149, in load
    model_args = models.ModelArgs.from_dict(config)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/lhwong/Projects/AI/mlx-examples/lora/models.py", line 40, in from_dict
    return cls(
           ^^^^
  File "<string>", line 14, in __init__
  File "/Users/lhwong/Projects/AI/mlx-examples/lora/models.py", line 33, in __post_init__
    raise ValueError(f"rope_scaling must contain keys {required_keys}")
ValueError: rope_scaling must contain keys {'factor', 'type'}

**Comment by awni** [comment]
Yes, but you have to use the lora in `mlx_lm`. See the [docs here](https://github.com/ml-explore/mlx-examples/blob/main/llms/mlx_lm/LORA.md).
