### ISSUE TITLE
Can't not run on MacOS 15.0.1

### ISSUE THREAD

**Issue by ZhuominLi** [ml-explore/mlx-examples#1046]
![image](https://github.com/user-attachments/assets/010ca243-4f8c-47e2-9250-7a51cc6b805a)
got an error above but actually my MacOS already 15.0.1

**Comment by awni** [comment]
Well for some reason Python thinks you are using an older OS. Can you run the below and share the output?

```
python -c "import platform;print(platform.mac_ver())"
```

**Comment by ZhuominLi** [comment]
> Well for some reason Python thinks you are using an older OS. Can you run the below and share the output?
> 
> ```
> python -c "import platform;print(platform.mac_ver())"
> ```
![image](https://github.com/user-attachments/assets/37fa4c52-1d4f-4c35-ab12-a8135103efc0)
okay, why shows 10.16....
here is my real OS
<img width="482" alt="image" src="https://github.com/user-attachments/assets/81951a0c-95c4-4159-962d-77015fc033e9">

**Comment by awni** [comment]
It looks like you have an x86_64 mac? What hardware is it?

If it's an M-series machine then you are probably using an emulated python. You can check the [troubleshooting guide on this](https://ml-explore.github.io/mlx/build/html/install.html#troubleshooting).

**Comment by awni** [comment]
Closing this as resolved. Feel free to comment here if you are still having issues.
