### ISSUE TITLE
tools example for finetuning seems wrong

### ISSUE THREAD

**Issue by hansvdam** [ml-explore/mlx-examples#1053]
In https://github.com/ml-explore/mlx-examples/blob/main/llms/mlx_lm/LORA.md
for **tools finetuning** the example reads:

`{"messages":[{"role":"user","content":"What is the weather in San Francisco?"},{"role":"assistant","tool_calls":[{"id":"call_id","type":"function","function":{"name":"get_current_weather","arguments":"{\"location\": \"San Francisco, USA\", \"format\": \"celsius\"}"}}]}],"tools":[{"type":"function","function":{"name":"get_current_weather","description":"Get the current weather","parameters":{"type":"object","properties":{"location":{"type":"string","description":"The city and country, eg. San Francisco, USA"},"format":{"type":"string","enum":["celsius","fahrenheit"]}},"required":["location","format"]}}}]}`

When using the that format, the result was a disaster with all kinds of quotes with backslashes in the results of the tool calls. After removing the \\" from the arguments, my finetunings work very well:

`{"messages":[{"role":"user","content":"What is the weather in San Francisco?"},{"role":"assistant","tool_calls":[{"id":"call_id","type":"function","function":{"name":"get_current_weather","arguments":"{"location": "San Francisco, USA", "format": "celsius"}"}}]}],"tools":[{"type":"function","function":{"name":"get_current_weather","description":"Get the current weather","parameters":{"type":"object","properties":{"location":{"type":"string","description":"The city and country, eg. San Francisco, USA"},"format":{"type":"string","enum":["celsius","fahrenheit"]}},"required":["location","format"]}}}]}`

**Comment by awni** [comment]
Yes that looks like an error in the documentation. Thanks for catching it!
