### ISSUE TITLE
[BUG] memory during fine tuning grows until MacBook crashes

### ISSUE THREAD

**Issue by hschaeufler** [ml-explore/mlx-examples#1076]
**Describe the bug**
The required memory seems to increase continuously during fine-tuning. I train 5 epochs. Shortly after starting the 2nd epoch, my MacBook crashes because there is no more memory available. My data set contains 2058 entries and I train 10290 iterations. The peak memory increases in the meantime. With a similar configuration, I was able to perform fine-tuning a month ago without crashing. I terminate all programms before starting to train. I have a MacBook Pro with 128GB memory and M3 Max processor.

```
dartgen % mlx_lm.lora --config "fine_tuning/mlx/llama3_1_8B_instruct_lora_config.yaml"
Loading configuration file fine_tuning/mlx/llama3_1_8B_instruct_lora_config.yaml
Loading pretrained model
/Users/admin/.cache/huggingface/hub/models--meta-llama--Meta-Llama-3.1-8B-Instruct/snapshots/0e9e39f249a16976918f6564b8830bc894c89659
Loading datasets
Training
Trainable parameters: 1.045% (83.886M/8030.261M)
Starting training..., iters: 10290
Iter 1: Val loss 0.655, Val took 87.790s
[WARNING] Some sequences are longer than 8192 tokens. The longest sentence 19487 will be truncated to 8192. Consider pre-splitting your data to save memory.
Iter 10: Train loss 0.784, Learning Rate 2.913e-07, It/sec 0.037, Tokens/sec 81.695, Trained Tokens 22075, Peak mem 121.550 GB
Iter 20: Train loss 0.841, Learning Rate 6.149e-07, It/sec 0.084, Tokens/sec 115.019, Trained Tokens 35799, Peak mem 121.550 GB
Iter 30: Train loss 0.812, Learning Rate 9.385e-07, It/sec 0.097, Tokens/sec 115.662, Trained Tokens 47775, Peak mem 121.550 GB
Iter 40: Train loss 0.728, Learning Rate 1.262e-06, It/sec 0.075, Tokens/sec 113.291, Trained Tokens 62897, Peak mem 121.550 GB
Iter 50: Train loss 0.629, Learning Rate 1.586e-06, It/sec 0.092, Tokens/sec 122.670, Trained Tokens 76177, Peak mem 121.550 GB
Iter 60: Train loss 0.604, Learning Rate 1.909e-06, It/sec 0.071, Tokens/sec 119.333, Trained Tokens 93038, Peak mem 121.550 GB
Iter 70: Train loss 0.544, Learning Rate 2.233e-06, It/sec 0.072, Tokens/sec 126.830, Trained Tokens 110709, Peak mem 121.550 GB
Iter 80: Train loss 0.583, Learning Rate 2.557e-06, It/sec 0.120, Tokens/sec 129.292, Trained Tokens 121482, Peak mem 121.550 GB
Iter 90: Train loss 0.617, Learning Rate 2.880e-06, It/sec 0.107, Tokens/sec 129.724, Trained Tokens 133588, Peak mem 121.550 GB
Iter 100: Train loss 0.574, Learning Rate 3.204e-06, It/sec 0.128, Tokens/sec 129.965, Trained Tokens 143762, Peak mem 121.550 GB
...
 Peak mem 236.340 GB
Iter 2300: Saved adapter weights to results/llama3_1_8B_instruct_lora/tuning_15/adapters/adapters.safetensors and results/llama3_1_8B_instruct_lora/tuning_15/adapters/0002300_adapters.safetensors.
Iter 2310: Train loss 0.235, Learning Rate 9.042e-06, It/sec 0.050, Tokens/sec 83.557, Trained Tokens 3243107, Peak mem 236.340 GB
Iter 2320: Train loss 0.205, Learning Rate 9.033e-06, It/sec 0.075, Tokens/sec 81.691, Trained Tokens 3254004, Peak mem 236.340 GB
Iter 2330: Train loss 0.248, Learning Rate 9.024e-06, It/sec 0.062, Tokens/sec 82.444, Trained Tokens 3267278, Peak mem 236.340 GB
Iter 2340: Train loss 0.218, Learning Rate 9.015e-06, It/sec 0.065, Tokens/sec 82.367, Trained Tokens 3279931, Peak mem 236.340 GB
Iter 2350: Train loss 0.196, Learning Rate 9.005e-06, It/sec 0.065, Tokens/sec 76.131, Trained Tokens 3291607, Peak mem 236.340 GB
Iter 2360: Train loss 0.230, Learning Rate 8.996e-06, It/sec 0.052, Tokens/sec 81.457, Trained Tokens 3307229, Peak mem 236.340 GB
Iter 2370: Train loss 0.265, Learning Rate 8.986e-06, It/sec 0.058, Tokens/sec 82.938, Trained Tokens 3321615, Peak mem 236.340 GB

  [30.10.2024, 21:51:48 Wiederhergestellt]
Last login: Wed Oct 30 21:51:45 on console
```

**To Reproduce**

`mlx_lm.lora --config "fine_tuning/mlx/llama3_1_8B_instruct_lora_config.yaml"``

```yaml
model: "meta-llama/Meta-Llama-3.1-8B-Instruct"
train: true
# The fine-tuning method: "lora", "dora", or "full".
fine_tune_type: lora
data: "fine_tuning/data/rev2"
seed: 0
num_layers: 32
batch_size: 1
iters: 10290
val_batches: 25
learning_rate: 1e-5
steps_per_report: 10
steps_per_eval: 200
resume_adapter_file: null
adapter_path: "results/llama3_1_8B_instruct_lora/tuning_15/adapters"
save_every: 100
test: true
test_batches: -1
max_seq_length: 8192
grad_checkpoint: true
lora_parameters:
  keys: [
    "self_attn.q_proj",
    "self_attn.v_proj",
    "self_attn.k_proj",
    "self_attn.o_proj",
    "mlp.gate_proj",
    "mlp.down_proj",
    "mlp.up_proj"
  ]
  scale: 1
  rank: 32
  dropout: 0.1
lr_schedule:
  name: cosine_decay
  warmup: 309 # 0 for no warmup
  warmup_init: 0
  arguments: [
    1e-5,
    9981,
    0
  ]
```

**Expected behavior**
That the memory consumption remains the same and there is no crash.

**Desktop (please complete the following information):**
 - OS Version: [MacOS 15.0.1]
 - MLX Version [0.19.1]
 - MLX-LM Version [0.19.2]

**Additional context**

Log from a month ago when it still worked with a similar configuration:

```bash
(dartgen) admin@MBPvonH dartgen % date
Fr 20 Sep 2024 17:08:10 CEST
(dartgen) admin@MBPvonH dartgen % mlx_lm.lora --config "fine_tuning/lora_config.yaml"
Loading configuration file fine_tuning/lora_config.yaml
Loading pretrained model
Fetching 11 files: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 11/11 [00:00<00:00, 159094.29it/s]
Loading datasets
Training
Trainable parameters: 1.045% (83.886M/8030.261M)
Starting training..., iters: 10290
Iter 1: Val loss 0.698, Val took 88.051s
[WARNING] Some sequences are longer than 8192 tokens. The longest sentence 19453 will be truncated to 8192. Consider pre-splitting your data to save memory.
Iter 10: Train loss 0.711, Learning Rate 1.456e-06, It/sec 0.051, Tokens/sec 113.748, Trained Tokens 22358, Peak mem 121.504 GB
Iter 20: Train loss 0.691, Learning Rate 3.074e-06, It/sec 0.097, Tokens/sec 131.496, Trained Tokens 35934, Peak mem 121.504 GB
...
Iter 10220: Train loss 0.029, Learning Rate 6.419e-09, It/sec 0.142, Tokens/sec 136.709, Trained Tokens 14102462, Peak mem 121.504 GB
Iter 10230: Train loss 0.033, Learning Rate 4.758e-09, It/sec 0.127, Tokens/sec 136.872, Trained Tokens 14113259, Peak mem 121.504 GB
Iter 10240: Train loss 0.046, Learning Rate 3.347e-09, It/sec 0.058, Tokens/sec 130.574, Trained Tokens 14135730, Peak mem 121.504 GB
Iter 10250: Train loss 0.035, Learning Rate 2.185e-09, It/sec 0.086, Tokens/sec 135.763, Trained Tokens 14151482, Peak mem 121.504 GB
Iter 10260: Train loss 0.041, Learning Rate 1.268e-09, It/sec 0.086, Tokens/sec 137.544, Trained Tokens 14167447, Peak mem 121.504 GB
Iter 10270: Train loss 0.041, Learning Rate 5.975e-10, It/sec 0.046, Tokens/sec 96.664, Trained Tokens 14188391, Peak mem 121.504 GB
Iter 10280: Train loss 0.038, Learning Rate 1.803e-10, It/sec 0.100, Tokens/sec 133.021, Trained Tokens 14201681, Peak mem 121.504 GB
[WARNING] Some sequences are longer than 8192 tokens. The longest sentence 11907 will be truncated to 8192. Consider pre-splitting your data to save memory.
Iter 10290: Val loss 0.317, Val took 123.558s
Iter 10290: Train loss 0.031, Learning Rate 4.470e-12, It/sec 0.704, Tokens/sec 1178.573, Trained Tokens 14218430, Peak mem 121.504 GB
Saved final adapter weights to adapters/adapters.safetensors.
Testing
[WARNING] Some sequences are longer than 8192 tokens. The longest sentence 10044 will be truncated to 8192. Consider pre-splitting your data to save memory.
Test loss 0.243, Test ppl 1.275.
```

The configuration a month ago.
```
model: "meta-llama/Meta-Llama-3.1-8B-Instruct"
train: true
data: "fine_tuning/"
seed: 0
lora_layers: 32
batch_size: 1
iters: 10290
val_batches: 25
learning_rate: 5e-5
steps_per_report: 10
steps_per_eval: 200
resume_adapter_file: null
adapter_path: "adapters"
save_every: 100
test: true
test_batches: -1
max_seq_length: 8192
grad_checkpoint: true
use_dora: false
lora_parameters:
  keys: [
    "self_attn.q_proj",
    "self_attn.v_proj",
    "self_attn.k_proj",
    "self_attn.o_proj",
    "mlp.gate_proj",
    "mlp.down_proj",
    "mlp.up_proj"
  ]
  scale: 4
  rank: 32
  dropout: 0.05
lr_schedule:
  name: cosine_decay
  warmup: 309 # 0 for no warmup
  warmup_init: 0
  arguments: [
    5e-5,
    9981,
    0
  ] 
```

**Comment by hschaeufler** [comment]
> **Describe the bug** The required memory seems to increase continuously during fine-tuning. I train 5 epochs. Shortly after starting the 2nd epoch, my MacBook crashes because there is no more memory available. My data set contains 2058 entries and I train 10290 iterations. The peak memory increases in the meantime. With a similar configuration (and older MLX-Version), I was able to perform fine-tuning a month ago without crashing. I terminate all programms before starting to train.
> 
> ```
> dartgen % mlx_lm.lora --config "fine_tuning/mlx/llama3_1_8B_instruct_lora_config.yaml"
> Loading configuration file fine_tuning/mlx/llama3_1_8B_instruct_lora_config.yaml
> Loading pretrained model
> /Users/admin/.cache/huggingface/hub/models--meta-llama--Meta-Llama-3.1-8B-Instruct/snapshots/0e9e39f249a16976918f6564b8830bc894c89659
> Loading datasets
> Training
> Trainable parameters: 1.045% (83.886M/8030.261M)
> Starting training..., iters: 10290
> Iter 1: Val loss 0.655, Val took 87.790s
> [WARNING] Some sequences are longer than 8192 tokens. The longest sentence 19487 will be truncated to 8192. Consider pre-splitting your data to save memory.
> Iter 10: Train loss 0.784, Learning Rate 2.913e-07, It/sec 0.037, Tokens/sec 81.695, Trained Tokens 22075, Peak mem 121.550 GB
> Iter 20: Train loss 0.841, Learning Rate 6.149e-07, It/sec 0.084, Tokens/sec 115.019, Trained Tokens 35799, Peak mem 121.550 GB
> Iter 30: Train loss 0.812, Learning Rate 9.385e-07, It/sec 0.097, Tokens/sec 115.662, Trained Tokens 47775, Peak mem 121.550 GB
> Iter 40: Train loss 0.728, Learning Rate 1.262e-06, It/sec 0.075, Tokens/sec 113.291, Trained Tokens 62897, Peak mem 121.550 GB
> Iter 50: Train loss 0.629, Learning Rate 1.586e-06, It/sec 0.092, Tokens/sec 122.670, Trained Tokens 76177, Peak mem 121.550 GB
> Iter 60: Train loss 0.604, Learning Rate 1.909e-06, It/sec 0.071, Tokens/sec 119.333, Trained Tokens 93038, Peak mem 121.550 GB
> Iter 70: Train loss 0.544, Learning Rate 2.233e-06, It/sec 0.072, Tokens/sec 126.830, Trained Tokens 110709, Peak mem 121.550 GB
> Iter 80: Train loss 0.583, Learning Rate 2.557e-06, It/sec 0.120, Tokens/sec 129.292, Trained Tokens 121482, Peak mem 121.550 GB
> Iter 90: Train loss 0.617, Learning Rate 2.880e-06, It/sec 0.107, Tokens/sec 129.724, Trained Tokens 133588, Peak mem 121.550 GB
> Iter 100: Train loss 0.574, Learning Rate 3.204e-06, It/sec 0.128, Tokens/sec 129.965, Trained Tokens 143762, Peak mem 121.550 GB
> ...
>  Peak mem 236.340 GB
> Iter 2300: Saved adapter weights to results/llama3_1_8B_instruct_lora/tuning_15/adapters/adapters.safetensors and results/llama3_1_8B_instruct_lora/tuning_15/adapters/0002300_adapters.safetensors.
> Iter 2310: Train loss 0.235, Learning Rate 9.042e-06, It/sec 0.050, Tokens/sec 83.557, Trained Tokens 3243107, Peak mem 236.340 GB
> Iter 2320: Train loss 0.205, Learning Rate 9.033e-06, It/sec 0.075, Tokens/sec 81.691, Trained Tokens 3254004, Peak mem 236.340 GB
> Iter 2330: Train loss 0.248, Learning Rate 9.024e-06, It/sec 0.062, Tokens/sec 82.444, Trained Tokens 3267278, Peak mem 236.340 GB
> Iter 2340: Train loss 0.218, Learning Rate 9.015e-06, It/sec 0.065, Tokens/sec 82.367, Trained Tokens 3279931, Peak mem 236.340 GB
> Iter 2350: Train loss 0.196, Learning Rate 9.005e-06, It/sec 0.065, Tokens/sec 76.131, Trained Tokens 3291607, Peak mem 236.340 GB
> Iter 2360: Train loss 0.230, Learning Rate 8.996e-06, It/sec 0.052, Tokens/sec 81.457, Trained Tokens 3307229, Peak mem 236.340 GB
> Iter 2370: Train loss 0.265, Learning Rate 8.986e-06, It/sec 0.058, Tokens/sec 82.938, Trained Tokens 3321615, Peak mem 236.340 GB
> 
>   [30.10.2024, 21:51:48 Wiederhergestellt]
> Last login: Wed Oct 30 21:51:45 on console
> ```
> 
> **To Reproduce**
> 
> `mlx_lm.lora --config "fine_tuning/mlx/llama3_1_8B_instruct_lora_config.yaml"``
> 
> ```yaml
> model: "meta-llama/Meta-Llama-3.1-8B-Instruct"
> train: true
> # The fine-tuning method: "lora", "dora", or "full".
> fine_tune_type: lora
> data: "fine_tuning/data/rev2"
> seed: 0
> num_layers: 32
> batch_size: 1
> iters: 10290
> val_batches: 25
> learning_rate: 1e-5
> steps_per_report: 10
> steps_per_eval: 200
> resume_adapter_file: null
> adapter_path: "results/llama3_1_8B_instruct_lora/tuning_15/adapters"
> save_every: 100
> test: true
> test_batches: -1
> max_seq_length: 8192
> grad_checkpoint: true
> lora_parameters:
>   keys: [
>     "self_attn.q_proj",
>     "self_attn.v_proj",
>     "self_attn.k_proj",
>     "self_attn.o_proj",
>     "mlp.gate_proj",
>     "mlp.down_proj",
>     "mlp.up_proj"
>   ]
>   scale: 1
>   rank: 32
>   dropout: 0.1
> lr_schedule:
>   name: cosine_decay
>   warmup: 309 # 0 for no warmup
>   warmup_init: 0
>   arguments: [
>     1e-5,
>     9981,
>     0
>   ]
> ```
> 
> **Expected behavior** That the memory consumption remains the same and there is no crash.
> 
> **Desktop (please complete the following information):**
> 
> * OS Version: [MacOS 15.0.1]
> * MLX Version [0.19.1]
> * MLX-LM Version [0.19.2]
> 
> **Additional context**
> 
> Log from a month ago when it still worked with a similar configuration:
> 
> ```shell
> (dartgen) admin@MBPvonHolger2 dartgen % date
> Fr 20 Sep 2024 17:08:10 CEST
> (dartgen) admin@MBPvonHolger2 dartgen % mlx_lm.lora --config "fine_tuning/lora_config.yaml"
> Loading configuration file fine_tuning/lora_config.yaml
> Loading pretrained model
> Fetching 11 files: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 11/11 [00:00<00:00, 159094.29it/s]
> Loading datasets
> Training
> Trainable parameters: 1.045% (83.886M/8030.261M)
> Starting training..., iters: 10290
> Iter 1: Val loss 0.698, Val took 88.051s
> [WARNING] Some sequences are longer than 8192 tokens. The longest sentence 19453 will be truncated to 8192. Consider pre-splitting your data to save memory.
> Iter 10: Train loss 0.711, Learning Rate 1.456e-06, It/sec 0.051, Tokens/sec 113.748, Trained Tokens 22358, Peak mem 121.504 GB
> Iter 20: Train loss 0.691, Learning Rate 3.074e-06, It/sec 0.097, Tokens/sec 131.496, Trained Tokens 35934, Peak mem 121.504 GB
> ...
> Iter 10220: Train loss 0.029, Learning Rate 6.419e-09, It/sec 0.142, Tokens/sec 136.709, Trained Tokens 14102462, Peak mem 121.504 GB
> Iter 10230: Train loss 0.033, Learning Rate 4.758e-09, It/sec 0.127, Tokens/sec 136.872, Trained Tokens 14113259, Peak mem 121.504 GB
> Iter 10240: Train loss 0.046, Learning Rate 3.347e-09, It/sec 0.058, Tokens/sec 130.574, Trained Tokens 14135730, Peak mem 121.504 GB
> Iter 10250: Train loss 0.035, Learning Rate 2.185e-09, It/sec 0.086, Tokens/sec 135.763, Trained Tokens 14151482, Peak mem 121.504 GB
> Iter 10260: Train loss 0.041, Learning Rate 1.268e-09, It/sec 0.086, Tokens/sec 137.544, Trained Tokens 14167447, Peak mem 121.504 GB
> Iter 10270: Train loss 0.041, Learning Rate 5.975e-10, It/sec 0.046, Tokens/sec 96.664, Trained Tokens 14188391, Peak mem 121.504 GB
> Iter 10280: Train loss 0.038, Learning Rate 1.803e-10, It/sec 0.100, Tokens/sec 133.021, Trained Tokens 14201681, Peak mem 121.504 GB
> [WARNING] Some sequences are longer than 8192 tokens. The longest sentence 11907 will be truncated to 8192. Consider pre-splitting your data to save memory.
> Iter 10290: Val loss 0.317, Val took 123.558s
> Iter 10290: Train loss 0.031, Learning Rate 4.470e-12, It/sec 0.704, Tokens/sec 1178.573, Trained Tokens 14218430, Peak mem 121.504 GB
> Saved final adapter weights to adapters/adapters.safetensors.
> Testing
> [WARNING] Some sequences are longer than 8192 tokens. The longest sentence 10044 will be truncated to 8192. Consider pre-splitting your data to save memory.
> Test loss 0.243, Test ppl 1.275.
> ```
> 
> The configuration a month ago.
> 
> ```
> model: "meta-llama/Meta-Llama-3.1-8B-Instruct"
> train: true
> data: "fine_tuning/"
> seed: 0
> lora_layers: 32
> batch_size: 1
> iters: 10290
> val_batches: 25
> learning_rate: 5e-5
> steps_per_report: 10
> steps_per_eval: 200
> resume_adapter_file: null
> adapter_path: "adapters"
> save_every: 100
> test: true
> test_batches: -1
> max_seq_length: 8192
> grad_checkpoint: true
> use_dora: false
> lora_parameters:
>   keys: [
>     "self_attn.q_proj",
>     "self_attn.v_proj",
>     "self_attn.k_proj",
>     "self_attn.o_proj",
>     "mlp.gate_proj",
>     "mlp.down_proj",
>     "mlp.up_proj"
>   ]
>   scale: 4
>   rank: 32
>   dropout: 0.05
> lr_schedule:
>   name: cosine_decay
>   warmup: 309 # 0 for no warmup
>   warmup_init: 0
>   arguments: [
>     5e-5,
>     9981,
>     0
>   ] 
> ```

**Comment by hschaeufler** [comment]
I am currently testing it with a downgrade of the MLX version to the version of 20 Sep. The current peak mem seems to be stable at 121,504 GB.  But I'm only at Iter 710, so I'll report more tomorrow.

```
mlx = "0.17.3"
mlx-lm = "0.18.2"
...
transformers = "==4.44.2"
```

**Comment by hschaeufler** [comment]
With MLX 0.17.3 and Mlx-lm 0.18.2 there is no crash. Peak Memory is stable.

```
Iter 2700: Train loss 0.211, Learning Rate 7.850e-06, It/sec 0.084, Tokens/sec 134.516, Trained Tokens 3806066, Peak mem 121.504 GB
Iter 2700: Saved adapter weights to results/llama3_1_8B_instruct_lora/tuning_16/adapters/adapters.safetensors and results/llama3_1_8B_instruct_lora/tuning_16/adapters/0002700_adapters.safetensors.
Iter 2710: Train loss 0.270, Learning Rate 7.834e-06, It/sec 0.116, Tokens/sec 134.561, Trained Tokens 3817627, Peak mem 121.504 GB
Iter 2720: Train loss 0.206, Learning Rate 7.817e-06, It/sec 0.089, Tokens/sec 134.335, Trained Tokens 3832672, Peak mem 121.504 GB
Iter 2730: Train loss 0.320, Learning Rate 7.801e-06, It/sec 0.164, Tokens/sec 136.103, Trained Tokens 3840970, Peak mem 121.504 GB
Iter 2740: Train loss 0.219, Learning Rate 7.785e-06, It/sec 0.089, Tokens/sec 134.494, Trained Tokens 3856049, Peak mem 121.504 GB
Iter 2750: Train loss 0.193, Learning Rate 7.769e-06, It/sec 0.120, Tokens/sec 136.323, Trained Tokens 3867396, Peak mem 121.504 GB
Iter 2760: Train loss 0.244, Learning Rate 7.752e-06, It/sec 0.104, Tokens/sec 136.876, Trained Tokens 3880495, Peak mem 121.504 GB
```

**Comment by awni** [comment]
Thanks for flagging. I did confirm there is a leak with gradient checkpointing enabled. Looking into it.

**Comment by hschaeufler** [comment]
> Thanks for flagging. I did confirm there is a leak with gradient checkpointing enabled. Looking into it.

Many thanks for the quick fix. :)
