### ISSUE TITLE
Phi-2 speed is limited by memory on 8GB Macs

### ISSUE THREAD

**Issue by jbarrow** [ml-explore/mlx-examples#109]
Currently Phi-2 inferences at ~20s/tok on an 8GB machine, in spite of using ~10-20% of CPU/GPU at any given time. Bigger machines see much, much faster inference speeds. Imo, this points to the model being memory bound (although it uses ~5.4GB in fp16). I believe this will be solved by support for quantized models in MLX, but maybe somebody will see an obvious optimization in the model in the mean time.

**Comment by dx-dtran** [comment]
Oh interesting, Phi-2 only uses 5.4 GB during inference? Your implementation must be super efficient then 😆 thank you for your Phi-2 PR by the way!!

I thought it would be around 5.6 GB for the weights alone, and much more for the activations and KV cache -- perhaps there is swapping?

I got GPT-2 1.5B working on MLX in float32. With my M1 Pro 16GB, it generates at approx 0.06 seconds per token, but it uses ~10GB of RAM

https://github.com/dx-dtran/gpt2-mlx

**Comment by dx-dtran** [comment]
On my M1 Pro 16GB, I'm getting a decently fast 18 tokens per second. When you mentioned ~20s/tok, you mean 20 seconds for a single token right? 

I'm getting 56% CPU utilization and 94% GPU utilization as measured by Activity Monitor

**Comment by jbarrow** [comment]
Yup, 20 seconds per token. That a 16GB machine has flipped stats and such high CPU/GPU utilization I think confirms the fact that it’s a memory issue.

Perhaps the reported memory usage for me in activity monitor is only 5.4GB because the rest is being paged.

**Comment by iamwhatsall** [comment]
Anybody can tell me why my ph-2 doesn't output good response to my prompt? Is it because it lacks fine-tuning and not ready to chat? Or is there any thing I missed during installation or usage process? Thanks.

**Comment by jbarrow** [comment]
@iamwhatsall What response do you get to the default prompt?

**Comment by x4080** [comment]
Any link for .npz for phi-2 already shared on HF ?
Thanks, hopefully can test this soon

**Comment by jbarrow** [comment]
If you run `python convert.py` it will automatically download the weights and convert them to `.npz`. It will automatically save them in a file called `weights.npz`.

**Comment by x4080** [comment]
@jbarrow thanks

**Comment by iamwhatsall** [comment]
> @iamwhatsall What response do you get to the default prompt?

![Uploading Screenshot 2023-12-15 at 20.25.23.png…]()

**Comment by awni** [comment]
@jbarrow probably you are swapping which is somewhat surprising given the model size is not that big / should easily fit.  It's possible the max working set for a given token is >8GB but for a small prompt / only generating a few tens of tokens I wouldn't expect that.

Just FYI looking at total memory use isn't always that helpful as MLX is greedy. It will take up whatever memory it can and hold it for future allocations even if it isn't actively using it.

One thing to look at is the swap usage. Does it go way up when the model starts generating?

<img width="776" alt="Screenshot 2023-12-16 at 7 38 31 AM" src="https://github.com/ml-explore/mlx-examples/assets/1542805/ec7447f9-dfdc-4acd-98aa-23b67af68418">

**Comment by awni** [comment]
@iamwhatsall can't see your screenshot, maybe try uploading again..

**Comment by iamwhatsall** [comment]
Sorry about my last post. Here is the screenshot. Thanks. <img width="658" alt="1" src="https://github.com/ml-explore/mlx-examples/assets/88936522/1dde73b7-cbe0-437a-9712-dc77987d35bb">

**Comment by awni** [comment]
@jbarrow you could try replacing the [generation loop](https://github.com/ml-explore/mlx-examples/blob/main/phi2/phi2.py#L203-L225) with this to see if it reduces memory pressure:

```
    for token, _ in zip(generate(prompt, model, args.temp), range(args.max_tokens)):
        mx.simplify(token)
        if token == tokenizer.eos_token_id:
            break
        s = tokenizer.decode(token.item())
        print(s, end="", flush=True)
```

Let me know if it helps and we can update the example.

**Comment by awni** [comment]
@iamwhatsall are you using the latest `mlx-exmaples/phi2/`? It looks like you are missing the code to stop generating at the end of sentence token. Maybe try pulling the repo. I get more reasonable output for the same prompt:

```
[INFO] Generating with Phi-2...
Instruct:Introduce yourself please.\nOutput: Hello, my name is Alice and I am a student at Wonderland High. I like to read books, play chess, and bake cookies. I am looking forward to meeting you all and learning new things.
```

**Comment by iamwhatsall** [comment]
> @iamwhatsall are you using the latest `mlx-exmaples/phi2/`? It looks like you are missing the code to stop generating at the end of sentence token. Maybe try pulling the repo. I get more reasonable output for the same prompt:
> 
> ```
> [INFO] Generating with Phi-2...
> Instruct:Introduce yourself please.\nOutput: Hello, my name is Alice and I am a student at Wonderland High. I like to read books, play chess, and bake cookies. I am looking forward to meeting you all and learning new things.
> ```

It works! Thanks a lot. But I still expect it to generate better response than this. Maybe this is not the best prompt to make it show its real power :)

**Comment by jbarrow** [comment]
@awni Swap space used goes from about 800MB to ~4GB when the model is generating (even with the new loop). Not sure it helped overall speed.

**Comment by bigsnarfdude** [comment]
python phi2.py --prompt "Instruct:Why is the sky blue?.
\nOutput: "  --max_tokens 1024

@jbarrow using a m2pro 32gb. im just seeing same output for swap (up to 3gb for few seconds) as @awni. its fast and responsive

**Comment by jbarrow** [comment]
Quantized weights fix this! Speed is now *very* good. Excellent job @awni!
