### ISSUE TITLE
LoRA trains on tokens with duplicated BOS for some models

### ISSUE THREAD

**Issue by chimezie** [ml-explore/mlx-examples#1095]
During LoRa training, iterate_batches [calls](https://github.com/ml-explore/mlx-examples/blob/main/llms/mlx_lm/tuner/trainer.py#L104) `tokenizer.encode()` (with default arguments) on the dataset item, which in the case of ChatDataset or CompletionsDataset, returns the raw text with the model's chat template applied:

```python
tokenizer.apply_chat_template(.. conversation .., tokenize=False, add_generation_prompt=True)
```

Invoking `tokenizer.encode` with default arguments on the result of this can produced a token sequence with duplicated BOS tokens:

```python
In [..]: tokenizer = AutoTokenizer.from_pretrained("mistralai/Mistral-Nemo-Instruct-2407")

In [..]: message = [{"role": "user", "content": "Who is on first?"}, {"role": "assistant", "content": "Is that a trick question?"}]

In [..]: print(tokenizer.encode(tokenizer.apply_chat_template(message, tokenize=False, add_generation_prompt=True), add_special_tokens=False))
[1, 3, 31500, 1395, 1408, 2158, 1063, 4, 5356, 1455, 1261, 31544, 4098, 1063, 2]

In [..]: print(tokenizer.apply_chat_template(message, tokenize=True, add_generation_prompt=True))
[1, 3, 31500, 1395, 1408, 2158, 1063, 4, 5356, 1455, 1261, 31544, 4098, 1063, 2]

In [..]: print(tokenizer.encode(tokenizer.apply_chat_template(message, tokenize=False, add_generation_prompt=True)))
[1, 1, 3, 31500, 1395, 1408, 2158, 1063, 4, 5356, 1455, 1261, 31544, 4098, 1063, 2]

In [..]: tokenizer = AutoTokenizer.from_pretrained("google/gemma-2-2b-it")

In [..]: print(tokenizer.apply_chat_template(message, tokenize=True, add_generation_prompt=True))
[2, 106, 1645, 108, 6571, 603, 611, 1370, 235336, 107, 108, 106, 2516, 108, 2437, 674, 476, 17760, 2872, 235336, 107, 108, 106, 2516, 108]

In [..]: print(tokenizer.encode(tokenizer.apply_chat_template(message, tokenize=False, add_generation_prompt=True)))
[2, 2, 106, 1645, 108, 6571, 603, 611, 1370, 235336, 107, 108, 106, 2516, 108, 2437, 674, 476, 17760, 2872, 235336, 107, 108, 106, 2516, 108]

In [..]: tokenizer = AutoTokenizer.from_pretrained("Qwen/Qwen2.5-7B-Instruct")

In [..]: print(tokenizer.apply_chat_template(message, tokenize=True, add_generation_prompt=True))
[151644, 8948, 198, 2610, 525, 1207, 16948, 11, 3465, 553, 54364, 14817, 13, 1446, 525, 264, 10950, 17847, 13, 151645, 198, 151644, 872, 198, 15191, 374, 389, 1156, 30, 151645, 198, 151644, 77091, 198, 3872, 429, 264, 14068, 3405, 30, 151645, 198, 151644, 77091, 198]

In [..]: print(tokenizer.encode(tokenizer.apply_chat_template(message, tokenize=False, add_generation_prompt=True)))
[151644, 8948, 198, 2610, 525, 1207, 16948, 11, 3465, 553, 54364, 14817, 13, 1446, 525, 264, 10950, 17847, 13, 151645, 198, 151644, 872, 198, 15191, 374, 389, 1156, 30, 151645, 198, 151644, 77091, 198, 3872, 429, 264, 14068, 3405, 30, 151645, 198, 151644, 77091, 198]

In [..]: tokenizer = AutoTokenizer.from_pretrained("microsoft/Phi-3-mini-128k-instruct")

In [..]: print(tokenizer.apply_chat_template(message, tokenize=True, add_generation_prompt=True))
[32010, 11644, 338, 373, 937, 29973, 32007, 32001, 1317, 393, 263, 8938, 1139, 29973, 32007, 32001]

In [..]: print(tokenizer.encode(tokenizer.apply_chat_template(message, tokenize=False, add_generation_prompt=True)))
[32010, 11644, 338, 373, 937, 29973, 32007, 32001, 1317, 393, 263, 8938, 1139, 29973, 32007, 32001]

```

In the cases above, the BOS duplication occurs with _Mistral-Nemo-Instruct-2407_ and _gemma-2-2b-it_ but not the others.

Invoking encode this way (with `add_special_tokens=False`):
```python
 tokenizer.encode(
    tokenizer.apply_chat_template(.. conversation .., tokenize=False, add_generation_prompt=True),
    add_special_tokens=False
)
```
or by using apply_chat_template with tokenize=False  (which seems like the more appropriate solution) should address this.

**Comment by awni** [comment]
Thanks for raising this issue.. this is likely a bug we have in for some tokenizers in generate as well.

I think the situation is:
- If it's an instruct model (ie. a model with a chat template) then applying the chat template followed by encoding does not require adding special tokens. The chat template adds the special tokens.
- If it's a non instruct model then we don't apply the chat template so special tokens should be added when you encode.

It's pretty messy to try and auto-detect if the prompt needs to be encoded with or without the special tokens so I think the right fix is to move the encoding to an earlier point where we know if special tokens are needed or not..I will work on a fix for this.

**Comment by awni** [comment]
Actually, upon further investigation, I think the tokenizers for instruct models which have a chat template should not have `add_bos_token = True`. So for `Mistral-Nemo-Instruct-2407` and `gemma-2-2b-it` maybe the right thing to do is file an issue against the HF repos and ask them to fix the tokenizer config.

**Comment by awni** [comment]
I fixed the tokenizers configuration for these models in the mlx-community. You can use e.g.:

`mlx-community/Mistral-Nemo-Instruct-2407-bf16` and `mlx-community/gemma-2-2b-it` instead of the ones you are using. I am closing this for now as I think this is mostly a tokenizer configuration mistake.. if you find any more issues with models please let us know.
