### ISSUE TITLE
libc++abi: Unable to build metal library from source error: invalid value 'metal3.1' in '-std=metal3.1'

### ISSUE THREAD

**Issue by maxlund** [ml-explore/mlx-examples#1102]
Hello!

Having issues running `mlx-whisper` on both these machines:

MacBook Pro with Ventura 13.7 (22H123), M1 Max, and a MacStudio M2 Max.
![image](https://github.com/user-attachments/assets/f5669f0a-71b5-414a-b2c1-4940cbdb5aeb)
![image](https://github.com/user-attachments/assets/fbc022aa-8e34-4c78-bcfb-57d562457b1d)

AFAIK it should be supported on 13.7, according to https://support.apple.com/en-gb/102894

Like the subject says, the error we get is:
```
libc++abi: terminating due to uncaught exception of type std::runtime_error: [metal::Device] Unable to build metal library from source
error: invalid value 'metal3.1' in '-std=metal3.1'
note: use 'ios-metal1.0' for 'Metal 1.0 (iOS)' standard
note: use 'ios-metal1.1' for 'Metal 1.1 (iOS)' standard
note: use 'ios-metal1.2' for 'Metal 1.2 (iOS)' standard
note: use 'ios-metal2.0' for 'Metal 2.0 (iOS)' standard
note: use 'ios-metal2.1' for 'Metal 2.1 (iOS)' standard
note: use 'ios-metal2.2' for 'Metal 2.2 (iOS)' standard
note: use 'ios-metal2.3' for 'Metal 2.3 (iOS)' standard
note: use 'ios-metal2.4' for 'Metal 2.4 (iOS)' standard
note: use 'macos-metal1.0' or 'osx-metal1.0' for 'Metal 1.0 (macOS)' standard
note: use 'macos-metal1.1' or 'osx-metal1.1' for 'Metal 1.1 (macOS)' standard
note: use 'macos-metal1.2' or 'osx-metal1.2' for 'Metal 1.2 (macOS)' standard
note: use 'macos-metal2.0' or 'osx-metal2.0' for 'Metal 2.0 (macOS)' standard
note: use 'macos-metal2.1' for 'Metal 2.1 (macOS)' standard
note: use 'macos-metal2.2' for 'Metal 2.2 (macOS)' standard
note: use 'macos-metal2.3' for 'Metal 2.3 (macOS)' standard
note: use 'macos-metal2.4' for 'Metal 2.4 (macOS)' standard
note: use 'metal3.0' for 'Metal 3.0' standard
```
Any ideas what the issue is?

**Comment by maxlund** [comment]
Ok I think I found the issue here: https://developer.apple.com/metal/Metal-Shading-Language-Specification.pdf
![image](https://github.com/user-attachments/assets/6d5660fd-ed33-4dfd-a6ee-8a97a0703d40)

> "metal3.1 supports programs for macOS 14"

Guessing that's the issue - we're trying to run something built with metal3.1 on macOS 13.7, and we need to be on >=14?

Feel free to verify and/or close this if so!

**Comment by awni** [comment]
Yea that is most likely the problem. I think it's a bug though.. we should be picking the right version of metal  (metal 3.0) when we build the 13.5+ MLX. I will investigate that.

**Comment by awni** [comment]
How did you install MLX?

**Comment by maxlund** [comment]
Via pip

**Comment by awni** [comment]
Could you do:

```
>> DIR=`python -c "import mlx.core as mx; import pathlib; print(pathlib.Path(mx.__file__).parent.parent)"`
>> cat ${DIR}/mlx-0.20.0.dist-info/WHEEL                                                                  
```

And report the result? I just want to make sure it installed the correct wheel.

**Comment by maxlund** [comment]
Doesn't look like I have `mlx-0.20.0`, but `mlx-0.18.0`
```
(.venv) maxlund @ Maxs-MacBook-Pro ~/clone/ffinder (main)
└─ $ ▶  echo $DIR
/Users/maxlund/clone/ffinder/.venv/lib/python3.10/site-packages
(.venv) maxlund @ Maxs-MacBook-Pro ~/clone/ffinder (main)
└─ $ ▶  ls $DIR | grep mlx
mlx
mlx-0.18.0.dist-info
mlx_whisper
mlx_whisper-0.3.0.dist-info
(.venv) maxlund @ Maxs-MacBook-Pro ~/clone/ffinder (main)
└─ $ ▶  cat /Users/maxlund/clone/ffinder/.venv/lib/python3.10/site-packages/mlx-0.18.0.dist-info/WHEEL
Wheel-Version: 1.0
Generator: setuptools (75.1.0)
Root-Is-Purelib: false
Tag: cp310-cp310-macosx_14_0_arm64
```

**Comment by maxlund** [comment]
Btw, can confirm that the person I distributed our application to fixed it on his MBP after upgrading to macOS >=14

**Comment by awni** [comment]
> cp310-cp310-macosx_14_0_arm64

That's strange. It's downloading macosx_14_0 but you have macOS 13.7. Pypi should (?) download the 13.0 wheel which is like this: `mlx-0.20.0-cp310-cp310-macosx_13_0_arm64.whl`.

**Comment by awni** [comment]
> Btw, can confirm that the person I distributed our application to fixed it on his MBP after upgrading to macOS >=14

For sure and I recommend doing so.. but 13.7 should still work given that we say it does. It's odd it's not downloading the right wheel for you 🤔 .

**Comment by maxlund** [comment]
Well that would explain it since the application builds a Python binary that we bundle, and this is what was sent to the 13.7 user. So you probably don't have a bug I guess, and we should just say we require macOS >=14 to run our application.

**Comment by awni** [comment]
Makes sense! In the future we’ll  consider doing these types of metal based version dispatches at runtime to make binary distribution simpler.
