### ISSUE TITLE
mlx_lm.generate --system-prompt doesn't convert `\n` as new line.

### ISSUE THREAD

**Issue by chigkim** [ml-explore/mlx-examples#1120]
If I include `\n` in --system-prompt `"xxx\nyyy"`, it seems to just feed the characters `\n` to the model instead of a new line.

**Comment by awni** [comment]
This shell escapes the `\` before sending to Python and I believe this dependent behavior. If you are using bash or zsh (and maybe others, not sure) then you can do `$'system\nprompt'` and it will not escape it. For example:

```
mlx_lm.generate --system-prompt $'You\nare\na\nhelpful\nAI\nassistant' --prompt "Write a story about Einstein"
```
