### ISSUE TITLE
API Clarity: load_model vs load_models Module Structure

### ISSUE THREAD

**Issue by 4rash-4** [ml-explore/mlx-examples#1126]
### Current Behavior
The current API structure can lead to confusion when attempting to use `load_model`. Users might try:
```python
import mlx_whisper
model = mlx_whisper.load_model()  # Raises AttributeError
```

### Expected Behavior
Either:
1. Provide a clear error message directing users to the correct import
2. Add a top-level alias for commonly used functions
3. Update documentation to highlight this distinction

### Actual Error
```python
AttributeError: module 'mlx_whisper' has no attribute 'load_model'. Did you mean: 'load_models'?
```

### Proposed Solutions
1. Add a top-level alias:
```python
# In mlx_whisper/__init__.py
from .load_models import load_model
```

2. Or enhance error messages:
```python
# In mlx_whisper/__init__.py
def load_model(*args, **kwargs):
    raise AttributeError(
        "load_model() is not available directly. Use either:\n"
        "1. mlx_whisper.transcribe(audio, path_or_hf_repo='model_name')\n"
        "2. from mlx_whisper.load_models import load_model"
    )
```

### Additional Context
This issue was discovered while developing AI tooling for MLX-Whisper integration. The current structure, while logical, can be unintuitive for new users and automated tools.

### Version Info
- mlx-whisper version: 0.4.1
- Python version: 3.11
- Platform: macOS (Apple Silicon)

**Comment by awni** [comment]
Closing as inactive. Feel free to send a PR to fix this if it's still of interest.
