### ISSUE TITLE
The problem of stream_generate() method returning Chinese

### ISSUE THREAD

**Issue by catman002** [ml-explore/mlx-examples#1136]
When I call the big model and use stream_generate() to return the Chinese result, the effect is the same as the result returned by generate(). It only returns greetings generated from all texts, and the waiting time is relatively long; If the return result is in English, stream_generate() returns the streaming result.

### Here are my code calls and result processing:

```
streamer = stream_generate(self.model,self.tokenizer,prompt=chat_template,max_tokens=generation_config.max_new_tokens,sampler=sampler,prompt_cache=self.prompt_cache)

for response in streamer:
    print(response.text, end="", flush=True)
```
### Why is that?

**Comment by awni** [comment]
I'm not following your comment. Could you share example inputs and outputs and what you expect to happen?

**Comment by catman002** [comment]
> I'm not following your comment. Could you share example inputs and outputs and what you expect to happen?
```
 content="请写一篇100字描写冬天的作文"
 #content=“Please write a 100 word article describing winter”
  chat_template = self.tokenizer.apply_chat_template(
            content,
            add_generation_prompt=True,
            tokenize=False,
            prompt_cache=self.prompt_cache
        )
streamer = stream_generate(self.model,self.tokenizer,prompt=chat_template,max_tokens=generation_config.max_new_tokens,sampler=sampler,prompt_cache=self.prompt_cache)

for response in streamer:
    print(response.text, end="", flush=True)
```
### The result of my test is:
If the content is in Chinese, it cannot be output in streaming format; 
If the content is in English, it can be output in a streaming format.

The models I use are: qwen, llma, gemma .

**Comment by awni** [comment]
I think I understand what you are saying now. If the content is chinese character, it will output good results but it will wait until the end to output them.

**Comment by awni** [comment]
This is due to the streaming BPE decoder. Right now we only decode if we encounter a space and there are no spaces in Chinese characters.

I think we can to fix this by having a proper utf-8 streaming decoder. Once a utf-8 sequence is complete we can decode it safely.

**Comment by madroidmaq** [comment]
I'm not sure if the problem I encountered is the same. The error stack is as follows:

```log
ERROR: Failed to generate completion: 'utf-8' codec can't decode bytes in position 0-1: invalid continuation byte
Traceback (most recent call last):
  File "/Users/madroid/develop/workspace/mlx-omni-server/src/mlx_omni_server/services/chat/mlx_model.py", line 164, in generate
    async for result in self._stream_generate(
  File "/Users/madroid/develop/workspace/mlx-omni-server/src/mlx_omni_server/services/chat/mlx_model.py", line 88, in _stream_generate
    for response in stream_generate(
  File "/Users/madroid/Library/Caches/pypoetry/virtualenvs/mlx-omni-server-2ieLigwp-py3.11/lib/python3.11/site-packages/mlx_lm/utils.py", line 340, in stream_generate
    detokenizer.add_token(token)
  File "/Users/madroid/Library/Caches/pypoetry/virtualenvs/mlx-omni-server-2ieLigwp-py3.11/lib/python3.11/site-packages/mlx_lm/tokenizer_utils.py", line 205, in add_token
    ).decode("utf-8")
      ^^^^^^^^^^^^^^^
UnicodeDecodeError: 'utf-8' codec can't decode bytes in position 0-1: invalid continuation byte
```

The same prompt does not always lead to this issue.

PS, mlx_lm version is  `0.20.1`

**Comment by catman002** [comment]
@awni  Great, I have already seen the modified effect.
