### ISSUE TITLE
Requests for add the model LGAI-EXAONE/EXAONE-3.5 Model.

### ISSUE THREAD

**Issue by SOSONAGI** [ml-explore/mlx-examples#1150]
I've been using the mlx for long time.

Really appreciate for MLX.

The model EXAONE is good model. If it is possible to adds on llms, could you please add the model?

LGAI currently uploaded 3 new models

LGAI-EXAONE/EXAONE-3.5-2.4B-Instruct
LGAI-EXAONE/EXAONE-3.5-7.8B-Instruct
LGAI-EXAONE/EXAONE-3.5-32B-Instruct

Thank you very much.

**Comment by awni** [comment]
The model is already been added thanks to @N8python ! It can be used on main and will be in the next release. You can find [them in the MLX Community](https://huggingface.co/collections/mlx-community/exaone-35-67576b81c079403dcc1a2ce9)

**Comment by awni** [comment]
I just sent a new release to PyPi so you can update `pip install -U mlx-lm` and it should run.
