### ISSUE TITLE
mlx_lm.chat error in stream_generate

### ISSUE THREAD

**Issue by ivanfioravanti** [ml-explore/mlx-examples#1151]
Chat is not working anymore after stream_generated refactoring: "stream_generate() takes 3 positional arguments but 4 were given"

**Comment by awni** [comment]
It should be fixed on main. I'll put out a new release shortly.

**Comment by ivanfioravanti** [comment]
You are totally right! I should not tocuh code so early in the morning 🤣

**Comment by awni** [comment]
😄  

I just sent a new release to PyPi (0.20.3).
