### ISSUE TITLE
Issue with trying the Phi-2 model

### ISSUE THREAD

**Issue by muditbhargava66** [ml-explore/mlx-examples#117]
I am having an issue with this thing and am not able to resolve only for the PHI-2:

```bash
python3.10 phi2.py
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
[INFO] Generating with Phi-2...
Write a detailed analogy between mathematics and a lighthouse.2023-12-15 16:38:19.662443: F tensorflow/c/experimental/stream_executor/stream_executor.cc:743] Non-OK-status: stream_executor::MultiPlatformManager::RegisterPlatform( std::move(cplatform)) status: INTERNAL: platform is already registered with name: "METAL"
zsh: abort      python3.10 phi2.py
```

**Attempted Fixes**
- Upgraded to the latest TensorFlow version
- Set TF_FORCE_UNIFIED_MEMORY=1
- Uninstalled and cleanly reinstalled TensorFlow

**Comment by awni** [comment]
This is super odd, you shouldn't even need TensorFlow for this example, it's not a dependency.

Maybe try updating your Transformers:

`pip install -U transformers`

**Comment by muditbhargava66** [comment]
I tried to update the transformers, but I still encountered the same error.

**Comment by awni** [comment]
This seems like your environment corrupted or in a wonky state. Are you able to do anything with `mlx`? Like what happens if you do:

```
import mlx
a = mlx.zeros((2, 2))
print(a)
```

Maybe try uninstalling TensorFlow and/or making a clean conda env?

**Comment by munterwexi** [comment]
I have also issues with running the convert.py - 

it requires CUDA for the flash_attn module, which is not available obviously on my m1 macbook pro. 
is there a way to publish the .npz files with the weights on huggingface? or to workaround this issue?

thanks

**Comment by awni** [comment]
I think you are using an old version of Transformers try: `pip install -U transformers`. I will put a minimum version requirement on it!

**Comment by munterwexi** [comment]
That fixed the problem for me, thank you very much for the fast help!
