### ISSUE TITLE
mlx_lm.server: how to set context size?

### ISSUE THREAD

**Issue by chigkim** [ml-explore/mlx-examples#1170]
It looks like I can set context size on mlx_lm.generate with --max-kv-size.
However, mlx_lm.server doesn't seem to have that option from command line nor api via http request.
Does it just allocate the maximum context size for the loaded model?
Or, max-kv-size is not what I'm thinking?
Thanks!

**Comment by awni** [comment]
Right now MLX LM server doesn't support that. No reason for that other than reactive feature support for MLX server..  

To make it work basically we would need to get it from the request and [set it here](https://github.com/ml-explore/mlx-examples/blob/main/llms/mlx_lm/server.py#L434) where the prompt cache is made. And if the max_kv_size is changed even if the model remains the same, we'd need to reset / make a new cache.

**Comment by chigkim** [comment]
Thanks for the response.
How does mlx_lm.server set the context size currently then?
Does it use the maximum context size of the loaded model, or does it allocate dynamically based on prompt size and max_tokens?
Thanks!

**Comment by awni** [comment]
The context size not set in the server. So it can grow arbitrarily large with the prompt / tokens being generated.

**Comment by chigkim** [comment]
Ah ok. If it just dynamically accommodates prompt + output, I guess you don't need this feature. Closing it.
Thanks!

**Comment by mattharrison** [comment]
You need to specify the size with the server and `--max-tokens`, the default is a pitiful 512.

Here's my writeup for using Aider with the server: https://github.com/Aider-AI/aider/issues/4526
