### ISSUE TITLE
Problem using “mlx-community/Llama-3.2-11B-Vision-Instruct-8bit”

### ISSUE THREAD

**Issue by homerokzam** [ml-explore/mlx-examples#1172]
I'm trying to use the Problem template using “mlx-community/Llama-3.2-11B-Vision-Instruct-8bit” but I'm having the following problem: 
Model type mllama not supported.
ModuleNotFoundError: No module named 'mlx_lm.models.mllama'

I have installed the libs: mlx and mlx-lm

**Comment by awni** [comment]
MLX LM doesn't support vision models yet. You could try using [MLX VLM](https://github.com/blaizzy/mlx-vlm)

**Comment by homerokzam** [comment]
Thank you very much for your help.

**Comment by JoeJoe1313** [comment]
Hello @awni, are you planning on officially supporting vision models anytime in the future?

**Comment by awni** [comment]
If you need vision models I suggest trying out [MLX VLM](https://github.com/blaizzy/mlx-vlm). That is a complete package built on top of MLX LM that supports most SOTA vision LMs. Whether or not we include them in MLX Examples directly is open right now with no concrete plan either way. But we would definitely be in communication with @Blaizzy (creator/maintainer of MLX VLM) and the rest of the community about it.

We also support [vision LMs in Swift](https://github.com/ml-explore/mlx-swift-examples/tree/main/Libraries/MLXVLM) for running on other devices and in Apps.

**Comment by JoeJoe1313** [comment]
Thank you for the answer! I was exploring mlx-vlm but had missed vision LMs in Swift, I’ll definitely take a look at it!
