### ISSUE TITLE
[Feature Request] sentence-transformers embeddings

### ISSUE THREAD

**Issue by jpcompartir** [ml-explore/mlx-examples#1175]
First, thanks for all of the great work - MLX is proving very useful in so many ways.

To the point - I've been looking at using MLX for the tasks we currently perform via CUDA with [sentence-transformers](https://huggingface.co/sentence-transformers) - i.e. batch embedding documents (in the 10^4-10^6 range), and I'm wondering if this is planned to be supported by mlx_lm in the future, or if there's a need for contributions?

A somewhat-related issue on [BERT implementation](https://github.com/ml-explore/mlx-examples/issues/262) seems to have been dealt with.
The related [PR](https://github.com/ml-explore/mlx-examples/pull/263) was closed and it was suggested this could/should be done in a community package, so apologies if I've missed the correct one, but...

I've noticed that there are some community packages for this purpose (as mentioned in the PR), but they do not seem as developed as mlx.core, mlx.nn or mlx_lm. Furthermore, I was testing their outputs against the original implementations run via CUDA, and they are incomparable- both in actual values (some difference is expected as values differ across GPUs even with CUDA), but also crucially in downstream tasks such as clustering (partly due to pooling strategies, which can be fixed, but I suspect also partly due to implementation details, let me know if clustering outputs and ARI/NMI across hardware would be handy here).

To be more concrete, we would like to use models like [all-mpnet-base-v2](https://huggingface.co/sentence-transformers/all-mpnet-base-v2) and the [bge family](https://huggingface.co/BAAI/bge-base-en-v1.5) to generate document-embeddings via MLX, at some scale and with efficient batching.

**Comment by awni** [comment]
Did you try either of these packages: [mlx-embeddings](https://github.com/Blaizzy/mlx-embeddings) or [mlx_embedding_models](https://github.com/taylorai/mlx_embedding_models) ?

I would recommend:
- Checking those packages
- If the model you want is missing or buggy, file an issue
- Alternatively you could implement it yourself using the MLX BERT example as a starting point

We don't have plans ourselves to support embedding models in MLX LM.

**Comment by jpcompartir** [comment]
Hi Awni, 

Yes I have tried them - I didn't want to reference any particular packages shortcomings. I'll look into PR'ing my implementation of MPNet and a batch pipeline to avoid the current memory issues I'm finding in the packages, thanks
