### ISSUE TITLE
Run example Error : got an unexpected keyword argument 'use_scaled_rope'

### ISSUE THREAD

**Issue by hsoftxl** [ml-explore/mlx-examples#1181]
Traceback (most recent call last):
  File "/Users/rays/PycharmProjects/mlx-examples/llms/llama/llama.py", line 379, in <module>
    model, tokenizer = load_model(args.model_path)
  File "/Users/rays/PycharmProjects/mlx-examples/llms/llama/llama.py", line 340, in load_model
    model = Llama(ModelArgs(**config))
TypeError: ModelArgs.__init__() got an unexpected keyword argument 'use_scaled_rope'

**Comment by awni** [comment]
That example is a bit outdated and only works with Llama <= 2. You can use LLama 3+ with [MLX LM](https://github.com/ml-explore/mlx-examples/blob/main/llms/README.md)

**Comment by awni** [comment]
That example is a bit outdated and only works with Llama <= 2. You can use LLama 3+ with [MLX LM](https://github.com/ml-explore/mlx-examples/blob/main/llms/README.md)
