### ISSUE TITLE
mlx_lm.server is slow to generate a response 

### ISSUE THREAD

**Issue by Baitur5** [ml-explore/mlx-examples#1183]
When I use mlx_lm.chat with a model, it responds to my prompt instantly. But when I use mlx_lm.server, it takes 2 to 4 seconds to reply. Why is there a delay? I use mlx version 0.21.1

**Comment by awni** [comment]
Could you share the commands you ran for both?

**Comment by Baitur5** [comment]
I figured it out, it was because there were several simultaneous requests to **mlx_lm.server**, it was waiting for the earlier one to finish. Is there a way to parallelize answering to the prompts instead of waiting for earlier one to finish?

> Could you share the commands you ran for both?

**Comment by awni** [comment]
> I figured it out

Nice!

>  Is there a way to parallelize answering to the prompts instead of waiting for earlier one to finish?

At the moment no.
