### ISSUE TITLE
Config.json -> Params.json

### ISSUE THREAD

**Issue by fakerybakery** [ml-explore/mlx-examples#120]
Hi,
I'm completely new to MLX. I want to convert [TinyLlama](https://huggingface.co/TinyLlama/tinyLlama-intermediate-checkpoints-after-1T-token/tree/main) to MLX and I'm trying to convert a HuggingFace config.json to params.json. Is there any way to do this?
Thank you!

**Comment by jbarrow** [comment]
One option (used for BERT and Phi-2, and maybe others) is to just define a `dataclass` that holds the config variables, and a dict from model names to instances of that dataclass. Check out this as an example:

https://github.com/ml-explore/mlx-examples/blob/main/bert/model.py#L25
