### ISSUE TITLE
Cifar training unsuccessful

### ISSUE THREAD

**Issue by ChangweiZhou** [ml-explore/mlx-examples#124]
I am using a Mac Pro3 with Python installed using Anaconda. I got the following error:

ImportError: ......./anaconda3/lib/python3.11/site-packages/mlx/data/_c.cpython-311-darwin.so, 0x0002): Library not loaded: /opt/homebrew/opt/libsndfile/lib/libsndfile.1.dylib
  Referenced from: <9F7752F7-AB7A-3025-A4B7-0EFABE6D194E> /Users/pencilbard/anaconda3/lib/python3.11/site-packages/mlx/data/_c.cpython-311-darwin.so
  Reason: tried: '/opt/homebrew/opt/libsndfile/lib/libsndfile.1.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/opt/homebrew/opt/libsndfile/lib/libsndfile.1.dylib' (no such file), '/opt/homebrew/opt/libsndfile/lib/libsndfile.1.dylib' (no such file)

Can someone help?

Note the same set up works fine for the transformer_lm task.

**Comment by awni** [comment]
It looks like an issue with mlx-data. Did you install it following [these instructions](https://ml-explore.github.io/mlx-data/build/html/install.html#dependencies)?

**Comment by ChangweiZhou** [comment]
Okay it is working now.

**Comment by ChangweiZhou** [comment]
It is working now.
