### ISSUE TITLE
How to get token per sec info when generate?

### ISSUE THREAD

**Issue by katopz** [ml-explore/mlx-examples#125]
I can see [The above command on an M1 Max with 32 GB runs at about 250 tokens-per-second.](https://github.com/ml-explore/mlx-examples/blob/main/lora/README.md) mentions there, not sure how can I also get that info when generate?

**Comment by awni** [comment]
The LoRA example doesn't time generation, but you could easily wrap [that part](https://github.com/ml-explore/mlx-examples/blob/main/lora/lora.py#L315-L326) in a timer.

Alternatively you can also use the [llama example](https://github.com/ml-explore/mlx-examples/tree/main/llama) which does time generation.
