### ISSUE TITLE
Error when running mnist example

### ISSUE THREAD

**Issue by nmrenyi** [ml-explore/mlx-examples#13]
When I run `python main.py` in `mnist`folder, here's the output
```
HELLO WORLD!
Traceback (most recent call last):
  File "/Users/renyi/Code/mlx-examples/mnist/main.py", line 8, in <module>
    import mlx.core as mx
ModuleNotFoundError: No module named 'mlx.core'
```

I've already installed `mlx` with `pip install mlx` but it still doesn't work

Here are some information about my machine and environment

MacBook Air M2 with 24GB memory

ProductName: macOS
ProductVersion: 14.1.1
BuildVersion: 23B81

Python Version: 3.12.0
Pip Version: 23.3.1

**Comment by marcj** [comment]
You have likely a mismatch in your python interpreters. `pip` probably points to a different python binary than the one you are using to execute `main.py`. To make sure `mlx` is installed in the correct python environment, you can use `python -m pip install mlx`. Then you can check if it worked by executing `python -c 'import mlx.core'`. This should not print any errors.

**Comment by nmrenyi** [comment]
@marcj Still doesn't work

<img width="566" alt="Screenshot 2023-12-06 at 22 22 44" src="https://github.com/ml-explore/mlx-examples/assets/46751328/0202af7e-5748-40fb-8427-8e0ea98c9a11">

**Comment by marcj** [comment]
where is `HELLO WORLD!` coming from? That should not be there.
Try to switch your cwd to /tmp (`cd /tmp`) and execute `python -c 'import mlx.core'` again. maybe you have a folder/file `mlx.py` interfering with module resolving.

**Comment by msitarzewski** [comment]
For what it's worth, I ran into a similar issues. I used the recommended pip install mlx and pip install -r requirements.txt
when what worked was **pip3** install mlx and **pip3** install -r requirements.txt
