### ISSUE TITLE
Ask your PDF example

### ISSUE THREAD

**Issue by angelo-smartsheet** [ml-explore/mlx-examples#142]
Processing / finetuning with local files will be a widely used use-case for mlx. Would be nice if there was an example on how to fine tune with local pdf files using a vectordb like pinecone and ask your PDF's something.

**Comment by CosasDePuma** [comment]
Any news on this?

**Comment by awni** [comment]
We should close this as we don't have an intention to implement anything like this here. If you are looking for a RAG tool which supports PDF checkout some of the [MLX community projects](https://github.com/ml-explore/mlx/discussions/654). E.g. https://github.com/qnguyen3/chat-with-mlx
