### ISSUE TITLE
Whisper: word-level time-stamps

### ISSUE THREAD

**Issue by caseybasichis** [ml-explore/mlx-examples#146]
Would it be possible to add and option for word-level timestamps to the Whisper example?

**Comment by awni** [comment]
It's possible but a bit involved. If someone wants to add it in that would be awesome. See how the [original whisper](https://github.com/openai/whisper/blob/main/whisper/transcribe.py#L90-L92) does it as a good place to start

**Comment by AndyZhangDavis** [comment]
Would be a nice feature to have, some other project that uses whisper like whisper_streaming needs word-level timestamps to work.

**Comment by awni** [comment]
Fixed in #201 !
