### ISSUE TITLE
Can't seem to be able to use the Phi2 model

### ISSUE THREAD

**Issue by jbHouse93** [ml-explore/mlx-examples#156]
When i try the method in the example i get this error: "This modeling file requires the following packages that were not found in your environment: einops. Run `pip install einops` " even though i have einops already installed. I also tried using the huggingface community method and i have this error "Fast download using 'hf_transfer' is enabled (HF_HUB_ENABLE_HF_TRANSFER=1) but 'hf_transfer' package is not available in your environment. Try `pip install hf_transfer`" even though i also have hf_transfer already installed.

**Comment by awni** [comment]
Was this during the conversion process or when running the model?

It sounds like your environment might be a little wonky.. perhaps your `pip` and `python` are not pointing to the same place.

Maybe try the following install instead

```
python -m pip install -r requirements.txt
```

And verify:

```
python -c "import einops; print(einops.__version__)"
```

**Comment by jbHouse93** [comment]
hi. it was during the conversion process. Hmm the first code tells me i dont have a module named pip and the second no module named einops

**Comment by jbHouse93** [comment]
thanks it's working. that's why i hate using the terminal

**Comment by awni** [comment]
Did you convert the model first? Is there actually a file `phi-2/weights.npz` from where you are running `phi2.py`?

**Comment by jbHouse93** [comment]
yes there's a file weights.npz

**Comment by awni** [comment]
You can specify the path to the directory with the weights `--model-path`. Make sure you are providing the right path. If that doesn't fix your issue, I would try regenerating the weights. Let me know if you are still having any issues after that and I can reopen this.
