### ISSUE TITLE
Mistral Lora example

### ISSUE THREAD

**Issue by zakkor** [ml-explore/mlx-examples#16]
Would be nice to get a Mistral 7B Lora example, similar to the Llama Lora one. Thanks!

**Comment by awni** [comment]
We will get this done ASAP.

**Comment by awni** [comment]
Mistral is now supporting in the LoRA fine tuning example: https://github.com/ml-explore/mlx-examples/pull/53

https://github.com/ml-explore/mlx-examples/tree/main/lora
