### ISSUE TITLE
MLX LLM questions (speed, training quant models, server)

### ISSUE THREAD

**Issue by RonanKMcGovern** [ml-explore/mlx-examples#181]
I'm new to MLX and have some questions after reviewing the repo and testing some models:

1. I've run Mistral on Llama cpp and also on MLX - both in 4 bit.  I'm using an M1 with 8 GB of RAM. Inference is at least 10x slower on MLX. Is this expected?
1. What fundamentally, is the key difference between MLX and llama.cpp ? Is it down to better memory usage (across memory types) with MLX?
1. How - at a high level - does inference of a quantized model work? Are the quantized weights dequantized? If so, is that dequantization fused with multiplication in a kernel?
1. What would it take to allow quantized models to be fine-tuned?
1. Are there plans to allow for a server (so weights are pre-loaded)? [Related - is there a roadmap here on github, I didn't see it immediately in the repo]

**Comment by awni** [comment]
> I've run Mistral on Llama cpp and also on MLX - both in 4 bit. I'm using an M1 with 8 GB of RAM. Inference is at least 10x slower on MLX. Is this expected?

No. This could be an issue with memory use / swapping. Could you share tokens per second you are seeing with each if you have them handy?

> What fundamentally, is the key difference between MLX and llama.cpp ? Is it down to better memory usage (across memory types) with MLX?

There's too many differences to answer this in a concise way. Suffice it to say MLX is a much more general framework for Apple silicon.

> How - at a high level - does inference of a quantized model work? Are the quantized weights dequantized? If so, is that dequantization fused with multiplication in a kernel?

Yes eexactly.

> What would it take to allow quantized models to be fine-tuned?

QLoRA which we will have an example for soon (1-2 weeks). We are just missing support for transposed quantized_matmuul at the moment.

> Are there plans to allow for a server (so weights are pre-loaded)? [Related - is there a roadmap here on github, I didn't see it immediately in the repo]

That's somewhat out of the scope of mlx and mlx-examples. But would love to see a contribution along those lines from the community. Gradio could be a great place to start.

As for a roadmap, nothing published yet but it's a good idea.

**Comment by justinh-rahb** [comment]
> > Are there plans to allow for a server (so weights are pre-loaded)? [Related - is there a roadmap here on github, I didn't see it immediately in the repo]
> 
> That's somewhat out of the scope of mlx and mlx-examples. But would love to see a contribution along those lines from the community. Gradio could be a great place to start.

I've adapted the Stable Diffusion demo into a working Gradio interface, but didn't think it worth contributing until I could make it use the existing stable_diffusion.py as-is instead of modifiying it.

[/stable_diffusion/app.py](github.com/RAHB-REALTORS-Association/mlx-demos/blob/main/stable_diffusion/app.py)

**Comment by awni** [comment]
Great this is super helpful! That run time is unexpected and much too slow.

Is this the Llama 2 model you tested: https://huggingface.co/mlx-community/Llama-2-7b-chat-4-bit ? Just want to make sure I'm using the same steps to try and reproduce it.

**Comment by RonanKMcGovern** [comment]
> Is this the Llama 2 model you tested: https://huggingface.co/mlx-community/Llama-2-7b-chat-4-bit ? Just want to make sure I'm using the same configuration to try and reproduce it.

Yes, exactly that model

**Comment by awni** [comment]
@RonanKMcGovern I'm not able to reproduce this on an M2 with 8GB. I'm seeing tokens per second around 100x faster than you! (2.873s)

Some questions:
1. Have you modified the example at all? 
2. Are you using the latest version of mlx and mlx-examples? If not could you try updating?
3. OS version?

I will see if I can try an M1 vs an M2 as it's possible that could be the difference...though it seems unlikely..

**Comment by RonanKMcGovern** [comment]
> 3\. OS version?

Updating from Ventura to Sonoma made a huge difference:
```
python llama.py --prompt "Building a website can be done in 10 simple steps:" --max-tokens 128
[INFO] Loading model from disk.
Press enter to start generation
------
Building a website can be done in 10 simple steps:


1. Define your website's purpose: What is the main reason for creating a website? What do you want to achieve with it?
2. Choose a domain name: Your domain name is the address of your website. It should be easy to remember and relevant to your business.
3. Select a web hosting provider: Your web hosting provider will store your website's files and make them accessible to visitors. Choose a provider that offers reliable uptime, good customer support, and enough storage and bandwidth for your needs.
4. Plan your website's structure: Think about the main sections
------
[INFO] Prompt processing: 1.850 s
[INFO] Full generation: 15.962 s
```

Running now at about 8 toks, so a lot closer to llama cpp.

Thanks for the assistance.

**Comment by awni** [comment]
> Updating from Ventura to Sonoma made a huge difference:

That's so interesting! Thanks for sharing.

**Comment by LeonEricsson** [comment]
crazy that the OS made such a difference, perhaps this needs to be highlighted somewhere as a potential pitfall.

**Comment by x4080** [comment]
@RonanKMcGovern did you tried prompt with large tokens ? I found that using phi 4bit and long context memory usage is very high (create swapping) - I'm using m2pro 16gb
