### ISSUE TITLE
lora with more than one key-value pair

### ISSUE THREAD

**Issue by deboradum** [ml-explore/mlx-examples#188]
Currently, when finetuning with the lora example, only the key 'text' is recognized an the rest is ignored. I am finetuning a model for which I would like to also provide some context for the model to also take as input. Is there any plans to implement this by modifying the code a bit?

**Comment by awni** [comment]
We could add this but it isn't a huge priority at the moment for a couple reasons:

1. It's not clear it matters that much to not take loss from the context. (But I'd be interested to hear if you notice a big difference there).
2.  There is a balance between keeping the example simple (and useful for instruction) and fully featured and I think it's at a good place there right now.

I encourage you to extend it to support for that feature in your own fork. And if you think it makes sense to contribute back to here then we're happy to take a look at it!
