### ISSUE TITLE
How to convert CogVLM to mlx

### ISSUE THREAD

**Issue by ageorgios** [ml-explore/mlx-examples#194]
Where to start to try to convert CogVLM to mlx and quantize it ?
The goal is to run the model on MacOS quantized.
Bitsandbytes is not supported on Apple Sillicon, so I think MLX is the alternative.

https://github.com/THUDM/CogVLM

**Comment by awni** [comment]
That would be awesome to see in MLX!!

A great starting point is to take a look at one of our LLM example repos

For example [Mistral](https://github.com/ml-explore/mlx-examples/tree/main/llms/mistral) shows how to do model conversion and quantization for a Transformer LM. 

I usually start with a reliable reference implementation, then:
1. Translate the model to MLX. 
2. Include any additional code to generate inputs / process outputs.
3. Test to make sure it's working as expected
4. Add quantization at this point which is just a few lines in terms of implementation

**Comment by awni** [comment]
Let me know if you have more specific questions as you get going in the conversion process.
