### ISSUE TITLE
Unable to reproduce Mistral quantization

### ISSUE THREAD

**Issue by alvarobartt** [ml-explore/mlx-examples#196]
Hi to whoever is reading this 🤗

## Description

I'm having a hard time trying to reproduce and obtain https://huggingface.co/mlx-community/Mistral-7B-Instruct-v0.2-4-bit using the recently included quantization support in `mlx` 0.6.0 via the `convert.py` file at https://github.com/ml-explore/mlx-examples/blob/main/llms/mistral/convert.py#L27

The model is apparently quantized, but then the generation is completely messed up, and when comparing it to the one I get when running https://huggingface.co/mlx-community/Mistral-7B-Instruct-v0.2-4-bit instead, I see that mine is super off while the existing one is fairly decent.

Is there something that may be missing from the `convert.py` script? Maybe something that was kept internally and lost during the `convert.py` update? Thanks in advance!

cc @awni

**Comment by alvarobartt** [comment]
For more context, I tried to quantize Zephyr following the same recipe as the rest of the Mistral-based models, but even though the model looks fine, the weights are apparently not right, that's why I made this private temporarily https://huggingface.co/mlx-community/zephyr-7b-beta-4bit

**Comment by awni** [comment]
Can you point me to the Mistral model you are trying to convert + quantize? I can check it on my end.

**Comment by alvarobartt** [comment]
Hey sure, it's indeed https://huggingface.co/mistralai/Mistral-7B-Instruct-v0.2

**Comment by awni** [comment]
So just to be clear. You did the following:
1. Download that HF model
2. Run `python conver.py -q` pointing to that model
3. Test the converted model and get bogus results?

**Comment by awni** [comment]
Actually, I'm not sure, how did you convert it. It doesn't look like the `mistral/convert.py` can convert that format of model.

**Comment by alvarobartt** [comment]
Yes, indeed I'm just changing the `torch.load` line with `AutoModelForCausalLM.from_pretrained(...)` and `state = model.state_dict()`, then converting the weights to `mx.float16` and finally quantizing it using the `nn.QuantizedLinear.quantize_module(...)` function.

**Comment by alvarobartt** [comment]
Would dumping the weights in a single file as `consolidated.00.pth` and the loading it via `torch.load` solve that? Shouldn't the state dict be preserved when loading the weights via `AutoModel` from `transformers`?

**Comment by awni** [comment]
I think using AutoModel as you did should work, but I have to double check. The HF version might have a different format than the original Mistral version which would require some key mappings.

**Comment by alvarobartt** [comment]
Oh fair, then I'll look into that, I just assumed it was not required, since when I tried to get the MLX compatible weights for `zephyr-7b-beta` I had success with the default conversion script with no need to remapping any key, but I'll double check and come back with a response if I manage to solve that! Thanks

**Comment by awni** [comment]
Yes, the keys in the state dictionary definitely need to be remapped from that HF repo.  I think the [TinyLlama](https://github.com/ml-explore/mlx-examples/blob/main/llms/llama/convert.py#L59) example is a good one to look at for how that goes.

Honestly I'm not sure how the original mistral instruct v2 was converted to work correctly :) I think someone must have put together a quick script for it.

**Comment by alvarobartt** [comment]
I've already made it work fine, some keys were not matching, but I've doubled checked and now those work. And fair, I'm also using a custom script based on the `convert.py` files, thanks again!

**Comment by awni** [comment]
Awesome can't wait to see the 4-bit Zephyr model!!

**Comment by alvarobartt** [comment]
Already on the Hub https://huggingface.co/mlx-community/zephyr-7b-beta-4bit 👏🏻 I'll post about these quantized models later today / tomorrow!
