### ISSUE TITLE
llama confusion

### ISSUE THREAD

**Issue by nikolaydubina** [ml-explore/mlx-examples#20]
1.

https://github.com/facebookresearch/llama

fetches weights for 13B and 70B weights in multiple files, but by mlx-example/llama expects single file path for weights (not directory). does this mean only 7B supported?

2.

mlx-example/llama can not convert weights from llama2

```bash
nikolaydubina@Macintosh llama % python3 convert.py ../../llama/llama-2-7b-chat/consolidated.00.pth mlx_llama_weights.npz
Traceback (most recent call last):
  File "/Users/nikolaydubina/Workspace/mlx-examples/llama/convert.py", line 47, in <module>
    **{k: v for k, v in starmap(map_torch_to_mlx, state.items()) if k is not None}
      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/nikolaydubina/Workspace/mlx-examples/llama/convert.py", line 47, in <dictcomp>
    **{k: v for k, v in starmap(map_torch_to_mlx, state.items()) if k is not None}
      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/nikolaydubina/Workspace/mlx-examples/llama/convert.py", line 35, in map_torch_to_mlx
    return key, value.numpy()
                ^^^^^^^^^^^^^
TypeError: Got unsupported ScalarType BFloat16
```

**Comment by angeloskath** [comment]
The example has been tested with Llama v1 7B but the fixes to the weight converter should be fairly easy to do.

For the above error, changing `value.numpy()` to `value.float().half().numpy()` would work but it would set the weight to `float16`. The reason is that numpy doesn't support `bfloat16`.

**Comment by awni** [comment]
1. The BF16 issue is fixed in main.
2. Converting sharded models is not supported yet, but we should add that. Marking this as duplicate with https://github.com/ml-explore/mlx-examples/issues/35 which we can use for this feature.
