### ISSUE TITLE
Making embed and norm layers trainable in mlx

### ISSUE THREAD

**Issue by RonanKMcGovern** [ml-explore/mlx-examples#209]
It's great we can train with LoRA but training embed and norm are important for chat fine-tuning and context extension.

If it's not possible to select and make these layers trainable, users have to do a full fine-tune, which requires a lot more RAM.

**Comment by awni** [comment]
You want to use the Lora example and also be able to tune the normalization and embedding parameters?

it’s a bit outside the scope of that example but it should be quite doable using the LoRA example as a starting point. Basically you just need to unfreeze the layers you want to optimize. 

We [freeze](https://github.com/ml-explore/mlx-examples/blob/main/lora/lora.py#L361) the model after we load it. You can unfreeze the layers you want to tune right after that. So `model.output.unfreeze()` to train the output embeddings!
