### ISSUE TITLE
stable diffusion malloc error

### ISSUE THREAD

**Issue by davidjoffe** [ml-explore/mlx-examples#21]
mlx seemed to install fine but I tried the stable diffusion example and keep getting this:

134217728 bytes seems small, there should not be a problem allocating only ~134MB memory, the machine has 8GB RAM & ~4GB free. It's an Apple M2 Mac mini (running headless & connected to via VNC, could that cause issues?),
Or am I misunderstanding something basic, does this need an M2 Pro or something? Though it does go through all the (default) 50 steps before failing

I ran the MLX unit tests and they seemed to run fine, said '154 tests ran, 4 skipped'

```
(foo) david@Davids-Mac-mini stable_diffusion % python txt2image.py "A photo of an astronaut riding a horse on Mars." --n_images 1 --n_rows 1
/Users/david/mlx/foo/lib/python3.9/site-packages/urllib3/__init__.py:34: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(
100%|
 [00:00<?, ?it/s]libc++abi: terminating due to uncaught exception of type std::runtime_error: [malloc_or_wait] Unable to allocate 134217728 bytes.
zsh: abort      python txt2image.py "A photo of an astronaut riding a horse on Mars."  1  1
(foo) david@Davids-Mac-mini stable_diffusion % /Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/multiprocessing/resource_tracker.py:216: UserWarning: resource_tracker: There appear to be 1 leaked semaphore objects to clean up at shutdown
  warnings.warn('resource_tracker: There appear to be %d '
```

python --version 3.9.6. OS: Ventura 13.6.1. tried Python 3.11.5 and does same
It cuts off at "There appears to be %d '

Briefly tried installing via source & also tried on conda, and Python 3.12, also didn't work

**Comment by davidjoffe** [comment]
Add --cfg 0 unfortunately makes no difference

Even if it's running out of memory, why wouldn't it just use the system pagefile/swap for such a small amount like ~134MB? In 20+ years of dev I've never seen malloc() fail from high memory load, it normally just allocs and uses swap ... these 8GB Macs regularly swap like crazy but continue, I often use much MUCH more on these Macs than this appears to be using from Activity Monitor

Or does this have something to do with the unified memory architecture? Or memory fragmentation?

It seems to have no problem running through the default 50 steps - it just fails at the end. I'm watching memory load as this runs and it's in the green most the way, using max 2GB of swap until it completes the 50 steps ... using only 2GB swap it doesn't seem to me like such an excessive memory load that a malloc of just 134MB should fail:

```
(foo) (base) david@Davids-Mac-mini stable_diffusion % python3 txt2image.py "A cat on a sandwich" --cfg 0 --n_images 1 --n_rows 1
/Users/david/mlx/foo/lib/python3.9/site-packages/urllib3/__init__.py:34: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(
100%|█████████████████████████████████████████████████████████████████████████████████████████████████| 50/50 [02:37<00:00,  3.14s/it]
  0%|                                                                                                           | 0/1 [00:00<?, ?it/s]libc++abi: terminating due to uncaught exception of type std::runtime_error: [malloc_or_wait] Unable to allocate 134217728 bytes.
zsh: abort      python3 txt2image.py "A cat on a sandwich" --cfg 0 --n_images 1 --n_rows 1

```

(foo) (base) david@Davids-Mac-mini stable_diffusion % python3 txtimage.py "A cat on a sandwich" --cfg 0 --n_images 1 --n_rows 1
/Users/david/mlx/foo/lib/python3.9/site-packages/urllib3/__init__.py:34: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(
100%|█████████████████████████████████████████████████████████████████████████████████████████████████| 50/50 [02:37<00:00,  3.14s/it]
  0%|                                                                                                           | 0/1 [00:00<?, ?it/s]libc++abi: terminating due to uncaught exception of type std::runtime_error: [malloc_or_wait] Unable to allocate 134217728 bytes.
zsh: abort      python3 txt2image.py "A cat on a sandwich" --cfg 0 --n_images 1 --n_rows 1
(foo) (base) david@Davids-Mac-mini stable_diffusion %  /Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/multiprocessing/resource_tracker.py:216

**Comment by davidjoffe** [comment]
I did some more tests, ran it again with --steps 2 - the maximum memory load system hits is about 7.5GB and the entire system is using ONLY ~500MB swap this time. I really don't see why a malloc of just ~134MB should fail under those conditions, why it shouldn't just use swap

**Comment by davidjoffe** [comment]
New information: I forked mlx itself, changed one line of code, rebuilt from my source fork, and now it works 😊

This line of code in mlx/backend/metal I changed to a much higher limit - this 1.5 seems a bit conservative:

`block_limit_(1.5 * device_->recommendedMaxWorkingSetSize()) {}'
`

There is indeed a relatively big spike of memory usage as it finishes the steps, but not world-ending, I'd rather have 'something that works' even if it spikes my swap, but I suppose it's debatable how best to handle that in the long run as a general solution for all users.

**Comment by angeloskath** [comment]
May I say, awesome work :-)

We need to start adding more 8GB Macs in our testing pool. There really wasn't a particular reason for the 1.5. It just gets significantly slower at that point and we wanted to avoid freezing the system.

I would encourage you to at least open an issue or maybe a PR at the main repo. Can't tell you that it will be the first one merged but for sure we 'll test the implications of increasing this limit and if there are none for most use cases then merge it.

Thanks for investigating! Feel free to close the issue and link to it from the PR.

**Comment by davidjoffe** [comment]
Thank you! 

I opened an issue for this on mlx: https://github.com/ml-explore/mlx/issues/63 and created this Pull Request: https://github.com/ml-explore/mlx/pull/64 - hope it's accepted, though of course it's up to the mlx maintainers.
