### ISSUE TITLE
Can we make hf_llm as a Python package?

### ISSUE THREAD

**Issue by mzbac** [ml-explore/mlx-examples#220]
First of all, thank you for making it available to us. I would love to use it for my project, but currently I have to manually copy the source code and put it in the project. I'm wondering if it's possible to make it a Python package so that people can simply import and use it.

**Comment by awni** [comment]
I'm definitely on board with that. I'm not sure exactly where we would put it (presumably a PyPi dist would be useful?). Will give it some thought.

**Comment by Vaibhavs10** [comment]
I 100% second this and am also happy to help with this ofc!
A new PyPI package would probably be for the best.
