### ISSUE TITLE
Performance Issue with Mistral-7B-v0.1 Model on M1 Pro with 16 GB RAM

### ISSUE THREAD

**Issue by ajamous** [ml-explore/mlx-examples#223]
Hello,

I am encountering a significant performance issue when running the Mistral-7B-v0.1 model on my M1 Pro with 16 GB of RAM. The command I'm using is as follows:

The problem I'm facing is twofold:

1. **Extremely Slow Performance:** The command runs unusually slow, which seems disproportionate to what I would expect from a system with my specifications. ``python3 generate.py --model mistralai/Mistral-7B-v0.1  --prompt "hello" --max-token 1024 --temp 0.7``
2. **Memory Exhaustion:** While running the command, I've noticed that my system runs out of memory, which suggests there might be an issue with how the model utilizes system resources.

I have considered the possibility of this being related to my specific setup. However, given the specs of my M1 Pro and the 16 GB of RAM, it seems unusual. I have not made any significant modifications to the configuration or the environment that could lead to such an issue.

Could this be a known issue, or am I possibly missing something in my setup? Any guidance or suggestions to resolve or debug this problem would be greatly appreciated.

Thank you for your time and assistance.

Best regards,
Ameed Jamous

**Comment by awni** [comment]
This is a known issue #38. The model uses about 14GB of RAM in 16-bit precision out of the box so it doesn't take much to put your system over the threshold of swapping. 

You can quantize the model or download a quantized [version from Hugging Face](https://huggingface.co/mlx-community)
