### ISSUE TITLE
Checking for nan values in arrays

### ISSUE THREAD

**Issue by sck-at-ucy** [ml-explore/mlx-examples#230]
I have run into a situation where my code continues to run for some time while nan values start to appear in mx arrays. I want to catch this early and do exception handling. In situations like this having the equivalent of NumPy's` isnan() `, e.g. 

`if mx.any(mx.isnan(u)) `

would be very handy.  I am not sure if something is already available and missed it.

**Comment by angeloskath** [comment]
It isn't but you can emulate it with `x != x`. So basically, `if mx.any(x != x): print("You've got nans")`.

Keep in mind that this will also cause an evaluation of the graph up to that point but for debugging it should be fine and you could always check it like `if check_for_nans and mx.any(x != x):` which will only eval `x` if `check_for_nans` is `True`.

**Comment by sck-at-ucy** [comment]
Thank you Angelos, this is a neat workaround. 

I am issuing `mx.eval(x)` every N steps anyway, so I could use this in place of the direct evaluation of the graph to accomplish both at the same call.

**Comment by awni** [comment]
I'm closing this in favor of the issue I just opened in mlx core: https://github.com/ml-explore/mlx/issues/404
