### ISSUE TITLE
LoRA finetuning with model downloaded from mlx-community fails

### ISSUE THREAD

**Issue by shreyaskarnik** [ml-explore/mlx-examples#232]
I downloaded pre-converted model from mlx-community from HuggingFace using the command 
```bash 
huggingface-cli download --local-dir-use-symlinks False --local-dir tinyllama-1.1B-Chat-v0.6 mlx-community/tinyllama-1.1B-Chat-v0.6
``` 
and tried to run 
```bash
python lora.py --model ./tinyllama-1.1B-Chat-v0.6 \
               --train \
               --iters 600
```
and got this error 
```python
Loading pretrained model
Traceback (most recent call last):
  File "/PATH/mlx-examples/lora/lora.py", line 360, in <module>
    model, tokenizer = load_model(args.model)
                       ^^^^^^^^^^^^^^^^^^^^^^
  File "/PATH/mlx-examples/lora/lora.py", line 339, in load_model
    model_args = ModelArgs(**config)
                 ^^^^^^^^^^^^^^^^^^^
TypeError: ModelArgs.__init__() got an unexpected keyword argument 'rope_traditional'
```

Is there a way to add support for fine-tuning the models from mlx-community?

**Comment by singhaki** [comment]
For this issue you can remove this param from config file. 'rope_traditional' = False for tinyllama and you might also find issue with head_dim. You can check code how it's calculated from convert script. it's config["dim"] // n_heads.

**Comment by awni** [comment]
Thanks @singhaki for the input.

Regarding the rope_traditional flag, I wouldn't remove it as the model won't work as well. We can add the config param to our model so that it interprets it correctly, that's an easy fix.

The other config options you can add to the json as needed to make sure they are there. I am planning to move the LoRA example to be more like our HF LLM example to simplify model conversions etc. Should solve this problem in a cleaner way.

**Comment by singhaki** [comment]
I removed it from config and added it in code. I tried like 1 week back before hf integration.

**Comment by shreyaskarnik** [comment]
Thanks for the responses @singhaki and @awni really appreciate it

**Comment by shreyaskarnik** [comment]
I was able to work around and get a model loaded from mlx-community for fine-tuning here is the modified `models.py` which I used https://gist.github.com/shreyaskarnik/dbe75ebba5d4819419f9ea2526650ba0

**Comment by mzbac** [comment]
I quickly modified the Lora and HF_Llama examples, and created a sample repository to do Lora/QLora on the new HF_Llama format models from MLX-Community.  @awni Do you think we could update the LoRa example to include that? I am more than happy to contribute back to the MLX examples.
https://github.com/mzbac/mlx-lora

**Comment by awni** [comment]
This will be updated in #252
