### ISSUE TITLE
peft lora example?

### ISSUE THREAD

**Issue by mzbac** [ml-explore/mlx-examples#239]
Thanks for providing a good example of how to use LoRa via MLX. While reading through the LoRa example, correct me if I'm wrong, but my understanding is that in the current LoRa example we are using rslora. I was just wondering if it's possible for us to provide a peft LoRa (lora alpha, dropout, lora rank) example as well.  and, do we have any plans to generalize the LoRa example into a Python package so that people can simply import it and fine-tune it?

**Comment by awni** [comment]
Certainly open to including a few more features to make it work better depending on how useful they are.

As for making it into a package. I think we'll aim to start by packaging hf_llm. Then it might make sense to simply bundle LoRA with that if it's useful for people.

**Comment by mzbac** [comment]
I haven't tried rslora before in the past, but I have had some good results using lora config with different lora alpha, dropout, and lora rank. I will give rslora a try to see if I can reproduce the performance. Definitely would love to support rslora if it has better performance.

**Comment by lopuhin** [comment]
@mzbac could you please explain what kind of LoRA did you expect to see? As I understand the rank and scaling factor are specified here https://github.com/ml-explore/mlx-examples/blob/b152d12d7bccd3fa6e8072c73dd98775a4e8d2aa/lora/models.py#L25 and here https://github.com/ml-explore/mlx-examples/blob/b152d12d7bccd3fa6e8072c73dd98775a4e8d2aa/lora/models.py#L58 and from reading the abstract of rslora it seems that it's about choosing the scaling factor (which is not implemented here I think). So while these parameters are not exposed in the command line options, we can still tweak them, so I'd be curious to learn what kind of modification are you looking for?

**Comment by mzbac** [comment]
@lopuhin Sorry, I misunderstood the example. I only saw that we passed the rank parameter and used sqrt in the initialization, so I thought it was using rslora. Thanks for clarifying this, I appreciate it. I will close this issue. Sorry for creating the noise.

**Comment by lopuhin** [comment]
No worries, I'm myself experimenting with this great lib and was curious 😄
