### ISSUE TITLE
[Feature] Add Metal support for FFT

### ISSUE THREAD

**Issue by sck-at-ucy** [ml-explore/mlx-examples#249]
I am trying to implement a spectral Poisson pressure solver in 2D using mx.fft and I am having a hard time. My first attempt was to avoid mixing NumPy and MLX, but I found that the function was getting convoluted trying to emulate the `np.meshgrid()`  functionality. So, I ended up mixing the two. However, the error I am getting seems to be unrelated to using NumPy and to be suggesting  that some functionality is not yet implemented in Metal backend. Do I need to compile from source to be able to use mx.fft ? 

```
def poisson_solver_fft(dx, dy, b):
    # Transform 'b' to frequency space using 2D real FFT
    b_hat = mx.fft.rfft2(b)

    # Precompute constants for frequency space solution
    ny, nx = b.shape
    nx_rfft = nx//2 + 1  # Adjusted size for the real FFT output
    kx = np.linspace(0, nx_rfft - 1, nx_rfft) * (2 * np.pi / (nx * dx))
    ky = np.linspace(0, ny - 1, ny) * (2 * np.pi / (ny * dy))

    # Create the frequency grid using NumPy's meshgrid
    kx_grid, ky_grid = np.meshgrid(kx, ky, indexing='ij')

    # Convert the frequency grids to MLX arrays
    kx_grid_mx = mx.array(kx_grid)
    ky_grid_mx = mx.array(ky_grid)

    # Transpose the grids to match the shape of b_hat
    kx_grid_mx = mx.reshape(kx_grid_mx, (nx_rfft, ny)).T
    ky_grid_mx = mx.reshape(ky_grid_mx, (nx_rfft, ny)).T

    # Compute the wave number squared, avoiding division by zero at the zero frequency
    k_squared_mx = kx_grid_mx**2 + ky_grid_mx**2
    k_squared_mx = mx.where(k_squared_mx == 0, 1, k_squared_mx)

    # Compute the solution in frequency space
    p_hat = b_hat / (-k_squared_mx)

    # Inverse real FFT to get back to physical space
    p = mx.fft.irfft2(p_hat, s=[ny, nx])  # Specify the size of the real output array

    # Zero out the mean pressure difference if necessary (adjust as per your boundary conditions)
    p -= mx.mean(p)

    return p
```

Here is the runtime error: 

            
```
libc++abi: terminating due to uncaught exception of type std::runtime_error: [FFT] NYI for Metal backend.
zsh: abort      streamlit run ./Lid_Driven_Cavity_Flow_RK2_v3.py
(base) 20:59:45 ~/PycharmProjects/pythonProject_StreamLit/MLX-Physics-master $> 
```

**Comment by awni** [comment]
No we actually do not have an FFT in Metal yet :\

A possible workaround until we add it is `b_hat = mx.fft.rfft2(b, stsream=mx.cpu)` (and in the `irfft2` as well).

**Comment by sck-at-ucy** [comment]
Ok, great thank you for the quick response 🙂

  I will use the cpu workaround, just to get a placeholder function ready in my code. 

BTW, for physics-based problems having a native support for `mx.fft.fftshift()` and `kx, ky = mx.meshgrid(kx, ky) ` would be very nice.

**Comment by awni** [comment]
This issue should really be in MLX core..closing here and moving it.
