### ISSUE TITLE
Slow mnist in M1

### ISSUE THREAD

**Issue by iseong83** [ml-explore/mlx-examples#26]
I am using Apple M1 Pro and ran main.py in Python 3.11. When I used the option `--gpu`, it's slower than cpu. Is this expected?

<img width="737" alt="image" src="https://github.com/ml-explore/mlx-examples/assets/44355378/52fcf247-e44b-4799-bb19-8e580c373d38">

**Comment by angeloskath** [comment]
Yes that is expected. There isn't a lot of work to be done so latency is more important than throughput and the CPU fares better.
