### ISSUE TITLE
convert model with quantization

### ISSUE THREAD

**Issue by iwasnothing** [ml-explore/mlx-examples#261]
the convert.py under lora/ does not have the quantization option.

lora % python convert.py -h
usage: convert.py [-h] [--torch-model TORCH_MODEL] [--mlx-model MLX_MODEL]

Convert Mistral or Llama models to MLX.

options:
  -h, --help            show this help message and exit
  --torch-model TORCH_MODEL
                        The torch model directory
  --mlx-model MLX_MODEL
                        The directory to store the mlx model

**Comment by awni** [comment]
It's definitely [there](https://github.com/ml-explore/mlx-examples/blob/main/lora/convert.py#L59-L64). I would pull the repo if you haven't updated it in a while.
