### ISSUE TITLE
Serious errors in BERT implementation

### ISSUE THREAD

**Issue by andersonbcdefg** [ml-explore/mlx-examples#262]
When working with the BERT implementation, I noticed some serious problems, most obvious is that the Pooler goes from intermediate_size -> vocab_size, when it should go from intermediate_size -> intermediate size. (It's also weird that the model dim is called intermediate_size because that's usually reserved for the inner dimension of an MLP, but let's ignore that for now). Even when I corrected this, I'm still getting outputs from the BERT model that are not numerically similar to the same weights run in PyTorch, so I'm concerned there are more subtle errors I'm not catching as well.

**Comment by awni** [comment]
Thanks for flagging. This should fix your issues: #269 

The pooling layer is the only actual bug I could find. I added a tests that compares the HF model to the MLX model and they match to a very reasonable numerical tolerance.

**Comment by andersonbcdefg** [comment]
awesome thanks :) check out my embeddings PR based on the MLX BERT when you get a chance :D
