### ISSUE TITLE
Generate till EOS token rather than till num-tokens / max-tokens

### ISSUE THREAD

**Issue by Ghatage** [ml-explore/mlx-examples#273]
While working on the lora finetune of the mistral model, I was wondering if any of the examples support generating till EOS token.
It seems all examples either generate till `max-tokens` / `num-tokens`.

I tried to change the lora.py for mistral to generate only till EOS by changing the generate function to this:
```
def generate(prompt: mx.array, model: Mistral, tokenizer: Tokenizer, temp: Optional[float] = 0.0):
    def sample(logits):
        if temp == 0:
            return mx.argmax(logits, axis=-1)
        else:
            return mx.random.categorical(logits * (1 / temp))

    logits, cache = model(prompt[None])
    y = sample(logits[:, -1, :])
    yield y

    eos_id = tokenizer.eos_id
    while True:
        logits, cache = model(y[:, None], cache)
        y = sample(logits.squeeze(1))
        token_id = y.item()
        yield token_id
        if token_id == eos_id:
            break
```

But this doesn't seem to work. Any comments / pointers?

**Comment by awni** [comment]
Lora already [does that](https://github.com/ml-explore/mlx-examples/blob/main/lora/lora.py#L275-L276). It will go until either the `eos` or until `max_tokens`, whichever comes first. So you can make `max_tokens` pretty large to make it more likely that it will hit and `eos`

Closing this, but let me know if you have any more questions about that.
