### ISSUE TITLE
whisper: No such file or directory: 'mlx_models/config.json'

### ISSUE THREAD

**Issue by sivanola** [ml-explore/mlx-examples#277]
I'm trying to run whisper, but I'm getting No such file or directory: 'mlx_models/config.json' I converted pytorch large model, the conversion creates this structure: mlx_models/large/config.json So, when I try to do whisper.transcribe(speech_file, model="large"), it doesn't recognize the folder and looks for config.json in mlx_models instead of in mlx_models/large/...

**Comment by awni** [comment]
Maybe you are using an outdated whisper? The `transcribe` function takes an `path_or_hf_repo` as the second argument which you should set to `mlx_models/large` if that's where you stored the model.

**Comment by awni** [comment]
I think the README for this example needs a little work, I will update it.

**Comment by awni** [comment]
For future reference `help(whisper.transcribe)` will tell you about the arguments it can accept 😄
