### ISSUE TITLE
lora  TypeError

### ISSUE THREAD

**Issue by coderabbit214** [ml-explore/mlx-examples#280]
python lora.py --model mistralai/Mistral-7B-v0.1 \
               --adapter-file adapters.npz \
               --prompt "table: 1-10015132-16 
columns: Player, No., Nationality, Position, Years in Toronto, School/Club Team
Q: What is terrence ross' nationality
A: "

    logits, cache = model(y[None], cache=cache)
                          ~^^^^^^
TypeError: list indices must be integers or slices, not NoneType

**Comment by awni** [comment]
Sorry, fix in #282!
