### ISSUE TITLE
Fine-tune lora errors with invoked with: array?

### ISSUE THREAD

**Issue by SOSONAGI** [ml-explore/mlx-examples#289]
Hi,

I've setup everything well with the requirements for lora fine-tune.

mlx==0.0.7
and others also installed well.

I've used the well converted model with quantized but, after i put

```CLI
python lora.py --model ./mlx_model --train --iters 600
```

and got an errors below

```CLI
Traceback (most recent call last):
  File "/Users/soonde17/anaconda3/envs/mlx/mlx_0.0.7/mlx-examples/lora/lora.py", line 324, in <module>
    train(model, train_set, valid_set, opt, loss, tokenizer, args)
  File "/Users/soonde17/anaconda3/envs/mlx/mlx_0.0.7/mlx-examples/lora/lora.py", line 222, in train
    for it, batch in zip(
  File "/Users/soonde17/anaconda3/envs/mlx/mlx_0.0.7/mlx-examples/lora/lora.py", line 191, in iterate_batches
    batch_arr[j, : lengths[j]] = batch[j]
TypeError: __array__(): incompatible function arguments. The following argument types are supported:
    1. (self: mlx.core.array) -> numpy.ndarray

Invoked with: array([1, 2401, 28747, ..., 266, 28742, 2], dtype=int64), dtype('int32')
```

after i've got above errors, i've tried models that mlx team uploaded on hf but, got a same error messages like above.

model is the mlx-community/Mistral-7B-Instruct-v0.2 btw.

Please let me know how should i fix that.

Thank you.

**Comment by mzbac** [comment]
Looks like a bug from the old example,  would you please pull the latest main branch. It should fix the issue
