### ISSUE TITLE
ERROR: No matching distribution found for mlx - Wheels missing for Python 3.12.x

### ISSUE THREAD

**Issue by sammcj** [ml-explore/mlx-examples#29]
Following the instructions from mistral/readme.md pip fails to find a package called mlx:

```
(mlx)samm@samm-mbp:~/git/mlx-examples/mistral@main pip install -r requirements.txt                                             <region:ap-southeast-2>
ERROR: Could not find a version that satisfies the requirement mlx (from versions: none)
ERROR: No matching distribution found for mlx
```

- Python 3.12.0
- Conda 23.11.0
- macOS 14.1.2

*edit: It looks like the [wheels](https://pypi.org/project/mlx/0.0.3/#files) are missing for 3.12.x

**Comment by awni** [comment]
This will be fixed in the next release today, hang tight! In the meantime you can do a conda env with 3.11.

https://github.com/ml-explore/mlx/pull/47
