### ISSUE TITLE
error in transformer_lm example

### ISSUE THREAD

**Issue by bkvogel** [ml-explore/mlx-examples#3]
I tried to run the transformer LM example in `mlx-examples/transformer_lm/main.py` as follows:
```
python main.py --gpu
```
which produced the output:
```
Training a transformer with 153.883 M parameters
Iter 10: Train loss 9.027, It/sec 2.114
Iter 20: Train loss 8.388, It/sec 2.272
...
Iter 990: Train loss 6.922, It/sec 2.280
Iter 1000: Train loss 6.916, It/sec 2.277
Traceback (most recent call last):
  File "/Users/vogel/data/mlx-examples/transformer_lm/main.py", line 192, in <module>
    main(args)
  File "/Users/vogel/data/mlx-examples/transformer_lm/main.py", line 115, in main
    val_loss = eval_fn(params, valid)
                       ^^^^^^
NameError: name 'params' is not defined. Did you mean: 'nparams'?
```

From a quick skim of the code, I suspect `model` should be passed to `eval_fn()` instead of `params`, e.g.:
```
val_loss = eval_fn(model, valid)
```
and `eval_fn()` should be something like:
```
def eval_fn(model, dataset):
        inputs, targets = map(mx.array, to_samples(context_size, dataset))
        loss = 0
        for s in range(0, targets.shape[0], batch_size):
            bx, by = inputs[s : s + batch_size], targets[s : s + batch_size]
            bx, by = map(mx.array, (bx, by))
            losses = model.loss(bx, by, reduce=False)
            loss += mx.sum(losses).item()
        return loss / len(targets)
```

**Comment by jaglinux** [comment]
I hit the same issue yesterday"params" not defined and I had the exact patch at my end.
However the eval_fn() takes forever. (after 1000 iteration)
I printed argets.shape[0] https://github.com/ml-explore/mlx-examples/blob/main/transformer_lm/main.py#L87 which is 72736. The loss calculation in the loop takes long time.
I am running on Apple M1 chip MacBook.
@bkvogel were you able to complete the training with the fix ? Thanks.

**Comment by jaglinux** [comment]
My patch is slightly different from the proposed https://github.com/ml-explore/mlx-examples/pull/19, but it does the same thing.
https://patch-diff.githubusercontent.com/raw/jaglinux/mlx-examples/pull/1.patch

**Comment by bkvogel** [comment]
Yes, the validation loss computation takes a while but eventually completes. It takes around 1.5 hours on my machine (M1 Max). I did not try computing the test loss.
