### ISSUE TITLE
why phi2 inference get failure in mac m1 pro,  do i convert  *.safetensors in wrong way?

### ISSUE THREAD

**Issue by hwx628** [ml-explore/mlx-examples#304]
i convert phi2 model local `python convert.py --hf-path "/Users/xxx/Documents/code/model/phi2"` , then  i  get result:
`[INFO] Loading
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.`

when i inference `python generate.py --model "./mlx_model" `, i  get result belong:
Traceback (most recent call last):
  File "generate.py", line 90, in <module>
    model, tokenizer = phi2.load(args.model)
  File "/Users/xxx/Documents/code/mlx-examples/llms/phi2/phi2.py", line 218, in load
    model.load_weights(list(weights.items()))
  File "/Users/xxx/anaconda3/envs/mmlab/lib/python3.8/site-packages/mlx/nn/layers/base.py", line 146, in load_weights
    raise ValueError(f"Received parameters not in model: {extras}.")
ValueError: Received parameters not in model: model.layers.27.input_layernorm.bias model.layers.23.input_layernorm.weight model.layers.2.self_attn.dense.bias model.layers.30.mlp.fc2.bias model.layers.9.self_attn.k_proj.weight model.layers.12.self_attn.q_proj.bias model.layers.27.self_attn.q_proj.weight model.layers.2.self_attn.v_proj.weight model.layers.7.self_attn.v_proj.weight model.layers.26.mlp.fc2.weight model.layers.18.self_attn.v_proj.bias model.layers.26.self_attn.k_proj.bias model.layers.13.input_layernorm.bias model.layers.28.input_layernorm.weight model.layers.29.self_attn.k_proj.bias model.layers.7.input_layernorm.bias model.layers.9.self_attn.dense.bias model.layers.31.mlp.fc1.weight model.layers.17.mlp.fc2.weight model.layers.30.mlp.fc2.weight model.layers.29.mlp.fc2.bias model.layers.23.mlp.fc2.weight model.layers.11.input_layernorm.bias model.layers.6.input_layernorm.weight model.layers.1.mlp.fc2.bias model.layers.18.input_layernorm.weig...  ... ...

**Comment by awni** [comment]
The phi2 model was changed in the Hugging Face hub so that example is now broken.

We also removed the phi2/ from `mlx-examples/llms`. If you pull the latest examples you now use it with `hf_llm/generate` and it should work.
