### ISSUE TITLE
Error w/ Upload Name Fuse.py

### ISSUE THREAD

**Issue by USMCM1A1** [ml-explore/mlx-examples#316]
I'm able to use fuse.py to fuse my LoRA--this command works and creates a new folder with weights, tokenizer, config, etc.  E.g.:
`python fuse.py --model /Users/williammarcellino/mlx-examples/lora/mlx_model --save-path /Users/williammarcellino/mlx-examples/lora/Fused_Models --adapter-file /Users/williammarcellino/mlx-examples/lora/adapters_GrkRom_1640Iter.npz`

However when I add --upload-name, e.g.:
`python fuse.py --model /Users/williammarcellino/mlx-examples/lora/mlx_model --save-path /Users/williammarcellino/mlx-examples/lora/Fused_Models --adapter-file /Users/williammarcellino/mlx-examples/lora/adapters_GrkRom_1640Iter.npz/--upload-name mistral-7b-v0.1-GreeceRome-v0.1`
I get the error "fuse.py: error: unrecognized arguments: mistral-7b-v0.1-GreeceRome-v0.1"

I was assuming that for [--upload-name UPLOAD_NAME] you replaced UPLOAD_NAME with whatever you wanted to name the new model, but maybe that's wrong?

**Comment by awni** [comment]
I think you're just missing a space in your command e.g. `1640Iter.npz/--upload-name` should be `1640Iter.npz/ --upload-name`.
