### ISSUE TITLE
MLX Iter vs Torch Epoch

### ISSUE THREAD

**Issue by gladjoyhub** [ml-explore/mlx-examples#322]
Traditionally 3 Epochs is enough for fine-tuning in Torch. Is it equivalent to the default 600 Iters in MLX?

**Comment by awni** [comment]
Well it depends on the size of the data set and the batch size...

1 Epoch typically means 1 full pass over the datasets. So you'd can do the math and figure out how many full passes 600 iterations is based on the size of the training set you are using and the batch size 😉

**Comment by gladjoyhub** [comment]
My dataset is a jsonl file of 1500 lines
{"text": "yada yada yada..."} X1500

So for 3 epochs, would it be 3 * 1500 or 4500 Iters?

**Comment by awni** [comment]
For 3 epochs it would be `(1500 / batch_size) * 3`. If `batch_size=1` then it is indeed `4500` iterations.
