### ISSUE TITLE
[Question] How do you generate from a model after 'chained' LoRa trainning?

### ISSUE THREAD

**Issue by chimezie** [ml-explore/mlx-examples#327]
I have qLora finetuned a mistral model via:

```bash
python lora/convert.py --hf-path mistralai/Mistral-7B-Instruct-v0.1 -q --mlx-path /path/to/raw_model/mlx
python lora.py --model /path/to/raw_model/mlx --train --data /path/to/data \
                          --adapter-file /path/to/adapter_file1.npz 
python lora.py --model /path/to/raw_model/mlx --train --data /path/to/data \
                         --resume-adapter-file /path/to/adapter_file1.npz \
                        --adapter-file /path/to/adapter_file2.npz 
```

I.e., the LoRa weights from the first training were stored in /path/to/adapter_file1.npz and the weights from the second training (which resumed from the state of this first set of weights) were stored in /path/to/adapter_file2.npz 

Will that second adapter file (adapter_file2.npz) be the cumulative adjustment for both training such that the first one can be deleted? if so, is all I need to generate from the state of this cumulative training the following?:

python lora.py --prompt "Some prompt" --model /path/to/raw_model/mlx  --adapter-file /path/to/adapter_file2.npz 

Or will I somehow need to specify both?

**Comment by awni** [comment]
>  if so, is all I need to generate from the state of this cumulative training the following?:

Yes that's correct! You only need to specify the second adapter file, not both. Specifying both would be wrong actually. When you load from the first and resuming training the adapters are updated from where you left off and then resaved.
