### ISSUE TITLE
mx.load(wf) cause RuntimeError

### ISSUE THREAD

**Issue by gladjoyhub** [ml-explore/mlx-examples#336]
I am able to run this code no problem in the miniconda venv that I installed just for MLX solely:

from mlx_lm import load, generate
model, tokenizer = load("/Users/joy/mlx_model/solar_q8")

But in my old pycharm venv, got this error:
RuntimeError: [load] Invalid header in file /Users/joy/mlx_model/solar_q8/weights.00.safetensors

I traced it to the line 171 in utils.py:
weights.update(mx.load(wf))

I googled around and found some one post similar problem on huggingface:

[Mlx_lm convert TinyLlama-1.1B-Chat-v1.0 failed RuntimeError : [load] Invalid header in file](https://discuss.huggingface.co/t/mlx-lm-convert-tinyllama-1-1b-chat-v1-0-failed-runtimeerror-load-invalid-header-in-file/69570)
[Beginners](https://discuss.huggingface.co/c/beginners/5)

[hhofchina](https://discuss.huggingface.co/u/hhofchina)
[21h](https://discuss.huggingface.co/t/mlx-lm-convert-tinyllama-1-1b-chat-v1-0-failed-runtimeerror-load-invalid-header-in-file/69570)
I have an issue when I try to run python -m mlx_lm.convert --hf-path ./TinyLlama-1.1B-Chat-v1.0/TinyLlama-1.1B-Chat-v1.0 --mlx-path ./mlx_model -q:

RuntimeError: [load] Invalid header in file ./TinyLlama-1.1B-Chat-v1.0/model.safetensors

Please help, thanks!

**Comment by mzbac** [comment]
The safetensors support was added in the recent mlx package. I guess maybe one of your environments is somehow using the old mlx package? Would you try `pip install -U mlx` to see if that fixes the issue?

**Comment by gladjoyhub** [comment]
Yes, that solved it. Thank you very much!
