### ISSUE TITLE
 [load] Invalid header in file /Users/xxx/.cache/huggingface/hub/models--mistralai--Mistral-7B-v0.1/snapshots/26bca36bde8333b5d7f72e9ed20ccda6a618af24/model-00001-of-00002.safetensors

### ISSUE THREAD

**Issue by LanLanBoom** [ml-explore/mlx-examples#341]
I'm trying out mlx_lm on my Macbook with M2 chips.  I run this command line
`
 python -m mlx_lm.generate --model mistralai/Mistral-7B-v0.1 --prompt "hello" `

I got this error.
`RuntimeError: [load] Invalid header in file /Users/xxx/.cache/huggingface/hub/models--mistralai--Mistral-7B-v0.1/snapshots/26bca36bde8333b5d7f72e9ed20ccda6a618af24/model-00001-of-00002.safetensors`

I have no idea why.  I followed the README instruction.  
Please help to figure this out!

Thank you very much!

**Comment by mzbac** [comment]
That's caused by an outdated mlx. Would you try installing the latest mlx with `pip install -U mlx`?

**Comment by LanLanBoom** [comment]
Solved!  Thank you!
