### ISSUE TITLE
convert.py doesn't know how to handle large models

### ISSUE THREAD

**Issue by leedrake5** [ml-explore/mlx-examples#35]
Instructions [here](https://github.com/ml-explore/mlx-examples/tree/main/llama) don't work for large models, which are often stored as shards. Can /llama/convert.py be adapted to handle models available on hugginface such as [this](https://huggingface.co/Phind/Phind-CodeLlama-34B-v2)? Even saving the shards individually with mlx support can work.

**Comment by BuildBackBuehler** [comment]
? You can cat shards together. That's no problem. 

What I am running into, though, is none of the models on HuggingFace seem to include the (apparently required) `OSError: SavedModel file does not exist at: [InsertPathHere]/{saved_model.pbtxt|saved_model.pb}` – instead they'll have JSONs for the weights and so on and so forth and unfortunately there is no straightforward conversion to protobuf. 

(For providing an arg for the tf model's weight conf.)

That is just for Tensorflow. So for my Llama conversion, I have a feeling that with Pytorch, it'd go smoothly. At least I believe everything is typically bundled into a .tar/.zip or w/e. TBH, though I couldn't find any documentation on it, I figure that the .safetensors, etc. *do* have some sort of archive-like contents to them but it can't be readily seen and doesn't necessarily always include the same files.

I found that the Llama one was a tad more difficult to modify for TF. The Mistral one was easy enough I think anyone could modify it quite quickly.

**Comment by leedrake5** [comment]
Embarrassed I didn't think to use cat. That worked, though still errors out with safe tensors

 ```
 File "~/GitHub/mlx-examples/llama/convert.py", line 49, in <module>
    state = torch.load(args.torch_weights)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "~/miniconda3/envs/pytorch/lib/python3.11/site-packages/torch/serialization.py", line 1040, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "~/miniconda3/envs/pytorch/lib/python3.11/site-packages/torch/serialization.py", line 1258, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
_pickle.UnpicklingError: invalid load key, '\x04'.
```

...and with original .bin

```
Traceback (most recent call last):
  File "~/GitHub/mlx-examples/llama/convert.py", line 49, in <module>
    state = torch.load(args.torch_weights)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "~/miniconda3/envs/pytorch/lib/python3.11/site-packages/torch/serialization.py", line 1005, in load
    with _open_zipfile_reader(opened_file) as opened_zipfile:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "~/miniconda3/envs/pytorch/lib/python3.11/site-packages/torch/serialization.py", line 457, in __init__
    super().__init__(torch._C.PyTorchFileReader(name_or_buffer))
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: PytorchStreamReader failed reading zip archive: invalid header or archive is corrupted
```

Looking through code and examples it's not clear what torch_weights means. Maybe .chkpt? But not sure how to recreate those from either safe tensors or .bin

**Comment by leedrake5** [comment]
Ok, so what failed less dramatically was this: 

```
from transformers import LlamaForCausalLM, LlamaTokenizer

tokenizer = LlamaTokenizer.from_pretrained("~/LLM/Phind-CodeLlama-34B-v2")
model = LlamaForCausalLM.from_pretrained("~LLM/Phind-CodeLlama-34B-v2")

torch.save(model, "~/LLM/phind.pth")
```

Then running their example: 

`python ~/GitHub/mlx-examples/llama/convert.py ~/LLM/phind.pth ~/LLM/mlx_phind_weights.npz
`

But this also fails. 

```
~/miniconda3/envs/pytorch/lib/python3.11/site-packages/transformers/utils/generic.py:441: UserWarning: torch.utils._pytree._register_pytree_node is deprecated. Please use torch.utils._pytree.register_pytree_node instead.
  _torch_pytree._register_pytree_node(
~/miniconda3/envs/pytorch/lib/python3.11/site-packages/transformers/utils/generic.py:309: UserWarning: torch.utils._pytree._register_pytree_node is deprecated. Please use torch.utils._pytree.register_pytree_node instead.
  _torch_pytree._register_pytree_node(
~/miniconda3/envs/pytorch/lib/python3.11/site-packages/transformers/utils/generic.py:309: UserWarning: torch.utils._pytree._register_pytree_node is deprecated. Please use torch.utils._pytree.register_pytree_node instead.
  _torch_pytree._register_pytree_node(
Traceback (most recent call last):
  File "~/GitHub/mlx-examples/llama/convert.py", line 52, in <module>
    **{k: v for k, v in starmap(map_torch_to_mlx, state.items()) if k is not None}
                                                  ^^^^^^^^^^^
  File "~/miniconda3/envs/pytorch/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1688, in __getattr__
    raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")
AttributeError: 'LlamaForCausalLM' object has no attribute 'items'
```

I'm increasingly confident I can figure out how to get the model to work, but the convert.py script has very specific but not defined expectations for what the .pth file should look like. More documentation would make it much easier to use.

**Comment by BuildBackBuehler** [comment]
Ah I see! So if I'm reading this correctly, you mitigated that issue I had mentioned(?) Therein providing the out-the-box torch.bin you get for some models

I imagine the way you are doing it would take a little more time, but not knowing how the inner machinations work, I don't know if it can quickly find the weights within the full torch.bin model, therefore a negligible time and a good shortcut/workaround. 

There's a HuggingFace convert.py that has a wholeeee lot more scenarios. It may elucidate the variations of code needed to make it work as-intended. Still haven't gotten around to fixing up the .safetensor attempt I did. Got interested in a Mistral model I'm trying next, should be straightforward. Then will be running this for a llama-based model.

**Comment by BuildBackBuehler** [comment]
I've found that everything needed is definitely within Safetensor's docs
https://huggingface.co/docs/safetensors/api/torch#safetensors.torch.load.returns

Still having problems, nonetheless. Also realized that .gguf is not optimal for Silicon. Better to use GPTQ, perhaps compressed with exllama2. I don't know what MLX does as far as how well AARM64 handles higher FPs...just know that for Stable Diff., needed an 8-bit. 

I think what also needs a bit of expansion is what exactly is the "output file" arg as well. While it'd normally make sense that it would just be to provide a name for the convert.py's final product, I could've sworn I saw some example that showed that argument as a means of identifying the mmapping or whatever else. 

–-

`from transformers import LlamaForCausalLM, LlamaTokenizer

tokenizer = LlamaTokenizer.from_pretrained("~/LLM/Phind-CodeLlama-34B-v2")
model = LlamaForCausalLM.from_pretrained("~/LLM/Phind-CodeLlama-34B-v2")

torch.save(model, "~/LLM/phind.pth")`

Works if you want to also download the repo with that code. I couldn't get it to work with *just* weights – which from I read seems to be the pytorch_bin.index.json. 

I tried to replace torch.save(model) 

Personally, I'd already cloned the repo and just wanted to get a cached away torch/safetensors_weight file for convert.py but couldn't quite get the code right.

I have a feeling it has to do with ST's usage of load vs load_file. 

Or save/safetensors.torch.save_file, seems the _file is added for support files. 

The other thing I noted is that what convert.py necessitates is the "model.state_dict()"

No sleep. If I remember I'll reorganize my thoughts. Figured in the meantime, might help someone.

**Comment by AlexanderIstomin** [comment]
You can do it using the transformers library which can load sharded model automatically:
```
from transformers import AutoModelForCausalLM
model = AutoModelForCausalLM.from_pretrained("./Mistral-7B-Instruct-v0.2/")
```
^^^ sharded model folder

and then
```
np.savez(
        str("./weights.npz"),
        **{k: v.to(torch.float16).numpy() for k, v in model.state_dict().items()}
    )
```

**Comment by awni** [comment]
This should work in the latest llama example #82 . Let me know if you run into issues!
