### ISSUE TITLE
mlx_lm.convert seems to modify special_tokens_map.json, tokenizer_config.json in significant ways

### ISSUE THREAD

**Issue by da-z** [ml-explore/mlx-examples#355]
Hi. I am trying to understand issues with a conversion of NeuralBeagle14 which does not correctly use stop words when using ChatML in prompts.

It seems that the generated special_tokens_map.json, tokenizer_config.json are different than in the original model. Is this the cause why the model does not stop correctly?

To reproduce, compare the *.json files in `./mlx-community/NeuralBeagle14-7B-X-4bit-mlx` (cli below) with the original ones at https://huggingface.co/mlabonne/NeuralBeagle14-7B/tree/main

```sh
python3 -m mlx_lm.convert --hf-path mlabonne/NeuralBeagle14-7B -q --mlx-path mlx-community/NeuralBeagle14-7B-X-4bit-mlx
```

**Comment by mzbac** [comment]
Just a quick thought, it may be related to the transformers. Would you mind trying to upgrade to the latest transformers and see if the problem still exists?

**Comment by da-z** [comment]
Thanks. I am using transformers 4.37.0 and I had the same issues few days ago, with older version of transformers (4.36.2 I think)

Same issue 🫤 This is what I see in console when converting/loading:

```
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
```

**Comment by mzbac** [comment]
> Thanks. I am using transformers 4.37.0 and I had the same issues few days ago, with older version of transformers (4.36.2 I think)
> 
> Same issue 🫤 This is what I see in console when converting/loading:
> 
> ```
> Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
> ```

Yeah, the convert script loads the tokenizer from the original model path and saves it to another folder. It doesn't make sense that it changes. may need to dig a bit deeper into the transformer code to see what happened.

**Comment by awni** [comment]
@mzbac this seems simply due to the fact that Neural Beagle updated their config after we converted?

**Comment by awni** [comment]
The `special_tokens_map.json` appear to be the same between the two repose, so i think the only difference is from the updated `tokenizer_config.json`. We can patch it in the mlx community version as well

**Comment by da-z** [comment]
original `special_tokens_map.json`:

```json
{
  "additional_special_tokens": [
    "<unk>",
    "<s>",
    "</s>"
  ],
  "bos_token": {
    "content": "<s>",
    "lstrip": false,
    "normalized": false,
    "rstrip": false,
    "single_word": false
  },
  "eos_token": {
    "content": "</s>",
    "lstrip": false,
    "normalized": false,
    "rstrip": false,
    "single_word": false
  },
  "pad_token": {
    "content": "</s>",
    "lstrip": false,
    "normalized": false,
    "rstrip": false,
    "single_word": false
  },
  "unk_token": {
    "content": "<unk>",
    "lstrip": false,
    "normalized": false,
    "rstrip": false,
    "single_word": false
  }
}
```

converted `special_tokens_map.json`:

```json
{
  "bos_token": {
    "content": "<|im_start|>",
    "lstrip": false,
    "normalized": false,
    "rstrip": false,
    "single_word": false
  },
  "eos_token": {
    "content": "<|im_end|>",
    "lstrip": false,
    "normalized": false,
    "rstrip": false,
    "single_word": false
  },
  "unk_token": {
    "content": "<unk>",
    "lstrip": false,
    "normalized": false,
    "rstrip": false,
    "single_word": false
  }
}
```

original `tokenizer_config.json`:

```json
{
  "add_bos_token": true,
  "add_eos_token": false,
  "added_tokens_decoder": {
    "0": {
      "content": "<unk>",
      "lstrip": false,
      "normalized": false,
      "rstrip": false,
      "single_word": false,
      "special": true
    },
    "1": {
      "content": "<|im_start|>",
      "lstrip": false,
      "normalized": false,
      "rstrip": false,
      "single_word": false,
      "special": true
    },
    "2": {
      "content": "<|im_end|>",
      "lstrip": false,
      "normalized": false,
      "rstrip": false,
      "single_word": false,
      "special": true
    },
    "32000": {
      "content": "<|im_end|>",
      "lstrip": false,
      "normalized": false,
      "rstrip": false,
      "single_word": false,
      "special": true
    },
    "32001": {
      "content": "<|im_start|>",
      "lstrip": false,
      "normalized": false,
      "rstrip": false,
      "single_word": false,
      "special": true
    }
  },
  "additional_special_tokens": [],
  "bos_token": "<|im_start|>",
  "chat_template": "{% for message in messages %}{{'<|im_start|>' + message['role'] + '\n' + message['content'] + '<|im_end|>' + '\n'}}{% endfor %}{% if add_generation_prompt %}{{ '<|im_start|>assistant\n' }}{% endif %}",
  "clean_up_tokenization_spaces": false,
  "eos_token": "<|im_end|>",
  "legacy": true,
  "model_max_length": 1000000000000000019884624838656,
  "pad_token": null,
  "sp_model_kwargs": {},
  "spaces_between_special_tokens": false,
  "tokenizer_class": "LlamaTokenizer",
  "trust_remote_code": false,
  "unk_token": "<unk>",
  "use_default_system_prompt": true,
  "use_fast": true
}
```

converted `tokenizer_config.json`:

```json
{
  "add_bos_token": true,
  "add_eos_token": false,
  "added_tokens_decoder": {
    "0": {
      "content": "<unk>",
      "lstrip": false,
      "normalized": false,
      "rstrip": false,
      "single_word": false,
      "special": true
    },
    "1": {
      "content": "<s>",
      "lstrip": false,
      "normalized": false,
      "rstrip": false,
      "single_word": false,
      "special": true
    },
    "2": {
      "content": "</s>",
      "lstrip": false,
      "normalized": false,
      "rstrip": false,
      "single_word": false,
      "special": true
    },
    "32000": {
      "content": "<|im_start|>",
      "lstrip": false,
      "normalized": false,
      "rstrip": false,
      "single_word": false,
      "special": true
    },
    "32001": {
      "content": "<|im_end|>",
      "lstrip": false,
      "normalized": false,
      "rstrip": false,
      "single_word": false,
      "special": true
    }
  },
  "additional_special_tokens": [],
  "bos_token": "<|im_start|>",
  "chat_template": "{% for message in messages %}{{'<|im_start|>' + message['role'] + '\n' + message['content'] + '<|im_end|>' + '\n'}}{% endfor %}{% if add_generation_prompt %}{{ '<|im_start|>assistant\n' }}{% endif %}",
  "clean_up_tokenization_spaces": false,
  "eos_token": "<|im_end|>",
  "legacy": true,
  "model_max_length": 1000000000000000019884624838656,
  "pad_token": null,
  "sp_model_kwargs": {},
  "spaces_between_special_tokens": false,
  "tokenizer_class": "LlamaTokenizer",
  "trust_remote_code": false,
  "unk_token": "<unk>",
  "use_default_system_prompt": true,
  "use_fast": true
}
```

**Comment by da-z** [comment]
> @mzbac this seems simply due to the fact that Neural Beagle updated their config after we converted?
> 
> Looks like the [last edit](https://huggingface.co/mlabonne/NeuralBeagle14-7B/commit/96508c101a1e6e55b02b60c455f2d64b3c1b37cc#d2h-846292) to `tokenizer_config.json` was 4 hours ago :)

I am aware of that change. Was due in part to my (and others) request to fix some issues related to stop words. That is how I noticed that the generated .json files are different in mlx_lm.convert. Not sure if that is the cause of the model not behaving nice in mlx-ul. Link to my comment there https://huggingface.co/mlabonne/NeuralBeagle14-7B/discussions/3#65af81ca101482afcc8b6fa6

Thanks a lot for looking into this. I really would like NeuralBeagle14 to work in the mlx-ui :)

**Comment by awni** [comment]
You should be able to fine the cache here `ls $HOME/.cache/huggingface/hub/`

**Comment by da-z** [comment]
No prob. Yes, I checked the cache already, even made sure I removed the previous commit of mlabonne/NeuralBeagle14 original. The ref is pointing to the latest master commit.

Then the only mlx model of NeuralBeagle14 I have on my machine is the one I am converting now, so I don't suspect other caching issues there.

From what I see in transformers, it does some sorting of the json keys at least, but from what I see there is also some filtering (some keys do not make it in the transformed .json files)

**Comment by da-z** [comment]
OK, so from what I understand, it is expected that the converted .json files are different given the state of the original ones, correct? If that is the case it means that more tweaks should be done on the original models' config and I can close this issue.

**Comment by mzbac** [comment]
> OK, so from what I understand, it is expected that the converted .json files are different given the state of the original ones, correct? If that is the case it means that more tweaks should be done on the original models' config and I can close this issue.

From what I can see from transforms code, special_token_map.json and added_token.json are marked as legacy. I guess you may not need them.

**Comment by da-z** [comment]
I see. Thanks a lot! Eventually I found a workaround on my side. I will close this issue as indeed the model seems to be working fine now in my app.

Given 2 and 32000 are pretty much standard codes from what I see in ChatML compatible models:

```python
if token in [2, 32000, tokenizer.eos_token_id]:
    break
```

**Comment by da-z** [comment]
Closing the issue as it seems the generated .json files should work fine even if they are slightly altered from the original.
