### ISSUE TITLE
missing positional encoding in transformer_lm

### ISSUE THREAD

**Issue by 0x1orz** [ml-explore/mlx-examples#359]
The positional encoding is essential in transformer models, while that is missing in all of  `transformer_lm/*main.py`.

**Comment by awni** [comment]
Good point we should indeed add it!

**Comment by 0x1orz** [comment]
I implemented the positional encoding module in mlx as following the snippet, referenced to the pytorch transformer [toturial ](https://pytorch.org/tutorials/beginner/transformer_tutorial.html)

```python
import mlx.core as mx
import numpy as np
class PositionalEncoding(nn.Module):
    def __init__(self, model_dims, max_len=5000):
        super().__init__()
        self.model_dims = model_dims
        self.max_len = max_len
    
    def __call__(self, x: mx.array) -> mx.array:
        x = x + self.weight[:x.shape[0]]
        return x
    
    @property
    def weight(self):
        pos = mx.arange(self.max_len).reshape((self.max_len, 1))
        pos = pos*mx.exp(mx.arange(0, self.dims,2)*(-np.log(10000)) / self.model_dims)
        pe = mx.zeros((self.max_len, 1, self.model_dims))
        pe[:, 0, 0::2] = mx.sin(pos)
        pe[:, 0, 1::2] = mx.cos(pos)
        return pe
````
all worked as expected. 

But  I used  the mlx module `mlx.nn.SinusoidalPositionalEncoding` instead, 

```python
class TransformerLM(nn.Module):
    def __init__(self, vocab_size: int, num_layers: int, dims: int, num_heads: int):
        super().__init__()

        self.embedding = nn.Embedding(vocab_size, dims)
        self.pos_embedding = nn.SinusoidalPositionalEncoding(dims)
        self.transformer = nn.TransformerEncoder(num_layers, dims, num_heads)
        self.out_proj = nn.Linear(dims, vocab_size)

    def __call__(self, x):
        mask = nn.MultiHeadAttention.create_additive_causal_mask(x.shape[1])
        x = self.embedding(x)
        x = x + self.pos_embedding(x)
        x = self.transformer(x, mask)
        return self.out_proj(x)
```
that raised
```
    x = x + self.pos_embedding(x)
        ~~^~~~~~~~~~~~~~~~~~~~~~~
ValueError: Shapes (2,1024,1024) and (2,1024,1024,1024) cannot be broadcast.
```

The  SinusoidalPositionalEncoding module confused me,  which is  completely differenced with the referenced paper “Attention Is All You Need".

**Comment by 0x1orz** [comment]
I tried the module `mlx.nn.SinusoidalPositionalEncoding`, like
```python
class TransformerLM(nn.Module):
    def __init__(self, vocab_size: int, num_layers: int, dims: int, num_heads: int):
        super().__init__()

        self.embedding = nn.Embedding(vocab_size, dims)
        self.pos_embedding = nn.SinusoidalPositionalEncoding(dims)
        self.transformer = nn.TransformerEncoder(num_layers, dims, num_heads)
        self.out_proj = nn.Linear(dims, vocab_size)

    def __call__(self, x):
        mask = nn.MultiHeadAttention.create_additive_causal_mask(x.shape[1])
        x = self.embedding(x)
        x = x + self.pos_embedding(x)
        x = self.transformer(x, mask)
        return self.out_proj(x)
```
that raised 
```
    x = x + self.pos_embedding(x)
        ~~^~~~~~~~~~~~~~~~~~~~~~~
ValueError: Shapes (2,1024,1024) and (2,1024,1024,1024) cannot be broadcast.
```
! am confused, `nn.SinusoidalPositionalEncoding` is completely differented with the referenced  paper `Attention Is All You Need <https://arxiv.org/abs/1706.03762>'.

instead, I referenced the pytorch transformer [toturial](https://pytorch.org/tutorials/beginner/transformer_tutorial.html), implemented  the following 
```python3
class PositionalEncoding(nn.Module):
    def __init__(self, model_dims, max_len=5000):
        super().__init__()
        self.model_dims = model_dims
        self.max_len = max_len

    def __call__(self, x: mx.array) -> mx.array:
        return self.weight[:x.shape[0]]
   
    @property
    def weight(self):
        pos = mx.arange(self.max_len).reshape((self.max_len, 1))
        pos = pos*mx.exp(mx.arange(0, self.model_dims,2)*(-np.log(10000)) / self.model_dims)
        pe = mx.zeros((self.max_len, 1, self.model_dims))
        pe[:, 0, 0::2] = mx.sin(pos)
        pe[:, 0, 1::2] = mx.cos(pos)
        return pe
```

**Comment by 0x1orz** [comment]
Should the input array `x`  be the indices of the sequence  for  'nn.SinusoidalPositionalEncoding' instance ?  
```python
class TransformerLM(nn.Module):
    def __init__(self, vocab_size: int, num_layers: int, dims: int, num_heads: int):
        super().__init__()

        self.embedding = nn.Embedding(vocab_size, dims)
        self.pos_embedding = nn.SinusoidalPositionalEncoding(dims)
        self.transformer = nn.TransformerEncoder(num_layers, dims, num_heads)
        self.out_proj = nn.Linear(dims, vocab_size)

    def __call__(self, x):
        mask = nn.MultiHeadAttention.create_additive_causal_mask(x.shape[1])
        x = self.embedding(x)
        x = x + self.pos_embedding(mx.arange(x.shape[1]))
        x = self.transformer(x, mask)
        return self.out_proj(x)
```

**Comment by mzbac** [comment]
The positional encoding for the transformer should be very similar to the nn.Rope layer. Instead of calculating sin/cos per token, you may need to build the entire pos_embedding and apply it to the entire sequence. Have a look at the implementation in plamo imp -> https://github.com/ml-explore/mlx-examples/blob/main/llms/mlx_lm/models/plamo.py#L70

**Comment by 0x1orz** [comment]
@mzbac Yeah. And we could faster update the sin/cos cache with the range(seq_len, self.max_seq_len_cached) if seq_len > self.max_seq_len_cached and self.max_seq_len_cached is so large.

**Comment by dsedov** [comment]
I have a few examples in my repo: 
https://github.com/dsedov/preditor/blob/main/n3xx_mlx/llm_classes.py
It has both traditional and RoPE
And all the layers described here:
https://github.com/dsedov/preditor/blob/main/n3xx_mlx/modules.py

**Comment by angeloskath** [comment]
> Should the input array `x` be the indices of the sequence for 'nn.SinusoidalPositionalEncoding' instance ?
> 
> ```python
> class TransformerLM(nn.Module):
>     def __init__(self, vocab_size: int, num_layers: int, dims: int, num_heads: int):
>         super().__init__()
> 
>         self.embedding = nn.Embedding(vocab_size, dims)
>         self.pos_embedding = nn.SinusoidalPositionalEncoding(dims)
>         self.transformer = nn.TransformerEncoder(num_layers, dims, num_heads)
>         self.out_proj = nn.Linear(dims, vocab_size)
> 
>     def __call__(self, x):
>         mask = nn.MultiHeadAttention.create_additive_causal_mask(x.shape[1])
>         x = self.embedding(x)
>         x = x + self.pos_embedding(mx.arange(x.shape[1]))
>         x = self.transformer(x, mask)
>         return self.out_proj(x)
> ```

Yep that is precisely it. The `SinusoidalPositionalEncoding` can encode any real number and is not limited to discrete positions. It would be the same encoding used for a NERF or if you want to extrapolate your data you could do `self.pos_embedding(mx.arange(x.shape[1])/2)` (assuming the model was trained with half the length).

I don't think there is a need to cache the positional encoding or fix it as a buffer in the module. Even for RoPE computing the frequencies takes no time at all compared to applying it to the vectors. In this case encoding 1000 numbers would take comparable time to the addition (especially with a large batch size) and significantly less time than the first matmul (and there will be many of those).

Having said that you could always just do the following

```
# underscore to make it a constant
self._pe_buffer = nn.SinusoidalPositionalEncoding(dims)(mx.arange(max_length))

# in the __call__
x = x + self._pe_buffer[:x.shape[1]]
```

**Comment by 0x1orz** [comment]
@angeloskath thanks.
