### ISSUE TITLE
AttributeError: 'tuple' object has no attribute 'item' in mlx-lm-0.0.4

### ISSUE THREAD

**Issue by mzbac** [ml-explore/mlx-examples#362]
There is a bug in the 0.0.4 release due to the change of the generate_step function returning a tuple instead of a token: https://github.com/ml-explore/mlx-examples/blob/21aa8038fb8048c7981a27f7c1aea2800e34132c/llms/mlx_lm/utils.py#L142

@awni we might need to release a new version to fix the broken one.

**Comment by awni** [comment]
Argg, another example of the CLI working but not the API 😬 

We can easily do a new release and yank 0.0.4, that's not a problem

I will have to add tests shortly, there's too many options at this point to test it all manually.

**Comment by mzbac** [comment]
Unit testing would be great, thanks. 🚀

**Comment by qiuhaolu** [comment]
met this as well

**Comment by awni** [comment]
Sorry about that! I will update now.

**Comment by awni** [comment]
Ok `0.0.5` is up. Closing this.
