### ISSUE TITLE
mlx-lm 0.0.4 - ValueError: Missing parameters: lm_head.biases lm_head.scales

### ISSUE THREAD

**Issue by da-z** [ml-explore/mlx-examples#367]
Hi guys.

[mlx-ui](https://github.com/da-z/mlx-ui) users are getting this error after bumping from 0.0.3 to 0.0.4, while 0.0.3 continues to work fine, same models.

```sh
File "/Users/x/dev/mlx-ui/venv/lib/python3.11/site-packages/mlx_lm/utils.py", line 232, in load
    model = load_model(model_path)
            ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/x/dev/mlx-ui/venv/lib/python3.11/site-packages/mlx_lm/utils.py", line 205, in load_model
    model.load_weights(list(weights.items()))
  File "/Users/x/dev/mlx-ui/venv/lib/python3.11/site-packages/mlx/nn/layers/base.py", line 151, in load_weights
    raise ValueError(f"Missing parameters: {missing}.")
ValueError: Missing parameters: lm_head.biases lm_head.scales.
```

Is there anything I can do on mlx-ui side?

**Comment by awni** [comment]
Sorry for that, I will take a look. Is it with the NousHermes model?

**Comment by da-z** [comment]
No worries and no rush 😊 (I am using cached requirements.txt from repo now)

I've reproduced with 2 models:

```
mlx-community/dolphin-2.6-mistral-7b-dpo-laser-4bit-mlx
mlx-community/Nous-Hermes-2-Mixtral-8x7B-DPO-4bit
```

**Comment by awni** [comment]
Hmm, I see the problem. We updated MLX to quantize non 32 multiples. So now we don't by default assume those layers are not quantized.

**Comment by awni** [comment]
It's a problem of back compatibility. It's messy to support those old models while also supporting new models that are fully quantized. 

One option is to make a little script that can download, quantize the linear layer, and then re-upload 🤔 

@mzbac what do you think?

**Comment by mzbac** [comment]
> It's a problem of back compatibility. It's messy to support those old models while also supporting new models that are fully quantized.
> 
> One option is to make a little script that can download, quantize the linear layer, and then re-upload 🤔
> 
> @mzbac what do you think?

Non-32-dimensional quantization shouldn't cause the issue. We still have that `m.weight.shape[0]!= 8`, so it may be caused by something else. I can take a look at those two models.

**Comment by awni** [comment]
No that's just for gating :), this is for the LM head

**Comment by awni** [comment]
This is [what changed](https://github.com/ml-explore/mlx-examples/commit/195bec2fa3fbde91ceedbf79a7aaa6c2d23148b3#diff-0a6a68b052d33b27711b2bbd8dc70ec07b41ad35e71e2cca1c6bbe18c8a746b0R24-R27), as you can see we used to check for multiples of 32 (not just the gate size)

**Comment by mzbac** [comment]
> This is [what changed](https://github.com/ml-explore/mlx-examples/commit/195bec2fa3fbde91ceedbf79a7aaa6c2d23148b3#diff-0a6a68b052d33b27711b2bbd8dc70ec07b41ad35e71e2cca1c6bbe18c8a746b0R24-R27), as you can see we used to check for multiples of 32 (not just the gate size)

@awni  it's possible that the lm_head model wasn't quantized due to non-32 dimensions, now the loaded model converts the lm_head into a quant layer cause the weight mismatch. I am checking the dimensions of the lm_head of the model now.

**Comment by awni** [comment]
Yes exactly, it is not a multiple of 32

**Comment by awni** [comment]
This usually happens for fine-tuned models where a couple of tokens were added to the vocab. So it's probably pretty common in the mlx-community.

**Comment by mzbac** [comment]
> This usually happens for fine-tuned models where a couple of tokens were added to the vocab. So it's probably pretty common in the mlx-community.

I think the quick workaround is to not quantize lm_head. I also noticed that quantizing and de-quantizing lm_head could cause some performance issues.

**Comment by awni** [comment]
> I think the quick workaround is to not quantize lm_head. I also noticed that quantizing and de-quantizing lm_head could cause some performance issues. @awni what do you think?

There's always perf degradation from quantization so that's unavoidable. I don't know if the LM head is worse than other layers in that respect 🤷‍♂️ , if it is then maybe that's the right call. But then again you do get a nice memory and speed boost by quantizing the LM head since it is the biggest matrix in the model.

I think I would prefer rather than blanket not quantizing LM heads in general (which will break existing models that have quantized LM heads), to special case legacy models if it's not too complex to do it.

**Comment by awni** [comment]
Thanks for the quick fix @mzbac, this should be fixed in main now. I will do a 0.0.5 release today @da-z then you can hopefully use that 😄

**Comment by da-z** [comment]
Thanks a lot! I can confirm the fix. Monkey patched the file for now to test. 😊

**Comment by awni** [comment]
Thanks for the verification!
