### ISSUE TITLE
Contrained Generation and Accessing Token Probabilities

### ISSUE THREAD

**Issue by mlinegar** [ml-explore/mlx-examples#372]
Is it possible to constrain the output of LLMs to only include particular token sequences? Is it possible to then access the probabilities of each of these token sequences? 

This is useful in many cases, and is implemented in LMQL: [https://lmql.ai/docs/language/constraints.html](https://lmql.ai/docs/language/constraints.html). Does this seem possible in MLX?

**Comment by LeonEricsson** [comment]
Depending on the particular model you're interested in I suppose you could modify the generate() function to achieve your desired behaviour. For example, in the [mistral example](https://github.com/LeonEricsson/mlx-examples/blob/0340113e02dbb3b29c656132232ca24835cd4f79/llms/mistral/mistral.py#L213) you could change the sample function to something like this

```
constrained_tokens = [4, 1551, 9143, 300, 1440]

def sample(logits):
    # extract constrained token logits
    constrained_logits = logits[constrained_tokens]

    # probabilities of constrained logits
    probs = mx.softmax(constrained_logits)

    # return random sample and probabilities
    return mx.random.categorical(constrained_logits * (1 / temp)), probs
```

**Comment by awni** [comment]
I think something like this might also be interesting for you: https://github.com/sacha-ichbiah/outlines-mlx

I'll close this issue as it's quite general. Feel free to open a discussion
