### ISSUE TITLE
Error Lora fuse.py --de-quantize 

### ISSUE THREAD

**Issue by AlexisBalayre** [ml-explore/mlx-examples#376]
Hi, I encountered the following error with this command:
python3 fuse.py --de-quantize \
 --model mistralai/Mistral-7B-Instruct-v0.2 \
 --adapter-file ./fine-tuning/adapters/adapters.npz \
 --save-path ./Models/My-Mistral-7B-fine-tuned

Loading pretrained model
Fetching 11 files: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 11/11 [00:00<00:00, 104619.83it/s]
Traceback (most recent call last):
  File "/Users/alexis/Programmation/mlx-examples/lora/fuse.py", line 98, in <module>
    model.update_modules(tree_unflatten(de_quantize_layers))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/alexis/Programmation/mlx-examples/lora/venv/lib/python3.11/site-packages/mlx/utils.py", line 123, in tree_unflatten
    int(tree[0][0].split(".", maxsplit=1)[0])
        ~~~~^^^
IndexError: list index out of range

**Comment by mzbac** [comment]
This is because the model you are trying to de-quantize is not a quantized model, so it throws an error when attempting to update the empty weight dict.
