### ISSUE TITLE
KeyError: 'text' When Training w lora.py

### ISSUE THREAD

**Issue by USMCM1A1** [ml-explore/mlx-examples#381]
I'm trying to train a writing prompt model, and keep getting an error whenever I try and train:

`(base) Williams-MacBook-Pro-3:lora williammarcellino$ python lora.py --model /Users/williammarcellino/mlx-examples/lora/mlx_model --train --iters 489 --batch-size 4
Loading pretrained model
Total parameters 7243.436M
Trainable parameters 1.704M
Loading datasets
Training
Traceback (most recent call last):
  File "/Users/williammarcellino/mlx-examples/lora/lora.py", line 324, in <module>
    train(model, train_set, valid_set, opt, loss, tokenizer, args)
  File "/Users/williammarcellino/mlx-examples/lora/lora.py", line 222, in train
    for it, batch in zip(
  File "/Users/williammarcellino/mlx-examples/lora/lora.py", line 177, in iterate_batches
    batch = [tokenizer.encode(dset[indices[i + j]]) for j in range(batch_size)]
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/williammarcellino/mlx-examples/lora/lora.py", line 177, in <listcomp>
    batch = [tokenizer.encode(dset[indices[i + j]]) for j in range(batch_size)]
                              ~~~~^^^^^^^^^^^^^^^^
  File "/Users/williammarcellino/mlx-examples/lora/lora.py", line 128, in __getitem__
    return self._data[idx][self._key]
           ~~~~~~~~~~~~~~~^^^^^^^^^^^
KeyError: 'text'
`

I have tried multiple iterations in case there was a fractional error, basically 389-395 and no dice.  I suspect maybe I am making an error in my training data format. I have varied my Q&A format to a more alpaca-like format for prompting:

`{"Instruction": "Write a story section featuring a character who finds themselves surrounded by a curious crowd while wearing a concealing cloak. The character should feel both pity and revulsion towards the crowd, and should be asked a series of probing questions that they do not wish to answer. One member of the crowd should be particularly fixated on the character, and their behavior should be reminiscent of a crazed obsession.\n\nIn this section, focus on developing the atmosphere of unease and discomfort, as well as the power dynamic between the character and the crowd. Consider exploring themes of invasion of privacy and the desire for connection, no matter how superficial or unsettling it may be.", "output": "did not, wrapped as I was in my fuligin cloak, and I was able to pretend I did not know what they were; they might have been at a party, all a little drunk. They came eagerly yet hesitantly...blah blah blah...Wh-wh-where is she now, my own scopolagna?"}`

I'd be grateful for any suggestions!

**Comment by mzbac** [comment]
You need to preprocess your training data into one sentence and make it an object with the text as a key. For more details, please see: https://github.com/ml-explore/mlx-examples/tree/main/lora#custom-data

**Comment by USMCM1A1** [comment]
> You need to preprocess your training data into one sentence and make it an object with the text as a key. For more details, please see: https://github.com/ml-explore/mlx-examples/tree/main/lora#custom-data

Ahhhh, I didn't realize that was a key--I thought it was a message for the model.  Thanks, reformatted and all good now!
