### ISSUE TITLE
How to convert the mlx model to hugging face pytorch model?

### ISSUE THREAD

**Issue by 592319702** [ml-explore/mlx-examples#382]
I want to fine-tune a model with mlx in my macbook and deploy it on the colab with a pytorch model? How to convert the mlx model to hugging face pytorch model? I just notice there is a convert file to convert the hugging face model to mlx model, how can I convert a mlx model to hugging face model? BTW, If I fine-tune a mlx-model in macbook, how do I deploy it?

**Comment by mzbac** [comment]
There is a great blog post from Andy that should be able to answer all of your questions. https://apeatling.com/articles/part-4-testing-and-interacting-with-your-fine-tuned-llm/
