### ISSUE TITLE
Any way to get the model cached?

### ISSUE THREAD

**Issue by vatsaldin** [ml-explore/mlx-examples#384]
Hello,

I have been trying the Mixtral example shown as a reference .

Each time I run the code, it seems to be downloading the weights.

Is there any way to cache the model weights?

As it takes more than 30-40 minutes after mac restart

Please advise.

Thanks

**Comment by awni** [comment]
I'm not sure exactly what you are referring to. The [Mixtral example](https://github.com/ml-explore/mlx-examples/tree/main/llms/mixtral) has an explicit model download step so you need only do that once. 

If you use `mlx-lm` it will download and store the model weights in a cache indefinitely. Check out [the docs](https://github.com/ml-explore/mlx-examples/blob/main/llms/README.md).
