### ISSUE TITLE
Repetition penalty for LLM inference in MLX LM

### ISSUE THREAD

**Issue by danilopeixoto** [ml-explore/mlx-examples#385]
Implement `repetition_penalty` parameter for LLM inference with `mlx_lm.generate`.

**Paper**

[CTRL: A Conditional Transformer Language Model for Controllable Generation](https://arxiv.org/abs/1909.05858)

**Implementation example**

[huggingface/transformers: logits_process.py](https://github.com/huggingface/transformers/blob/f1cc6157210abd9ea953da097fb704a1dd778638/src/transformers/generation/logits_process.py#L288)

**Possible MLX implementation**

```python
# Generate step

# Apply repetition penalty
score = logits[:, input_ids]
score = mx.where(score < 0, score * repetition_penalty, score / repetition_penalty)
logits[:, input_ids] = score

# Apply temperature sampling
```

**Comment by awni** [comment]
I think it's a good idea to improve the mlx-lm package with a repetition penalty. If anyone is interested in contributing it that would be great!

**Comment by vishal-14069** [comment]
Hi @awni , can I take this up ?

**Comment by awni** [comment]
For sure! Will assign to you.

**Comment by vishal-14069** [comment]
Hi @awni @danilopeixoto I have implemented the repetition penalty in `mlx_lm.utils.generate_step` function. I tested out the repetition penalty implementation with Mistral, and all the tests passed.

I also have a question regarding the accessibility of the repetition penalty implementation, are we gonna implement it as an optional argument in the all the generate function or just in the `mlx_lm.utils.generate_step` function and import it in other files to use it?

Here is the implementation, let me know if everything checks out.

```python

def generate_step(
    prompt: mx.array,
    model: nn.Module,
    temp: float = 0.0,
    repetition_penalty: float = 1.0
) -> Generator[Tuple[mx.array, mx.array], None, None]:
    """
    A generator producing text based on the given prompt from the model.

    Args:
        prompt (mx.array): The input prompt.
        model (nn.Module): The model to use for generation.
        temp (float): The temperature for sampling, if 0 the argmax is used.
        repetition_penalty (float): The penalty factor for repeating tokens.
    Yields:
        Generator[Tuple[mx.array, mx.array]]: A generator producing
        one token and probability per call.
    """

    def sample(logits: mx.array) -> Tuple[mx.array, float]:
        softmax_logits = mx.softmax(logits)

        if temp == 0:
            token = mx.argmax(logits, axis=-1)
        else:
            token = mx.random.categorical(logits * (1 / temp))

        prob = softmax_logits[0, token]
        return token, prob
    
    if repetition_penalty<0 or not isinstance(repetition_penalty,float):
        raise ValueError(f"repetition_penalty must be a non-negative float, got {repetition_penalty}")
    
    y = prompt
    cache = None
    while True:
        logits, cache = model(y[None], cache=cache)
        logits = logits[:, -1, :]
        score= logits[:,y]
        score= mx.where(score<0,score * repetition_penalty,score/repetition_penalty)
        logits[:,y]=score 
        y, prob = sample(logits)
        yield y,prob
```

**Comment by mzbac** [comment]
Maybe I am misunderstood. Does the repetition_penalty only apply to each new token? My understanding is that the repetition_penalty should be applied to the last N number of tokens, but it seems like in the code above, it is only applied to the new token "y" for every generation. 
FYI, I have tried something similar [here](https://github.com/mzbac/mlx-examples/commit/a476d1909ddf7ab89154fdcda2422c9a7ef31241).

**Comment by danilopeixoto** [comment]
@mzbac @vishal-14069 I believe the paper mentions the “last N tokens”. In the context of MLX LM, it appears that `y` represents the “last token”, likely due to the `cache`.

Reference:

> This penalized sampling works by discounting the scores of previously generated tokens.

**Comment by vishal-14069** [comment]
Yes that's correct @mzbac @danilopeixoto. I've corrected the [code](https://github.com/vishal-14069/mlx-examples-fork/blob/2867d6fec760e78d93effe2eb1975030fb26d965/llms/mlx_lm/utils.py#L85-L225). 

I also tested the `generate_step` and `generate` functions with phi 2, and it works fine. If possible please review the corrected code, and let me know if there are any changes/improvements to be made. Thank you:)

**Comment by mzbac** [comment]
@vishal-14069  Would you be able to create a PR for your changes? Maybe that's easier to review.

**Comment by vishal-14069** [comment]
Hi @mzbac, sorry for the late reply. Yes I have created a PR --> #399.  Thanks a lot!
