### ISSUE TITLE
llama lora fune tune using previous adapters weights

### ISSUE THREAD

**Issue by thegodone** [ml-explore/mlx-examples#39]
Can we reuse a previous adapters.npz in a second fine tune process iteration ?

let say I fine tune for 600 iteration during the first fine tune process, I want to restart the fine tune a second time but I want to benefits of the first run adapters.npz weights. Can we add an option to load them in order to go close to the previous fine tune version of model ?

**Comment by awni** [comment]
Done in #16

You can load the previously saved adapter weights using the argument `--resume_adapter_file <path_to_adapters.npz>`
