### ISSUE TITLE
mnist.mnist() doesn't exist?

### ISSUE THREAD

**Issue by abizer** [ml-explore/mlx-examples#4]
the mnist example imports the python mnist library and calls the mnist() member, which doesn't seem to exist:

```bash
~/repos/mlx-examples
venv > python3 -V                                                                             Tue Dec  5 23:36:09 2023
Python 3.11.6

~/repos/mlx-examples
venv > pip install mnist                                                                      Tue Dec  5 23:36:15 2023
Collecting mnist
  Using cached mnist-0.2.2-py2.py3-none-any.whl (3.5 kB)
Collecting numpy (from mnist)
  Using cached numpy-1.26.2-cp311-cp311-macosx_11_0_arm64.whl.metadata (115 kB)
Using cached numpy-1.26.2-cp311-cp311-macosx_11_0_arm64.whl (14.0 MB)
Installing collected packages: numpy, mnist
Successfully installed mnist-0.2.2 numpy-1.26.2

~/repos/mlx-examples
venv > python -c "import mnist; mnist.mnist()"                                                Tue Dec  5 23:36:33 2023
Traceback (most recent call last):
  File "<string>", line 1, in <module>
AttributeError: module 'mnist' has no attribute 'mnist'
```

nor in the [source](https://github.com/datapythonista/mnist/blob/master/mnist/__init__.py)

error is located [here](https://github.com/ml-explore/mlx-examples/blob/0bf5d0e3bc1e51b82cf8083be422dc61dc88455b/mnist/main.py#L60C5-L61)

am i using this wrong/supposed to be importing mnist from another source? replacing the mnist.mnist() call with calls to mnist.train_images/train_labels/test_images/test_labels() seems to work fine

**Comment by marcj** [comment]
I think you refer to the documentation here: https://ml-explore.github.io/mlx/build/html/examples/mlp.html
and its example code

```python
# Load the data
import mnist
train_images, train_labels, test_images, test_labels = map(
    mx.array, mnist.mnist()
)
```

this is a bit misleading indeed. At the very bottom is a link to the full example

> The [full example](https://github.com/ml-explore/mlx-examples/tree/main/mlp) is available in the MLX GitHub repo.

which has a wrong link. A bit unfortunate. The real link is here https://github.com/ml-explore/mlx-examples/tree/main/mnist.

There you can see that there is a file `mnist.py`. This file has indeed the mnist function and this file is also the one that is being imported when you do `import mnist` in its sibling files e.g. `main.py`. mnist.py implements its own mnist file loader, so there is actually no need to install the package `mnist`. I think renaming the file in the examples would avoid this unfortunate mistake in the future.

**Comment by awni** [comment]
The doc link should be fixed, sorry about that.

The `mnist` package is a file in the `mnist/` directory. If you run `python main.py` from inside `mnist/` it should work. Sorry that is indeed a little confusing.
