### ISSUE TITLE
Safety-tuned model for "hello world" quickstart command

### ISSUE THREAD

**Issue by davidandrzej** [ml-explore/mlx-examples#400]
Kudos to the project that I was able to _very_ quickly and easily install/run a basic example following the instructions from the huggingface [mlx-community](https://huggingface.co/mlx-community) page!

However, both that page and the [README](https://github.com/ml-explore/mlx-examples/tree/main/llms) in this repo give the quickstart command: `python -m mlx_lm.generate --model mistralai/Mistral-7B-v0.1 --prompt "hello"`

This command, probably owing to the (intentionally) [non-safety-tuned nature](https://docs.mistral.ai/models/) of Mistral-7B, reproducibly (on my machine) generates a forum post fragment about "cutting" / self-harm, which seems like a non-ideal experience. Even if others don't get this exact generation, various "unfriendly" outputs are probably possible with a non-safety tuned model.

Suggested fix: the quickstart / "hello world" command could choose from any number of safety-tuned models instead of "bare metal" Mistral-7B.

**Comment by davidandrzej** [comment]
[HuggingFaceH4/zephyr-7b-beta](https://huggingface.co/HuggingFaceH4/zephyr-7b-beta) is a fine-tune of `mistralai/Mistral-7B-v0.1`, seems it has not been explicitly RHLF'ed for safety but has at least been chat/instruction-tuned, so for innocuous prompts at least it seems nicer. Other criteria:

- hosted by an org, not an individual account
- OSS license (MIT), no need to specially request weights/etc
- already uses `safetensors`

`python -m mlx_lm.generate --model HuggingFaceH4/zephyr-7b-beta  --prompt "hello"` gives me

```
Prompt: <|user|>
hello</s>
<|assistant|>

Hello, how may I assist you today? Please let me know what you're looking for, and I'll do my best to provide you with helpful information. You can ask me anything related to technology, science, history, and more. I'm here to answer your questions and provide you with accurate and up-to-date information. Let's get started!
==========
```

**Comment by LeonEricsson** [comment]
[zephyr](https://huggingface.co/HuggingFaceH4/zephyr-7b-beta), [open-hermes-mistral](https://huggingface.co/teknium/OpenHermes-2.5-Mistral-7B) or just [mistral-instruct](https://huggingface.co/mistralai/Mistral-7B-Instruct-v0.2)
