### ISSUE TITLE
How can I specific branch for hf model?

### ISSUE THREAD

**Issue by katopz** [ml-explore/mlx-examples#406]
Some model has `model.safetensors` in PR  [refs/pr/7](https://huggingface.co/microsoft/trocr-base-printed/tree/refs%2Fpr%2F7) and I can't find a way to use it via `--hf-path`. 

Any hint? I manually download atm for workaround.

**Comment by mzbac** [comment]
This requires an additional parameter to be passed down to `snapshot_download` from `huggingface_hub`. It feels like this is an edge case. Maybe it would be better to directly use the Hugging Face Hub CLI instead?

https://huggingface.co/docs/huggingface_hub
```
huggingface-cli download microsoft/trocr-base-printed  --revision=refs/pr/7
```

**Comment by awni** [comment]
Thanks @mzbac , that seems like a good compromise. We can add a little doc about this if it comes up often enough.

FWIW `snapshot_download` takes a `revision` kwarg... that could also be an option if this comes up often enough.

Closing this for now!

**Comment by RonanKMcGovern** [comment]
Yeah, would be nice if the convert feature allowed for specifying a branch directly. For new models, it's handy to just have a separate branch for mlx, awq etc.
