### ISSUE TITLE
max_seq_length

### ISSUE THREAD

**Issue by ivanfioravanti** [ml-explore/mlx-examples#407]
max_seq_length is available in TrainingArgs of tuner. It would be great being able to pass it as parameter to lora.py to change it during training.

**Comment by ivanfioravanti** [comment]
Merged!

**Comment by ivanfioravanti** [comment]
@awni would you like me to update the old lora sample based on wikisql?

**Comment by awni** [comment]
No that's not necessary.. I think it's ok for that example to stay without new features, mostly there for instructive purposes. The mlx-lm LoRA is the one that people should use if they are looking for something with more bells and whistles.
