### ISSUE TITLE
Integrate RWKV V5 into MLx's Model Roster

### ISSUE THREAD

**Issue by umuthopeyildirim** [ml-explore/mlx-examples#422]
I'm interested in integrating [RWKV v5](https://github.com/BlinkDL/RWKV-LM) with MLX. Notably, RWKV uses [CUDA as its kernel](https://github.com/BlinkDL/RWKV-LM/tree/main/RWKV-v5/cuda). I want to work on this to learn and any guidance on this process would be awesome.

**Comment by umuthopeyildirim** [comment]
This [version](https://github.com/BlinkDL/ChatRWKV/blob/main/RWKV_v5_demo.py) doesn't require CUDA. I'll start by porting this over and check how mlx manages it.

**Comment by awni** [comment]
That sounds awesome, let us know how it goes!

**Comment by p-i-** [comment]
Bump! Any chance of rwkv6 (Finch)?
