### ISSUE TITLE
Make the mlx-lm olmo model lazy loaded

### ISSUE THREAD

**Issue by mzbac** [ml-explore/mlx-examples#423]
Currently, the Olmo will be imported from https://github.com/ml-explore/mlx-examples/blob/main/llms/mlx_lm/utils.py#L15. So, the import hf_olmo will always throw an exception regardless of whether the user chooses to load the Olmo model or not. As a temporary workaround, maybe we can move loading hf_olmo into the model's init function. However, for a long-term solution, we may need a way to lazily load the models.

**Comment by awni** [comment]
Nice! And yea I can do the lazy loading, I actually started that at one point so I have an implementation in mind already.
