### ISSUE TITLE
Help With My LlaMa implementation based on the LLM Inference Example

### ISSUE THREAD

**Issue by NateAGeek** [ml-explore/mlx-examples#428]
Hello,

I was following the LLM documentation example, and I wanted to start using the external weights from llama-7b. I know that it works with my computer based on the llm example. However, when I start to use my custom code, that I believe is very similar to the example code. I get a malloc issue. 

```
libc++abi: terminating due to uncaught exception of type std::runtime_error: [malloc_or_wait] Unable to allocate 16384 bytes.
```
I stepped through the code and it seems to crash after 16 layers. But with the llm example here, it seems to generate tokens just fine with llama-7b.

I know I am asking the community to help optimize code, and this is on the borderline of if this is really related to the mlx-examples. However, I have been trying to scratch my head on what is causing my implementation to eat up more memory than the example.

I am using a M2 air with 16GB of ram. 

Thank you for your time,
Nate

Repo link: https://github.com/NateAGeek/MLX-LlaMa-Exercise

**Comment by awni** [comment]
That error should typically not be triggered except in pretty extreme memory requests or bugs.  What should happen instead if you use too much memory is that machine should swap and it will just be really really slow.

Are you using the same MLX version to run both scripts? 

Could you share more details on what you did to run the version that works? Which LLM example? Which model? etc.

**Comment by NateAGeek** [comment]
@awni, First and foremost, I'd like to express my sincere gratitude for the effort and expertise you bring to the issue queue. Your swift responses and dedication significantly contribute to the growth of the MLX community.

Regarding my model, I believe I've identified the root causes of the issues I encountered. The primary challenge was related to converting the keys from the original Llama-7B format to the NPZ format, ensuring the mapping was correctly done (from their keys to my model's keys). The initial problem appeared to be an incorrect loading of values into my model due to the generated keys. This lead to the "malloc_or_wait" issue above. I can investigate deeper what might have caused it, but I have a gut feeling it might have just been due to some mathematical operation on an improperly loaded set of tensors (mx.arrays). 

However, after resolving a memory allocation error, I encountered a new issue: the output from my model was garbled. Upon investigation, I discovered the mistake was due to an incorrect assignment of one of the output weights in my model. I'm not sure what the default approach is to loading weights, and what are weights by default initialized to (0s or rands). But I think this could lead to some confusion in the future with people trying to test and use other models in the MLX framework.

I acknowledge that this issue might stem from both subtle complexities and my own beginner mistakes. However, I believe it could be beneficial to implement printable warnings during the use of the load_weights method, maybe some control of the verbosity with a param. This would help users identify keys that have not been successfully loaded into their models or if default values have been used. If this suggestion interests you, I would appreciate guidance on your expectations and am willing to dedicate time to enhancing this method with a PR. Otherwise, if it is something that is already on the todo or not a priority feel free to close this issue and I hope it guides some people in the right direction.

Again, thank you very much for your efforts and even taking the time to respond to my vague like error.

**Comment by awni** [comment]
> This would help users identify keys that have not been successfully loaded into their models or if default values have been used.

[`Module.load_weights`](https://ml-explore.github.io/mlx/build/html/python/nn/_autosummary/mlx.nn.Module.load_weights.html#mlx.nn.Module.load_weights) will throw errors by default if you give it unexpected parameters or don't supply all of the parameters it expects. You can see in the docs `strict=True` by default.

I will close this issue since it does not appear to be specific to any one thing. For more general help getting models I encourage you to open a discussion.

**Comment by NateAGeek** [comment]
I wanted to share that you are very much so correct, and I was using mlx-0.0.6... Very old version, and the current version mlx-0.2.0 did have more verbosity with loading the models. Thank you again for the time, and yes I realize now a "discussion" was a good place to resolve this.
