### ISSUE TITLE
Support bfloat16 for quantization convert

### ISSUE THREAD

**Issue by mzbac** [ml-explore/mlx-examples#435]
Currently, we convert the weight to float16 during quantization. However, since we have done significant performance improvements with bfloat16 quantization, I am wondering if we can also support for bfloat16 during quantization.

https://github.com/ml-explore/mlx-examples/blob/main/llms/mlx_lm/convert.py#L102

https://github.com/ml-explore/mlx/pull/663

**Comment by awni** [comment]
I'm not opposed to supporting bfloat but I would not want to make it the default:

- float16 is still considerably faster given it has native support. The benchmarks in #633 don't tell the whole story. I see 42 TPS with fp16 vs 32 with bfloat16.
- the precision loss from bfloat16 -> float16 is nothing compared to float16 -> 4-bit quantization. So I think the impact of using bfloat is minor from a precision standpoint. Although maybe you have some case in mind that would be easier in bfloat16?

**Comment by mzbac** [comment]
I have tried the build mlx from mlx last master branch, but I didn't notice significant performance improvement as stated in #663. I was thinking that it might be because we quantized the model in float16. If that's not the case, I am happy to close this issue.

**Comment by awni** [comment]
> I have tried the build mlx from mlx last master branch, but I didn't notice significant performance improvement as stated in #663. I was thinking that it might be because we quantized the model in float16. If that's not the case, I am happy to close this issue.

Not sure I follow your comment. But just in case, #663 really only sped up bfloat16 quantized models of which there are not very many. I believe [this one](https://huggingface.co/mlx-community/Mistral-7B-Instruct-v0.2-4-bit) is one of the few examples. There should be no change for float16 and float32 quantized models.

**Comment by awni** [comment]
Can you share the command you ran? I didn't realize there was a scan in the LLM code..

**Comment by awni** [comment]
It does look like our [bloat16 scans are commented](https://github.com/ml-explore/mlx/blob/main/mlx/backend/metal/kernels/scan.metal#L454).. not sure why that is.

**Comment by mzbac** [comment]
> Can you share the command you ran? I didn't realize there was a scan in the LLM code..
```
python -m mlx_lm.generate --model <path_to_bfloat16_quant_model>
```
 happened to `mlx-community/Mistral-7B-Instruct-v0.2-4bit-mlx` as well

**Comment by awni** [comment]
Oh I see, that is the `cumsum` from the topk sampling.

**Comment by awni** [comment]
@angeloskath or @jagrit06 do you know why bfloat is not supported in the scans? Is that because there are simd reductions for bfloat?

**Comment by jagrit06** [comment]
@angeloskath might have the best insight for scans in particular but I think it came down to exclusive and inclusive reduction primitives for the scans that weren't there for bfloat - I'm not sure if we ended up making the same workarounds available for it as we did for other sims reductions

**Comment by awni** [comment]
This is enabled now.
