### ISSUE TITLE
Weird Output from llama-2-70b-chat

### ISSUE THREAD

**Issue by muchi674** [ml-explore/mlx-examples#437]
Hi,

On my machine: M2 Ultra (60 GPU cores, 192GB memory), I did the following:
1. downloaded llama-2-7b-chat, llama-2-13b-chat, and llama-2-70b-chat models from Meta
2. successfully ran the conversion script (llms/llama/convert.py) against all of them
3. successfully interacted with llama-2-7b-chat and llama-2-13b-chat using llms/llama/llama.py

However, I was getting weird output from llama-2-70b-chat while following same steps I took to get the two smaller models running. Attached below is a screenshot of what I am seeing.

<img width="702" alt="Screenshot 2024-02-13 at 4 19 29 PM" src="https://github.com/ml-explore/mlx-examples/assets/126644960/482c310c-b2ed-4a29-8a95-bdddb19efb5c">

This isn't normal, right? Am I missing anything?

Thank you so much for your time.

**Comment by awni** [comment]
Hmm, maybe good to try with mlx_lm: https://github.com/ml-explore/mlx-examples/blob/main/llms/README.md

Our original llama implementation was mostly tested with llama v1 7B so there could be some config that is off for the larger llama 2 models.

**Comment by muchi674** [comment]
Thank you @awni for the suggestion,
I will try the specified library out and keep you posted!

**Comment by muchi674** [comment]
> Hmm, maybe good to try with mlx_lm: https://github.com/ml-explore/mlx-examples/blob/main/llms/README.md
> 
> Our original llama implementation was mostly tested with llama v1 7B so there could be some config that is off for the larger llama 2 models.

Hi @awni ,

Sorry for the wait. I tried running llama-2-70b-chat today (with weights downloaded from https://huggingface.co/meta-llama/Llama-2-7b-chat-hf) with mlx_lm library and it worked. Nevertheless, the latency is quite concerning. Please refer to the screenshot attached below. In comparison, with llama.cpp, I am getting 11.87 t/s for prompt evaluation and 4.78 t/s for generation. Given the strength of mlx, I would guess that it would at least have comparable speed to llama.cpp?

<img width="751" alt="Screenshot 2024-02-14 at 6 07 59 PM" src="https://github.com/ml-explore/mlx-examples/assets/126644960/31a16847-5426-4ff6-80bc-bdc53f437970">

I will continue to investigate the bottleneck, just following up with you and documenting the results.

Thanks again for your time and assistance!

**Comment by awni** [comment]
- Just to be clear did you try the 7B or the 70B model?
- What machine are you running on? If it does not have a lot of RAM you may need to use a quantized model to avoid swapping. Usually we are slower than llama.cpp but not by that much.

**Comment by muchi674** [comment]
> * Just to be clear did you try the 7B or the 70B model?
> * What machine are you running on? If it does not have a lot of RAM you may need to use a quantized model to avoid swapping. Usually we are slower than llama.cpp but not by nearly that much.

Ah,
So sorry for the confusion, @awni , I accidentally pasted the link to the 7B hf model instead of the 70b one.

To answer your questions:
- I tried the 70b-chat model
- as mentioned in the first comment, I am using M2 Ultra with 60 GPU cores and 192GB memory. I believe this should be plenty to fit the original fp16 model? According to my experiment, I do not see the process using swap memory. Please refer to the screenshots attached below

This is my machine's swap memory usage **_before_** I started the process (btw, pretty confused why the machine is using swap when there is plenty of physical memory available)
<img width="533" alt="Screenshot 2024-02-14 at 10 36 50 PM" src="https://github.com/ml-explore/mlx-examples/assets/126644960/8e917e6e-1e8c-4674-9134-16125b37f8b6">

This is how I am running the 70b-chat model and the observed memory consumption (according to htop)
<img width="1246" alt="Screenshot 2024-02-14 at 10 34 20 PM" src="https://github.com/ml-explore/mlx-examples/assets/126644960/5044c368-af28-4737-acb8-e3a00ab41f13">

This is when the process finishes, which shows the latency metrics as well as memory usage in normal times
<img width="1231" alt="Screenshot 2024-02-14 at 10 35 47 PM" src="https://github.com/ml-explore/mlx-examples/assets/126644960/d7a1fabc-69ac-4fa4-8e3e-037c1d56a94c">

Thank you again for your time, and I will keep on digging!

**Comment by muchi674** [comment]
Hi @awni ,

For your reference, I have recorded a video that shows output by vmstat when running the model.
https://drive.google.com/file/d/1ze65_YsETJ5pS7Mz_YvVH4stMDNhkdI3/view?usp=sharing

From there, you could see that:
- page-ins spiked for a brief period when the process first started, but if I am correct, this is just the model being loaded into memory
- after that, page in/out & swap in/out were mostly near 0

I believe the observations above indicate that swapping isn't an issue here.

Thank you again for your time.

**Comment by awni** [comment]
Btw, are you using a quantized model or a 16-bit precision model? I would strongly recommend using a quantized model for the 70B size, it will be much much faster. E.g. https://huggingface.co/mlx-community/CodeLlama-70b-Instruct-hf-4bit-MLX

You can quantize models using `mlx_lm.convert`. Docs [here](https://github.com/ml-explore/mlx-examples/blob/main/llms/README.md).

Finally, everything should be a lot faster now thanks to faster quantized kernels and fused attention. Hence I will close this issue. If you have any more benchmarks or issues, you can share them here and we can always reopen.
