### ISSUE TITLE
[Question] How to stop generate properly?

### ISSUE THREAD

**Issue by katopz** [ml-explore/mlx-examples#448]
My train data

```
{"text": "Q: Who's katopz?\nA: He's Rustaceans."}
{"text": "Q: What's katopz twitter account?\nA: https://twitter.com/katopz"}
```
My LoRA output from `Qwen/Qwen1.5-7B`
```
==========
Prompt: Q: Who's katopz?
A: 
He's Rustaceans.! https://twitter.com/katopz! He's also the boss of me! https://twitter.com/katopz! https://twitter.com/katopz! https://twitter.com/katopz
==========
```
My LoRA output from `SeaLLMs/SeaLLM-7B-v2`

```
==========
Prompt: Q: Who's katopz?
A: 
katopz is Rustaceans.?.2.[.9. /******/ /******/ */ /******/ Ấn Q katopz. /******/ /******/ */ /******/ /******/ */ /******/ /******/ Todsapz katopz. /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/
==========
```

Expected
```
==========
Prompt: Q: Who's katopz?
A: 
He's Rustaceans.
==========
```

The question is: How can I improve this? Is this a...
1. base model problems 
2. train data 
3. prompt template
4. `mlx_lm.lora` penalty (or stopper?)

Thanks for any hint.

**Comment by mzbac** [comment]
Looks like the model didn't really learn the pattern. Either you fine-tuned a chat mode with the wrong prompt, or you may need to fine-tune it more iterations.

**Comment by katopz** [comment]
Cool, Thanks! in case it's not mlx related I will close it for now.
