### ISSUE TITLE
Fused model seems broken

### ISSUE THREAD

**Issue by kohlerm** [ml-explore/mlx-examples#460]
I fine-tuned a Mistral 7B Instruct model following the Q(LORA) example:
`python convert.py --hf-path mistralai/Mistral-7B-Instruct-v0.2 -q`

Then  trained (with my own data) 
`python lora.py --model mlx_model/ --train --batch-size 1 --lora-layers 4`

I have got a test question:
`python lora.py --model mlx_model/ --adapter-file adapters.npz --max-tokens 250 --prompt "Where does XYZ live?" --temp 0.1`

I get the correct answer from the training data. 
then I tried to fuse:
`python fuse.py --model mlx_model/ --adapter-file adapters.npz`

and run the fused model (is that correct?)
`python lora.py --model lora_fused_model/ --max-tokens 250 --prompt "Where does XYZ live?" --temp 0.1''

I get only garbage and it seems to endlessly repeat the same word. 

Any hints what went wrong?

**Comment by awni** [comment]
Closing. Let me know if this is still an issue.
