### ISSUE TITLE
Support the HF format clip example

### ISSUE THREAD

**Issue by mzbac** [ml-explore/mlx-examples#463]
While attempting to port the llava model to MLX, I noticed that in the current clip example, it requires converting the model weights which makes it difficult to reuse with llava models (it will require conversion for llava model as well). Since most popular llava model weights in HF are in hf format, I wonder if it is worth creating a clip example that uses hf format directly and provides necessary APIs (output hidden state) that can be easier to use as a vision tower for integrating with similar Llava models.

**Comment by awni** [comment]
👍  I support updating our CLIP example to do that
