### ISSUE TITLE
QUESTION FOR HELP: Parametric quantities for quantitative models

### ISSUE THREAD

**Issue by madroidmaq** [ml-explore/mlx-examples#473]
When I tried to fine-tune the model using `QLoRA`, I found that there is a significant reduction in the number of parameters in the quantized model. For example, when I fine-tuned the model based on the `Qwen/Qwen1.5-1.8B-Chat` model by using `LoRA` and `QLoRA`, the corresponding parameter counts are printed as follows:

`LoRA` (unquantized) mode log printing：
```
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
Total parameters 1837.877M
Trainable parameters 1.049M
Trainable parameters: 0.06% (1.049M/1837.877M)
```

`QLoRA` mode log printing：
```
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
Total parameters 550.808M
Trainable parameters 1.049M
Trainable parameters: 0.19% (1.049M/550.808M)
```

When I use `microsoft/phi-2`, I also have a common problem: the number of parameters decreases significantly after quantization. Based on the understanding of [QLoRA: Efficient Finetuning of Quantized LLMs](https://arxiv.org/abs/2305.14314)  paper, quantization is just a change in the way of representing the parameter value, for example, float32 becomes int4, but this link does not reduce the number of parameters, only the unit of representation of the value is changed.

In addition to this, I have seen similar issues on Huggingface, for example the `Mistral-7B` model `int4` quantization shows a parameter count of `1.24B`.
<img width="1320" alt="image" src="https://github.com/ml-explore/mlx-examples/assets/6247142/552edde8-8c1c-45a7-80ae-838407de5804">

I'm not sure if I'm overlooking some points of knowledge that are causing a misunderstanding of this section? Or is there something wrong with the current presentation of parametric quantities?

**Comment by awni** [comment]
Hmm, this is really a bug in how we compute the number of parameters for quantized layers. We just compute the size of the weight which for a quantized model will be much smaller..

**Comment by awni** [comment]
That said, there should be no issue fine tuning that model. It's just the parameter count that's being printed which is off.

**Comment by madroidmaq** [comment]
@awni Thank you very much for your answer.
