### ISSUE TITLE
mlx_lm.server  OpenAI compatible endpoints

### ISSUE THREAD

**Issue by namp** [ml-explore/mlx-examples#478]
Currently mlx_lm.server only implements a single endpoint: /v1/chat/completions 

It is essential to add more OpenAI compatible endpoints similarly to the implementation of the llama_cpp.server:

https://github.com/abetlen/llama-cpp-python/tree/main/llama_cpp/server

**Comment by mzbac** [comment]
Just out of curiosity, what is the other endpoint you are more interested in getting support from mlx-lm?

**Comment by namp** [comment]
v1/completions

Thanks!
