### ISSUE TITLE
Error loading models from mlx-community on HF

### ISSUE THREAD

**Issue by Harrolee** [ml-explore/mlx-examples#480]
Hey!

## Problem

mlx.loader is looking for safetensor files. Models that have been converted to the mlx format use the .npz format.

## Steps to reproduce

1. I downloaded [mlx-community/Llama-2-7b-chat-4-bit](https://huggingface.co/mlx-community/Llama-2-7b-chat-4-bit). 
2. I tried to run the example mlx-example/lora/lora.py script with it
3. I got this error:

```
Loading pretrained model
Traceback (most recent call last):
  File "/Users/lee/projects/mlx-examples/lora/lora.py", line 321, in <module>
    model, tokenizer, _ = lora_utils.load(args.model)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/lee/projects/mlx-examples/lora/utils.py", line 154, in load
    raise FileNotFoundError("No safetensors found in {}".format(model_path))
FileNotFoundError: No safetensors found in ../Llama-2-7b-chat-mlx
```

I also tried using the model on huggingface, but got the same error.

```
python lora.py --model mlx-community/Llama-2-7b-chat-4-bit --data data/poem-analysis --train --batch-size 1 --lora-layers 4
```

I get the same error using the mlx pypi package:

```
python -m mlx_lm.lora \
    --model ../Llama-2-7b-chat-mlx  \
    --train \
    --data data/poem-analysis \
    --iters 600
```

**Comment by Harrolee** [comment]
Oh, it looks like some of the models in the HF community have safetensor files.
[bagel-dpo, for example](https://huggingface.co/mlx-community/bagel-dpo-34b-v0.2-4bit-mlx/tree/main

<img width="1012" alt="image" src="https://github.com/ml-explore/mlx-examples/assets/35541778/9eb6dc97-3439-4fa6-85a9-2d65d5f0cdc1">
)

I guess I just got unlucky? Evidently, the npz format is not required for using mlx.

**Comment by mzbac** [comment]
Yeah, the npz model weight was in the old format that mlx-example initially supported. Now it has been adapted to SafeTensor format as preferred by the community. If you are looking for a quant model, you can either quantize it yourself using the `mlx_lm.convert` command or find the model in the mlx-community space that has SafeTensor model weights.

**Comment by Harrolee** [comment]
Thanks @mzbac! I opened a [PR](https://huggingface.co/mlx-community/Llama-2-7b-chat-4-bit/discussions/5) on the HF model card to keep other folks who are looking for a 4bit Llama2 Chat model from getting as confused as I was.
