### ISSUE TITLE
Command buffer execution failed: Insufficient Memory While tying to fine tune using lora.py

### ISSUE THREAD

**Issue by abhishek-ch** [ml-explore/mlx-examples#481]
While trying to fine-tune, I am getting Insufficient Memoy on M2-Ultra 64GB RAM
Is it because of token size ie more than 2048 or there is some configuration to control the memory consumption?

Error Stack
```
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
Total parameters 1242.560M
Trainable parameters 0.213M
Loading datasets
Training
[WARNING] Some sequences are longer than 2048 tokens. Consider pre-splitting your data to save memory.
[WARNING] Some sequences are longer than 2048 tokens. Consider pre-splitting your data to save memory.
libc++abi: terminating due to uncaught exception of type std::runtime_error: [METAL] Command buffer execution failed: Insufficient Memory (00000008:kIOGPUCommandBufferCallbackErrorOutOfMemory)
[1]    31148 abort      python lora.py --model  --train --iters 500 --max-tokens 100 --batch-size 2
```

**Comment by saikiranpennam** [comment]
Hi, I am facing the same situation for some of the quantized models I used like mistral and phi-2, and how to overcome this issue? My current rig is M1Pro with 16GB RAM. Any suggestions are highly appreciated.

**Comment by awni** [comment]
There is a whole section in the documentation on how to reduce memory use for LoRA fine-tuning: https://github.com/ml-explore/mlx-examples/tree/main/lora#Memory-Issues

Hope that helps!

**Comment by saikiranpennam** [comment]
I have quantized the model and they are saved locally, but now in the docs it was mentioned as works for 'hf repo' or a 'local path to a converted model'. But when I provide the path, it says not a repo. How do I pass the locally saved quantized model? As the folder by default created mlx-model and stored .safetensors and .json files

**Comment by awni** [comment]
To fine tune using a locally quantized model you would pass the path to the model.

So if you saved the model in `/path/model` pass `--model /path/model`. There should be `.safetensors` and `config.json` etc in `/path/model`.

**Comment by saikiranpennam** [comment]
I had to manually create a folder under `mlx-model` consisting of the `.safetensors` and `config.json` and pass the path. It works now. Are there any best practices for visualizing these evaluation metrics that run via the command line?

**Comment by awni** [comment]
Some people use wand db. I would recommend you open a discussion as we are getting a bit off topic from this issue.
