### ISSUE TITLE
mlx_lm.lora need an option to set --eos-token

### ISSUE THREAD

**Issue by southkorea2013** [ml-explore/mlx-examples#488]
Hi,

Please help to add an option "-eos-token" to run a LORA fine-tuned Qwen llm with mlx_lm.lora. 

Thanks,
Nan

**Comment by southkorea2013** [comment]
If I used the fused model with mlx_lm.generate, I found it cannot answer questions with the training datasets, but it works with mlx_lm.lora with the adapters.npz. Thanks.

**Comment by mzbac** [comment]
> If I used the fused model with mlx_lm.generate, I found it cannot answer questions with the training datasets, but it works with mlx_lm.lora with the adapters.npz. Thanks. Are there any options I need to modify for running the mlx_lm.fuse ?

Yeah, a fused model will experience performance degradation due to the quant-dequant operation. Therefore, making the generate command to be able to load the base model and adapters would be a better solution.

**Comment by southkorea2013** [comment]
> > If I used the fused model with mlx_lm.generate, I found it cannot answer questions with the training datasets, but it works with mlx_lm.lora with the adapters.npz. Thanks. Are there any options I need to modify for running the mlx_lm.fuse ?
> 
> Yeah, a fused model will experience performance degradation due to the quant-dequant operation. Therefore, making the generate command to be able to load the base model and adapters would be a better solution.

Thanks.

**Comment by Solido** [comment]
Hi!
Is there a benchmark to evaluate the perplexity degradation for quantization?
