### ISSUE TITLE
How to generate an answer without pre-defined length of tokens?

### ISSUE THREAD

**Issue by 592319702** [ml-explore/mlx-examples#499]
I notice there is a parameter `--num-tokens` in lora.py. If I want to generate an answer, the length of the answer is always depend on the question rather than a fixed token length. How can I generate an answer without pre-defined length of tokens?

**Comment by awni** [comment]
Right so the parameter is actually named `--max-tokens` now. This is just an upper limit on the maximum number of tokens. Usually the model stops when it encounters an end of sentence token before it hits the upper limit.

**Comment by 592319702** [comment]
Thanks a lot.
