### ISSUE TITLE
Starcoder2 Support

### ISSUE THREAD

**Issue by lazarust** [ml-explore/mlx-examples#500]
It would be nice if we could support `starcoder2`. 

Expected Behavior:

`python -m mlx_lm.generate --model bigcode/starcoder2-3b --prompt "Write a quick sort in C++"`

**Comment by awni** [comment]
Happy to accept a contribution for that!

**Comment by lazarust** [comment]
@awni I'll take a stab at it and see what I can do! Could you point me to a good starting point?

**Comment by awni** [comment]
Of course! 

So it's relatively simple, you add the model file to this directory: https://github.com/ml-explore/mlx-examples/tree/main/llms/mlx_lm/models 

You can see other examples in there, I recommend starting from one of the models that is pretty similar to starcoder2

Make sure the name of the model file is the same as the `model_type` in the config (`starcoder2`) (https://huggingface.co/bigcode/starcoder2-7b/blob/main/config.json#L17)

If you want to add LoRA support you can edit this [section of the code](https://github.com/ml-explore/mlx-examples/blob/main/llms/mlx_lm/tuner/utils.py#L27-L60) as needed

**Comment by awni** [comment]
>  Just a heads-up the model is a FIM type

What's FIM? And does the HF tokenizer template handle that or do we need to do something special?

**Comment by lazarust** [comment]
@awni Could you also assign me to this issue? I can't seem to do it

**Comment by Vaibhavs10** [comment]
> What's FIM? And does the HF tokenizer template handle that or do we need to do something special?

FIM - Fill in the Middle. Nothing special. Just that it is not chat-tuned.

https://huggingface.co/bigcode/starcoder2-15b#running-the-model-on-cpugpumulti-gpu

**Comment by sugatoray** [comment]
FIM: Fill in the Middle [arxiv-paper](https://arxiv.org/abs/2207.14255)
