### ISSUE TITLE
Suggestion for a real world example

### ISSUE THREAD

**Issue by jrp2014** [ml-explore/mlx-examples#525]
Most of the apps that claim to add descriptions and keywords to images are poor. Not sure what models they use. 

The examples in this repo work well on small images, but it'd be great to build an end-to-end example that worked with 50-100Mpx images and, for bonus points, embedded the caption and keywords into the image (although that would probably need an Exif library, so could be left as an exercise for the reader).

**Comment by awni** [comment]
That would be super cool it it’s somewhat beyond the scope of the repo. Would love to see a community lead project that does that though!
