### ISSUE TITLE
can not run gguf

### ISSUE THREAD

**Issue by taozhiyuai** [ml-explore/mlx-examples#529]
<img width="949" alt="截屏2024-03-04 15 12 28" src="https://github.com/ml-explore/mlx-examples/assets/146583103/a2f93c2a-8086-421e-9975-23c86483fcf1">

thebloke openchat guf ,q4 and q5, report err 

same err for openchat-3.5-0106-fp16.gguf

anyone can help?

**Comment by taozhiyuai** [comment]
<img width="831" alt="截屏2024-03-04 15 19 12" src="https://github.com/ml-explore/mlx-examples/assets/146583103/6dc45fb6-ea30-4711-a769-7aefdb225950">

**Comment by taozhiyuai** [comment]
<img width="697" alt="截屏2024-03-04 21 13 05" src="https://github.com/ml-explore/mlx-examples/assets/146583103/52364e31-4418-4b99-84bc-cfbaab5dbc55">

q4_0 and Q8_0  both report ERR

**Comment by awni** [comment]
Those models are not supported in that example.

You can check out the example to see which models have been [tested and should run](https://github.com/ml-explore/mlx-examples/tree/main/llms/gguf_llm#run).

I don't think we will add arbitrary models to that example, but you are welcome to fork it and update it to work with other models.
