### ISSUE TITLE
inference speed of mlx is slower than LM Studio

### ISSUE THREAD

**Issue by taozhiyuai** [ml-explore/mlx-examples#535]
inference speed of mlx is slower than LM Studio.

anyone has the same experience?

**Comment by mzbac** [comment]
Yeah, MLX is not specifically for LLM only, so it's a bit slower than dedicated libraries like llama.cpp, which I believe is used by LM Studio under the hood.

**Comment by angeloskath** [comment]
I would also add that we are getting faster every week so keep checking 😁

**Comment by taozhiyuai** [comment]
> I would also add that we are getting faster every week so keep checking 😁

yes, I will. be better.
