### ISSUE TITLE
AttributeError: module 'mlx.core.metal' has no attribute 'get_peak_memory'

### ISSUE THREAD

**Issue by USMCM1A1** [ml-explore/mlx-examples#554]
I updated my mlx-examples repo today and now when I try and use python txt2image.py I get the error:
`module 'mlx.core.metal' has no attribute 'get_peak_memory'`

**Comment by awni** [comment]
Try updating MLX as well! `pip install -U mlx`.

**Comment by USMCM1A1** [comment]
Requirement already satisfied: mlx in /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages (0.6.0)

**Comment by awni** [comment]
You still see the issue with 0.6?  Can you do:

```
python -c "import mlx.core as mx; print(mx.__version__)"
```

It's possible your pip and python are diverged.. you have to make sure you are picking up the right version of mlx when you run the examples.

**Comment by USMCM1A1** [comment]
0.0.9
Not sure what that means exactly :)

**Comment by awni** [comment]
So pip has to use the right python otherwise it will install packages in the wrong place. A way to make sure that happens is:

`python -m pip install -U mlx`

That should give you the right mlx for whichever `python` you get when you do `python ...`.

**Comment by USMCM1A1** [comment]
Yes, thank you!
