### ISSUE TITLE
llama.py failed to generate on large mode.

### ISSUE THREAD

**Issue by Haixing-Hu** [ml-explore/mlx-examples#56]
For example, the program reports the following error on llama-2-13b-chat:

```
python3 llama.py llama-2-13b-chat.npz tokenizer.model 'Hello, who are you?'
[INFO] Loading model from disk.
Press enter to start generation
------
Traceback (most recent call last):
  File "/Users/starfish/working/llm/mlx-examples/llama/llama.py", line 306, in <module>
    generate(args)
  File "/Users/starfish/working/llm/mlx-examples/llama/llama.py", line 180, in generate
    for token in model.generate(x, args.temp):
  File "/Users/starfish/working/llm/mlx-examples/llama/llama.py", line 125, in generate
    x, c = l(x, mask=mask)
           ^^^^^^^^^^^^^^^
  File "/Users/starfish/working/llm/mlx-examples/llama/llama.py", line 77, in __call__
    y = self.norm1(x)
        ^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/mlx/nn/layers/normalization.py", line 85, in __call__
    return self.weight * x * n
           ~~~~~~~~~~~~^~~
ValueError: Shapes (5120) and (1,7,2560) cannot be broadcast.
```

 And the program reports the following error on llama-2-70b:

```shell
python3 llama.py llama-2-70b.npz tokenizer.model 'Hello, who are you?'
[INFO] Loading model from disk.
Press enter to start generation
------
Traceback (most recent call last):
  File "/Users/starfish/working/llm/mlx-examples/llama/llama.py", line 306, in <module>
    generate(args)
  File "/Users/starfish/working/llm/mlx-examples/llama/llama.py", line 180, in generate
    for token in model.generate(x, args.temp):
  File "/Users/starfish/working/llm/mlx-examples/llama/llama.py", line 125, in generate
    x, c = l(x, mask=mask)
           ^^^^^^^^^^^^^^^
  File "/Users/starfish/working/llm/mlx-examples/llama/llama.py", line 77, in __call__
    y = self.norm1(x)
        ^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/mlx/nn/layers/normalization.py", line 85, in __call__
    return self.weight * x * n
           ~~~~~~~~~~~~^~~
ValueError: Shapes (8192) and (1,7,1024) cannot be broadcast.
```

**Comment by awni** [comment]
I'm confused by the shape of `x` in the stack traces.  And why does `x` have dimension `2560`, that should also have dimension `5120`. Could you point me to the weights you are using if they are accessible? I could try to run it to see if I can get the same issue.

**Comment by Haixing-Hu** [comment]
> I'm confused by the shape of `x` in the stack traces. And why does `x` have dimension `2560`, that should also have dimension `5120`. Could you point me to the weights you are using if they are accessible? I could try to run it to see if I can get the same issue.

I try to load the model converted from the llama-2-16b-chat and llama-2-70b, which is directly download from the llama repository, and is converted by the `convert.py` (modified to use the CPU device). And I got the above error reports.

**Comment by awni** [comment]
You mean this model right? https://huggingface.co/meta-llama/Llama-2-13b-chat/tree/main

**Comment by Haixing-Hu** [comment]
> You mean this model right? https://huggingface.co/meta-llama/Llama-2-13b-chat/tree/main
> 
> 
> 
> 

yes

**Comment by awni** [comment]
Just curious, how did you do the weight conversion? Since they model is split into multiple files, some of the code needs to change.

**Comment by Haixing-Hu** [comment]
> Just curious, how did you do the weight conversion? Since the model is split into multiple files, some of the code needs to change.

I use the `convert.py` and use `consolidated.00.pth` as the first argument. The command is as follows:

```shell
python3 ./convert.py ../../../llm/llama/llama-2-13b-chat/consolidated.00.pth llama-2-13b-chat
```

 I don't know the `convert.py` cannot handle multiple files correctly. It seems that this is the cause of the error.

**Comment by awni** [comment]
Ah of course, that is the problem. The 13B and 70B models are sharded so we need to update the `convert.py` to unshard them. I am working on that now, and will link the PR when it is ready.

**Comment by Haixing-Hu** [comment]
> Ah of course, that is the problem. The 13B and 70B models are sharded so we need to update the `convert.py` to unshard them. I am working on that now, and will link the PR when it is ready.

Thank you very much !

**Comment by LeaveNhA** [comment]
I'm literally stuck at this point. I'm just waiting for updated convert functionality. But, would you guess how much RAM we need in order to convert relatively big models @awni?

**Comment by awni** [comment]
This should be supported now. Closing the issue. Feel free to comment or make a new isssue if you run into any problems!
