### ISSUE TITLE
Could I use the model 't5' when I fine tune with lora.py?

### ISSUE THREAD

**Issue by 592319702** [ml-explore/mlx-examples#560]
Could I use the model 't5' when I fine tune with lora.py?

**Comment by awni** [comment]
The MLX LM doesn't support T5 for fine-tuning. But you could adapt the [lora script](https://github.com/ml-explore/mlx-examples/tree/main/lora) to work with the [T5 example](https://github.com/ml-explore/mlx-examples/tree/main/t5).  We will probably not add it here, but getting it to work should not be too difficult.. all the pieces are there, just need to combine them.

**Comment by 592319702** [comment]
> to w

Thanks a lot.
