### ISSUE TITLE
Documentation Support

### ISSUE THREAD

**Issue by hwaseem04** [ml-explore/mlx-examples#57]
Thanks for this amazing library for Apple Silicon. I would like to know if I can start contributing code examples for each function available in the library so that it will be very useful for newcomers.

@awni,  I would like to get confirmation from you before starting to contribute.

regards,
Muhammad Waseem

**Comment by awni** [comment]
I'm not entirely sure what you mean, but feel free to send a PR or something that I can take a look at!
