### ISSUE TITLE
Memory Issues

### ISSUE THREAD

**Issue by siddartha-10** [ml-explore/mlx-examples#576]
I'm facing a challenge while fine-tuning the gemma-2b model using a substantial 1.2GB training dataset. Despite attempts to increase the max-sequence parameter, my M1 Pro Mac with 16GB RAM runs out of memory, leading to text truncation.  Any assistance would be helpful.

**Comment by awni** [comment]
There is some [documentation](https://github.com/ml-explore/mlx-examples/blob/main/llms/mlx_lm/LORA.md#Memory-Issues) with tips for reducing memory use.

Another option to try is the newly updated gradient checkpointing flag (you would need the latest MLX LM) and pass `--grad-checkpoint`. It will slow things down a bit but use potentially a lot less memory.

**Comment by siddartha-10** [comment]
I have tried the documentation but it didn't seem to work for me.

i am going to try using the grad-checkpoints but is there anything that i can do to not truncate my text?

**Comment by mzbac** [comment]
If I understand the issue correctly, the truncated text is irrelevant to memory usage. It's truncated based on the max_seq you set in the training argument. So if you want to avoid text truncation, you could increase the max seq.

**Comment by awni** [comment]
Yes exactly, just set `--max-seq-length 4096` or whatever length you want. (It will blow up the memory use a lot if you make it really long though.

**Comment by siddartha-10** [comment]
Yep got it thank you guys for your help, The last 2 comments cleared my doubts. Closing this issue now.

**Comment by siddartha-10** [comment]
Assuming the worst case if my text is so large i cannot control the truncation right? Because the sequence length of my text is about 20000.

**Comment by awni** [comment]
What I would do is split the longest sequences into multiple sequences of shorter lengths as a preprocessing step. 20000 is very long and almost certainly not going to fit on your machine. It will also be very slow as attention compute (and memory) scales with the square of the length!

**Comment by siddartha-10** [comment]
I am so sorry to trouble you, but still not able to understand how to split it ```i have 24,773 instances of training data and the longest sequence length is about 10000```. Any suggestion would be really helpful thank you.

**Comment by awni** [comment]
> the longest sequence length is about 10000

You should write a short program to split sequences longer than some maximum length (say 2048) into a bunch of sequences of length 2048 or less.
