### ISSUE TITLE
Encountered mlx version issue in text2img example

### ISSUE THREAD

**Issue by sungjaeCho96** [ml-explore/mlx-examples#584]
When running text2img.py, I encountered an issue due to the absence of the get_memory_peak function. 

Upon checking the mlx repository, it seems that this function is supported from version 0.5.1 onwards. In that case, wouldn't it be advisable to update the mlx version condition in mlx_examples/stable_diffusion/requirements.txt to be 0.5.1 or higher?

`AttributeError: module 'mlx.core.metal' has no attribute 'get_peak_memory'`

The above error message occurred when running on mlx version 0.4.0.

**Comment by awni** [comment]
Yes we should update the requirements.txt!
