### ISSUE TITLE
LoRA llama2-70b not giving any info when fine tuning

### ISSUE THREAD

**Issue by fedecanzo** [ml-explore/mlx-examples#586]
I am currently trying to fine tune a llama2-70b models, but scripts seems freezed.
 `!python lora.py --data datafn --model meta-llama/Llama-2-70b-chat-hf  --train --iters 2 --batch-size 4`, I waited for almost two hours and nothing appeared on log. Do i need to wait more time?

**Comment by awni** [comment]
> Do i need to wait more time?

No it shouldn't take two hours to see some output. I'm guessing you don't have enough RAM so it's grinding the machine to a halt. I'm not even sure it's possible to fine tune non-quantized on an M2 Ultra, I haven't tried it tbh.

My recommendation is to do QLoRA, even so you still need a lot of RAM. You can try some of the [following strategies](https://github.com/ml-explore/mlx-examples/blob/main/llms/mlx_lm/LORA.md#Memory-Issues) to reduce the memory footprint or use a smaller model.
