### ISSUE TITLE
Training set not found

### ISSUE THREAD

**Issue by samedovzaur1** [ml-explore/mlx-examples#597]
I'm having this while using this command:
python -m mlx_lm.lora --train --model ./mlx_model --data ./mlx_lm/data --batch-size 1 --lora-layers 16 --iters 3200 --save-every 200 --max-seq-length 4096 --learning-rate 1e-4

This is the error:
ValueError: Training set not found or empty. Must provide training set for fine-tuning.
![Screenshot 2024-03-20 at 2 04 30 AM](https://github.com/ml-explore/mlx-examples/assets/156820070/f32efa81-fec8-49bd-9350-e9ff250bb66d)

**Comment by awni** [comment]
It looks like you stored the data in `mlx_model` not `mlx_lm`...

**Comment by samedovzaur1** [comment]
> It looks like you stored the data in `mlx_model` not `mlx_lm`...

My bad, was sleepy that time 👯‍♂️
