### ISSUE TITLE
can you add the Mistral-7B-Instruct-v0.1 model ?

### ISSUE THREAD

**Issue by thegodone** [ml-explore/mlx-examples#60]
That would be nice to that the chat version of mistral.

https://huggingface.co/mistralai/Mistral-7B-Instruct-v0.1

**Comment by awni** [comment]
We need to add support for conversion from the HF repo. Can look into this soon.

**Comment by katopz** [comment]
0.2 now https://huggingface.co/mistralai/Mistral-7B-Instruct-v0.2
and better support quantized one (new issue?) https://huggingface.co/TheBloke/Mistral-7B-Instruct-v0.2-GGUF

**Comment by awni** [comment]
These should be usable now from the Hugging Face hub! See https://huggingface.co/mlx-community/Mistral-7B-Instruct-v0.2

Let me know if you have any issues and I will reopen this!
