### ISSUE TITLE
How could I deal with the GPU memory issue when fine-tune with lora?

### ISSUE THREAD

**Issue by 592319702** [ml-explore/mlx-examples#600]
I have 40 training data and 4 validation data.

(mlx) I542464@DY4GPKX1J0 lora % ls -al ./data
total 1496
drwxr-xr-x   4 I542464  staff     128 Mar 20 11:31 .
drwxr-xr-x  19 I542464  staff     608 Mar 20 16:15 ..
-rw-r--r--   1 I542464  staff  727714 Mar 20 11:29 train.jsonl
-rw-r--r--   1 I542464  staff   33800 Mar 20 11:31 valid.jsonl

Here is my fine-tune log, seems there is not enough gpu memory. I guess it is using gpu when training.

(mlx) I542464@DY4GPKX1J0 lora % python lora.py \
 --train \
 --model HuggingFaceH4/zephyr-7b-beta \
 --data ./data \
 --batch-size 1 \
 --lora-layers 4 \
 --iters 500
Loading pretrained model
Total parameters 7242.158M
Trainable parameters 0.426M
Loading datasets
Training
[WARNING] Some sequences are longer than 2048 tokens. Consider pre-splitting your data to save memory.
libc++abi: terminating due to uncaught exception of type std::runtime_error: [METAL] Command buffer execution failed: Insufficient Memory (00000008:kIOGPUCommandBufferCallbackErrorOutOfMemory)
zsh: abort      python lora.py --train --model HuggingFaceH4/zephyr-7b-beta --data ./data  1

**Comment by awni** [comment]
This is not a memory issue.. it's just a default setting of `--max-seq-length`.  You can make it longer to avoid that warning but at some point you will indeed run out of memory.. so I would also recommend (as does the warning) that you split your very long sequences into a few shorter sequences as a preprocessing step.

**Comment by 592319702** [comment]
@awni I have another question, if my training data's token is longer than 2048 token which config by`--max-seq-length` . Does this mean our mlx frame will cut my data to 2048 tokens to adapt to the max-seq-length?

**Comment by awni** [comment]
Yes that's exactly right!

**Comment by 592319702** [comment]
Thanks a lot. @awni

**Comment by southkorea2013** [comment]
> This is not a memory issue.. it's just a default setting of `--max-seq-length`. You can make it longer to avoid that warning but at some point you will indeed run out of memory.. so I would also recommend (as does the warning) that you split your very long sequences into a few shorter sequences as a preprocessing step.

Hi awni, How to split the long sequence into a few shorter sequences, Is the format like as follows ?
{"prompt": "Question1?", "completion": "Answer Part1\n"}
{"prompt": "Question1?", "completion": "Answer Part2\n"}
{"prompt": "Question1?", "completion": "Answer Part3<EOS>"}

Thanks.
