### ISSUE TITLE
Whisper is incredibly slow, PyTorch and even Whisper.cpp blow this out of the water

### ISSUE THREAD

**Issue by magnacartatron** [ml-explore/mlx-examples#624]
10 minutes of maxed out M1 Ultra GPU to transcribe tiny model  60 minutes file is very bad performance.
Especially when the likes of whisper.cpp and PyTorch can do it in 8 to 10 minutes (445 seconds) on same hardware.
My 40 flops of fp16 on m1 ultra look like a pretty bad compared to 60 tflop Nvidia card which does it under 2 minutes using PyTorch.

**Comment by awni** [comment]
Could you share the commands you run to compare the different frameworks?

**Comment by jrp2014** [comment]
What is the conclusion?  Does lightening whisper still perform much faster than the version here, or have the tweaks that it uses been incorporated?

**Comment by awni** [comment]
Lighting whisper will still be much faster for long transcriptions because of the batching. That has not been incorporated into `mlx-whisper`.
