### ISSUE TITLE
Mixtral model crashing with long prompt

### ISSUE THREAD

**Issue by oliverks** [ml-explore/mlx-examples#626]
I am using a 54K long prompt to the Mixtral-8x7B-Instruct-v0.1 quantized to 8bit on a 64GB M1 Mac.

The crash is happening in the 
class Mixtral(nn.Module):
    def __init__(self, args: ModelArgs):
        super().__init__()
        self.args = args
        self.vocab_size = args.vocab_size
        self.n_layers = args.n_layers
        assert self.vocab_size > 0
        self.tok_embeddings = nn.Embedding(args.vocab_size, args.dim)
        self.layers = [MOETransformerBlock(args=args) for _ in range(args.n_layers)]
        self.norm = nn.RMSNorm(args.dim, eps=args.norm_eps)
        self.output = nn.Linear(args.dim, args.vocab_size, bias=False)

    def __call__(
        self,
        inputs: mx.array,
        cache=None,
    ):
        h = self.tok_embeddings(inputs)

        mask = None
        T = h.shape[1]
        if T > 1:
            mask = nn.MultiHeadAttention.create_additive_causal_mask(T)
            mask = mask.astype(h.dtype)

        if cache is None:
            cache = [None] * len(self.layers)

        for e, layer in enumerate(self.layers):
            h, cache[e] = layer(h, mask, cache[e]) ## <-- crash here

        return self.output(self.norm(h[:, T - 1 : T, :])), cache

I think I may be hit a hard limitation, as I don't think I am really running out of RAM.  Cutting the prompt to 43K works just fine.  Adding just a bit more, causes it to crash, and the python memory utilization doesn't seem to be spiking as I approach the 43K prompt size.

is there something I need to adjust to get to the larger prompt size?

**Comment by awni** [comment]
> Adding just a bit more, causes it to crash

Share the error message?

**Comment by oliverks** [comment]
It crashes pretty hard, you don't get a stack trace out of python.  IT just says

libc++abi: terminating due to uncaught exception of type std::runtime_error: [METAL] Command buffer execution failed: Insufficient Memory (00000008:kIOGPUCommandBufferCallbackErrorOutOfMemory)
Abort trap: 6

**Comment by oliverks** [comment]
Is it possible it is running out of memory because the attention block is to big?

**Comment by awni** [comment]
> Insufficient Memory

Indeed that one looks pretty clear :). Maybe try a smaller model or a larger machine.

You could increasing the wired GPU limit, but I'm not sure that will help much:

```
sudo sysctl iogpu.wired_limit_mb=64000
```

**Comment by oliverks** [comment]
Well that cause a hard crash, and the whole system to shut down.

Is there a way to estimate how much RAM the system needs to run the prompt?

**Comment by awni** [comment]
One more comment: Mistral (and hence probably Mixtral?) were trianed with a sliding window of 4096 (https://mistral.ai/news/announcing-mistral-7b/).

MLX LM does not implement that.. so you have to be careful when going over 4096 in general as perf might degrade. In theory we could reduce the memory a lot if we use that sliding window but it would likely require a custom kernel to implement efficiently.

**Comment by oliverks** [comment]
What's weird is the memory seems non linear.  It works taking up about 45GB and then suddenly collapses.  Its almost as if there is a very hungry memory step in prepping the model.

**Comment by awni** [comment]
> Is there a way to estimate how much RAM the system needs to run the prompt?

Indeed you should be able to compute that based on the model dimension and the number of layers. We don't currently have an API for it :\

**Comment by oliverks** [comment]
But the model works find with smaller prompts, so it must be the prompt size that is overwhelming it somehow.

**Comment by awni** [comment]
> What's weird is the memory seems non linear.

It's not linear, it's quadratic in the length of the prompt. For short prompts the model size dominates but for long the score matrices get to be too large.

**Comment by oliverks** [comment]
Sure that I agree with, what's weird is it seems way more non linear than quadratic.

So my prompt at 43750 takes 42 GB of RAM (although I think there is slight spike before it gets going) 
at 43962 takes 43 GB of RAM
at 44024 it works and takes 43.22
at 44092 it fails

As I approach the limit on activity monitor I see the memory usage seem reall spiky.  At 44024 I sometimes see the model drop to 30GB and other times leap to 56GB.  It seems more stable with a bit smaller prompt.

I don't think it even gets to run the prompt through the model when it fails.  It seems to be more setting up the model that fails.

**Comment by oliverks** [comment]
I have taken a screen shot of the memory problem I am talking about.  You can see it often is 30% more than the physical memory.

![spiky memory](https://github.com/ml-explore/mlx-examples/assets/20148922/a9c2a78f-6199-4d55-824d-7cc9edfd4436)

**Comment by awni** [comment]
Strange.. ok I will take a look and see if I can reproduce that

**Comment by awni** [comment]
So I assume you are measuring the prompt length as a string rather than after the encoding. I can't even get it to run with a prompt of 20k tokens:

```
   prompt_tokens = mx.random.randint(0, 100, shape=(20000,))
```

It crashes OOM with the same message you gave

**Comment by awni** [comment]
> at 44024 it works and takes 43.22
> at 44092 it fails

The fact that there is a hard limit is not too surprising. The OS/metal runtime have limits on how much memory you can use / swap etc and those are specific values

**Comment by oliverks** [comment]
I am running on an 8bit quantized model, not the 32bit.  We have a client that wants to run the model on a Mac.  So we want to make sure they can run the long quotes without running out of memory.

**Comment by awni** [comment]
> I am running on an 8bit quantized model, not the 32bit

The scores will be upcast to 32 bit regardless of the quantization used

**Comment by awni** [comment]
>  So we want to make sure they can run the long quotes without running out of memory.

So that limit will get a lot better with:
1. Fused attention (this will let us avoid materializing the full upcast to 32-bit) as well as allow for faster prompt processing by taking advantage of the triangular sparsity
2. Windowed attention (this might be possible to implement with e.g. a convolution, I would need to consider that).

1 is already on the roadmap.
2 we can investigate and possibly include in 1 depending.

**Comment by awni** [comment]
You *should* be able to use much longer prompts now in the latest MLX LM (https://github.com/ml-explore/mlx-examples/pull/931). `pip install -U mlx-lm` and let us know if it's still an issue.
