### ISSUE TITLE
llora/convert.py not working

### ISSUE THREAD

**Issue by vierzwei** [ml-explore/mlx-examples#63]
I could not get the file llora/convert.py to work. 
There is a typo with n_heads. it should be:
`        if "n_kv_heads" not in config:
            config["n_kv_heads"] = config["n_heads"];
        if "head_dim" not in config:
            config["head_dim"] = config["dim"] // config["n_heads"];
`
Instead of  ` config["n_kv_heads"] = n_heads;` etc.

But even after fixing this, the resulting file did not work. The convert file in /llama/ did work.

**Comment by awni** [comment]
Sorry about that, I pushed a fix should be merged soon: #64 

Could yo tell me what else didn't work for you? (Stack trace / ...). After fixing the conversion, it runs fine for me..

**Comment by awni** [comment]
Comment if there is still an issue and I will reopen.
