### ISSUE TITLE
Please share the sample of chat format for LoRA Fine-tuning

### ISSUE THREAD

**Issue by southkorea2013** [ml-explore/mlx-examples#630]
I cannot organize the train.jsonl and valid.jsonl for the latest chat format, it always complains when run mlx_lm.lora. Thanks. Should I convert all the contents in one line?

**Comment by mzbac** [comment]
Not sure if  I understand the issue, but you can try using tokenizer.apply_chat_template to convert the conversation into text.

**Comment by southkorea2013** [comment]
Thanks mzbac.  I cannot use the following the chat format for LoRA Fine-Tuning.
![1](https://github.com/ml-explore/mlx-examples/assets/45256048/96d1824a-d9a0-40cb-a668-9d7470348950)

**Comment by mzbac** [comment]
you can do something like:
```
for item in data:
  data.text = tokenizer.apply_chat_template(item['messages'], tokenize=False)
```

**Comment by madroidmaq** [comment]
@southkorea2013 The jsonl format should ensure that each piece of data occupies only one line, and the document adds some line breaks to the content for ease of viewing, which should not appear in the jsonl file. Some simple examples are as follows:

```jsonl
{"messages": [{"role": "system", "content": "You are a helpful assistant." },{"role": "user", "content": "Hello."},{"role": "assistant", "content": "How can I assistant you today."}]}
{"messages": [{"role": "system", "content": "You are a helpful assistant." },{"role": "user", "content": "Hello."},{"role": "assistant", "content": "How can I assistant you today."}]}
{"messages": [{"role": "system", "content": "You are a helpful assistant." },{"role": "user", "content": "Hello."},{"role": "assistant", "content": "How can I assistant you today."}]}
```

PS: Providing out an example of your dataset (you can desensitize the data if needed) can better pinpoint the problem.
