### ISSUE TITLE
Errors while generating

### ISSUE THREAD

**Issue by sajinpgupta** [ml-explore/mlx-examples#635]
Hi,
I fine tuned Mistral 7B V0.2 on the SQL dataset and it went well.
python -m mlx_lm.lora --model mlx_mistral7b_v0.2_q --train --data data --iters 600 --batch-size 1 --lora-layers 8 --steps-per-report 10
While generating
python -m mlx_lm.generate --model mlx_model --adapter-file adapters.npz --prompt “If you get a ranking as major in the english military then what would the spanish military address you as?”
it throws error zsh: no matches found: as?”
Not sure what is going on

**Comment by angeloskath** [comment]
It seems that the prompt is passed incorrectly. My guess would be that the question is copy-pasted and there is a line change so instead of calling

```
$ python -m mlx_lm.generate \
    --model mlx_model --adapter-file adapters.npz \
    --prompt “If you get a ranking as major in the english military then what would the spanish military address you as?”
```

you call

```
$ python -m mlx_lm.generate \
    --model mlx_model --adapter-file adapters.npz \
    --prompt “If you get a ranking as major in the english military then what would the spanish military address you "
$ as?”
```

**Comment by sajinpgupta** [comment]
thanks!. You are right i copy pasted question from test  set. I deleted the double quote on both ends and manually typed in the double quote.
