### ISSUE TITLE
Regarding with #625

### ISSUE THREAD

**Issue by JKwon0331** [ml-explore/mlx-examples#641]
Hi, 

Regarding with issue "Doesn't change the value in the class. #625",

I tried to do what you recommended.

```python
 def __call__(self, inputs):
        outputs = inputs       
        for idx,layer in enumerate(self.layers):
            if idx == self.reduce_layer_index:
                self.recover_tensor = outputs
                if self.recover_tensor is None:
                    delattr(self,'recover_tensor')            
            if idx == self.recover_layer_index:
                outputs += self.recover_tensor
            
            outputs = self.layers['layer' + str(idx)](outputs)
      return outputs
```

after that, when I update the model with followed code,

I found this error.
![Screenshot 2024-03-30 at 8 07 43 PM](https://github.com/ml-explore/mlx-examples/assets/113830330/449331b5-0ba7-4ce5-9bcf-52b84f503166)

When I debugged, I checked that self.recover_tensor changed well.

Can you let me know how to deal with this?

**Comment by awni** [comment]
Re #625, it is fixed in the latest release, so you can just `pip install -U mlx` 

I am not sure why you are deleting the attribute `recover_tensor` (?) but I would not do that..

**Comment by JKwon0331** [comment]
I added the screenshot.

This is why I use deleting the attribute.

I also use pip install -U mlx
![Screenshot 2024-03-30 at 9 09 59 PM](https://github.com/ml-explore/mlx-examples/assets/113830330/241f57fb-6de3-4fab-b3a5-f4c8007e6699)
![Screenshot 2024-03-30 at 9 09 50 PM](https://github.com/ml-explore/mlx-examples/assets/113830330/301c81a5-140c-4da2-9ed9-c4e57ba55283)

As you can see, with out deleting the attribute, it doesn't change.

**Comment by awni** [comment]
Again I really am not sure what you are doing there without seeing any code..

The following works fine for me:

```
import mlx.core as mx
import mlx.nn as nn

class Model(nn.Module):

    def __init__(self):
        super().__init__()
        self.param = None

    def set_param(self, x):
        self.param = x


model = Model()
model.set_param(mx.array([1, 2, 3]))
print(model.param)
model.set_param(mx.array([3, 2, 1]))
print(model.param)
```

**Comment by JKwon0331** [comment]
Hi, after restarting the spyder, it works! Thank you for your assistance.

However, there is still error.
This is code.

   def __call__(self, inputs):
        outputs = inputs
        for idx,layer in enumerate(self.layers):
            if idx == self.reduce_layer_index:              
                self.recover_tensor = outputs
            
            if idx == self.recover_layer_index:
                outputs += self.recover_tensor
            
           outputs = self.layers['layer' + str(idx)](outputs)
     
        return outputs

This is error
![Screenshot 2024-03-30 at 9 29 30 PM](https://github.com/ml-explore/mlx-examples/assets/113830330/a44386f1-525c-41c6-b638-3ef49b7aaed0)

Thank you

**Comment by awni** [comment]
Can you share the full example?
