### ISSUE TITLE
Server produce gibberish output for some model

### ISSUE THREAD

**Issue by alwint3r** [ml-explore/mlx-examples#647]
The issue is observed on a 4-bit quantized `cognitivecomputations/dolphin-2.8-mistral-7b-v02` model.

Here's a curl request to reproduce the issue:
```bash
curl -X POST localhost:8080/v1/chat/completions \
    -H "Content-Type: application/json" \
    -d '{
            "messages":[
                  {
                        "role": "user",
                        "content": "Write a sentence of opening line for a dune-like movie"
                  }
            ],
            "max_tokens":500,
            "temperature":0.9
      }'
```

I would expect a response with the following line from the model

```
In a world of shifting sands and endless winds, a stranger's arrival sets off a chain of events that would determine the fate of a people and the land.
```

Here's the complete response that I received instead:

```json
{
  "id": "chatcmpl-85aa4e55-521b-4d35-960b-a2a4333b68dc",
  "system_fingerprint": "fp_beaf8d29-15d9-4c27-b583-2817518b51a6",
  "object": "chat.completions",
  "model": "default_model",
  "created": 1712188000,
  "choices": [
    {
      "index": 0,
      "logprobs": null,
      "finish_reason": "stop",
      "message": {
        "role": "assistant",
        "content": "||\b\ufffd\u00ab\ufffd{'What\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\u02da\ufffd}}_\ufffd\ufffd\ufffd\u06d5\ufffd\u0635\ufffd\u0437<`\u0414\ud83d\ude44\u2800\ufffd\u00ab\ufffd}))\ufffdigent\u00b3\u0445\u0430\ufffd@@\ufffd.<`DF\u0010subseteq\ufffd\ufffd\ufffd\ufffd\ufffd\u00a7\ufffd';\u0151l\ufffd\u011bl\u06d9 Una\u6d32\ufffd\ufffd'+\u00b0\ufffd<'\u00f9 beskrevs^-POS\u2122',',',',',','\u25cf`,`,,,','=>-_;``\ud83d\ude04\u0336\ufffd]+\ufffd ERR\ufffdefore \u0412\u0438\u06fb\u06d9\u043d\u0435Wrapper\u30fc\ufffd'))\ufffd Kamp klassLENGTH\ufffd\ufffd\ufffd'_\ufffd\u0090\ufffd\u0433\u0440\u0430\u0444\u0456\ufffd\ufffd\ufffd\ufffd\ufffd nationale',',',',',',,`,',',',' False\ufffd\u00d8\ufffd\ufffd\ufffd\ufffd\u200f\ufffd\uad6c\ufffd\u201a\ufffd\ufffd\u00c6\ufffd'}\ufffd\ufffd\ufffd\u05d8\ufffd\u043b\u044f\u0440\ufffd fais\ufffd\ud83e\udd14\ufffd                \u0178\ufffd habitants'_\ufffd\u0098\ufffd bzw\ufffd\ufffd\u0178\ufffd\ufffd\u00e4l\ufffd\ufffd\ufffd\u00b9\ufffd waited\ufffd \u00b0 \u0420\u0435\u06f7\u0158\ufffdLOT\ufffd todas\ufffd\ufffd\u06be\ufffd\u1d1c\ufffdAMP"
      }
    }
  ],
  "usage": {
    "prompt_tokens": 22,
    "completion_tokens": 200,
    "total_tokens": 222
  }
}
```

I did a little bit of investigation,  I found out that changing the following line in the `mlx_lm/server.py` file fixed the issue:

```py
# Original
prompt = TOKENIZER.apply_chat_template(
    body["messages"],
    tokenize=True,
    add_generation_prompt=True,
)

# Fixed
prompt = TOKENIZER.apply_chat_template(
    body["messages"],
    tokenize=False,
    add_generation_prompt=True,
)
prompt = TOKENIZER.encode(prompt)
```

The server produced the correct output:

```json
{
  "id": "chatcmpl-66ce1b54-a470-4ac0-902c-3996dad943b8",
  "system_fingerprint": "fp_90f61b62-9612-4647-885c-1064a0788aac",
  "object": "chat.completions",
  "model": "default_model",
  "created": 1712188169,
  "choices": [
    {
      "index": 0,
      "logprobs": null,
      "finish_reason": "stop",
      "message": {
        "role": "assistant",
        "content": "In a world of shifting sands and endless winds, a stranger's arrival sets off a chain of events that would determine the fate of a people and the land."
      }
    }
  ],
  "usage": { "prompt_tokens": 23, "completion_tokens": 34, "total_tokens": 57 }
}
```

I used both the `mlx` and `mlx_lm` development versions with the following details:
* mlx_lm latest commit: 2bd64b78cf304387e8fea7cc20db684b3a5f8459
* mlx latest commit: 0caf35f4b83eabaa85953f590f88f05455c0b746

After applying the change, I tested it with the following models:
* zephyr-7b-beta 4-bit
* mistral-7b-instruct-v0.2 4-bit
* qwen1.5-7b-chat 4bit
* tinyllama-1.1b-chat-v1.0
* dolphin-2.8-mistral-7b-v02 4-bit

The change didn't break those models.

I'm happy to file a PR

**Comment by mzbac** [comment]
It looks like something has changed in the transformers library, leading to this change in behavior. Could you try downgrading your transformers or add `return_dict=False` in the`apply_chat_template` call,  see if the issue gets fixed?
 
https://github.com/huggingface/transformers/commit/9d999481b2bb231de3c5980e407200bd0ce3ce4d#diff-85b29486a884f445b1014a26fecfb189141f2e6b09f4ae701ee758a754fddcc1

**Comment by alwint3r** [comment]
I tried using transformers version 4.39.3 and 4.38.0.
I'll look into it.

**Comment by alwint3r** [comment]
Update:

* I tried adding `return_dict=False` to transformers version 4.38.0, 4.38.1, 4.38.2, 4.39.0, 4.39.1, 4.39.2, 4.39.3 and the model produced gibberish.
* I tried downgrading the transformers to version 4.37.x and 4.36.x the model still produced gibberish.

**Comment by mzbac** [comment]
That looks very strange, I will try to reproduce it on my local see if I can find anything.

**Comment by mzbac** [comment]
The root cause is that the `apply_chat_template` disabled the special token (bos in this case) at https://github.com/huggingface/transformers/blob/main/src/transformers/tokenization_utils_base.py#L1805 and somehow the `cognitivecomputations/dolphin-2.8-mistral-7b-v02` is very sensitive to that. Maybe we could report an issue in the transformers repository to see why it gets disabled, as the behavior of `apply_chat_template(tokenize=True)` is different from `tokenizer.encode`. In the meantime, we can apply the workaround suggested by @alwint3r.

**Comment by alwint3r** [comment]
Thank you @mzbac.

I'll submit the workaround PR.

**Comment by awni** [comment]
@alwint3r or @mzbac not sure was there anything to fix in MLX server after this? It sounded like the chat template had an issue, was that the whole problem?

**Comment by alwint3r** [comment]
There shouldn't be an issue specifically with the MLX server. The model's chat template didn't work well with the `apply_chat_template` function from the transformers library.

**Comment by mzbac** [comment]
Yeah, the model template was missing the bos token, I was thinking about to add it via tokenizer.encode method, but after reading the transformers docs. Seems it prefers to handle that in chat template.

**Comment by yaroslavyaroslav** [comment]
@mzbac could you please provide an example of template with system, assistant, user roles? There's the lack of docs about template format.
