### ISSUE TITLE
LLama example doesn't work with HF format models?

### ISSUE THREAD

**Issue by mzbac** [ml-explore/mlx-examples#65]
First of all, thank you for the great work in providing us with all those examples. However, when I tried to use the LLama model in HF format, it didn't work. I was able to convert the HF format model weights to npz format by reverse engineering the convert.py and transformers' convert HF from pytorch script. The model seems to load without any errors, but it doesn't output any meaningful words; just a series of random characters.
Here is what I did to convert the HF format model:
- Merge all the shard weights into one .pth file, using the following script:
```
from transformers import AutoTokenizer, AutoModelForCausalLM
import torch

model_path = "./models/NousResearch/Llama-2-7b-chat-hf"

out_dir =  "./models/mlx/llama2-chat"

tokenizer = AutoTokenizer.from_pretrained(model_path)
model = AutoModelForCausalLM.from_pretrained(model_path, torch_dtype= torch.float16)

torch.save(model.state_dict(),'./models/mlx/llama2-chat/model.pth')
tokenizer.save_pretrained(out_dir)
```
- Use the modified convert.py as follows to convert HF format weight to npz format.
```
import argparse
from itertools import starmap

import numpy as np
import torch


def map_torch_to_mlx(key, value):
    if "embed_tokens.weight" in key:
        key = "embedding.weight"

    elif "norm" in key:
        key = key.replace("input_layernorm", "norm1").replace("post_attention_layernorm", "norm2")

    elif "q_proj" in key:
        key= key.replace("q_proj","query_proj")

    elif "k_proj" in key:
        key= key.replace("k_proj","key_proj")  

    elif "v_proj" in key:
        key= key.replace("v_proj","value_proj")  

    elif "o_proj" in key:
        key= key.replace("o_proj","out_proj")  

    elif "gate_proj" in key:
        key= key.replace("mlp.gate_proj","linear1")  

    elif "down_proj" in key:
        key= key.replace("mlp.down_proj","linear3")  

    elif "up_proj" in key:
        key= key.replace("mlp.up_proj","linear2")  

    elif "lm_head" in key:
        key = key.replace("lm_head", "out_proj")

    elif "rope" in key:
        return None, None
    
    key = key.replace('model.', '')
    
    return (
        key,
        value.numpy()
        if value.dtype != torch.bfloat16
        else value.to(torch.float32).numpy(),
    )


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Convert Llama weights to MLX")
    parser.add_argument("torch_weights")
    parser.add_argument("output_file")
    args = parser.parse_args()

    state = torch.load(args.torch_weights)
    np.savez(
        args.output_file,
        **{k: v for k, v in starmap(map_torch_to_mlx, state.items()) if k is not None}
    )
```
- Run the llama.py as instructed in the readme.

Wondering if I missed anything? I had a look at the llama.py and it looks fine to me. I'm not very sure why it doesn't work.

**Comment by LeaveNhA** [comment]
I have three updates for you.

1. Your method to combine shereded models is working.
2. Convert is working with combined model.
3. This is bad; I couldn't run the converted model due to lack of my RAM capacity. 64GB is not enough for my job, obv. 🤦🏻‍♂️

I worked on [WizardCoder](https://huggingface.co/WizardLM/WizardCoder-Python-34B-V1.0/tree/main) FYI.

**Comment by awni** [comment]
I updated the conversion script to handle sharded weights for larger models. But we need to update the HF weights to be compatable with the updated model.

**Comment by andersonbcdefg** [comment]
Just my experience, but I found when converting HF weights (I tried with TinyLlama and Llama-2-7b-chat-hf), I got gibberish output from the model when nn.RoPE had `traditional=True`. Once I set `traditional=False`, the output from both models looks normal. I found this surprising, since I wouldn't expect the HuggingFace and Meta weights to be so different that they require totally different RoPE. @awni do you know what's going on here?

**Comment by awni** [comment]
- The HF models are updated now to the new format: https://huggingface.co/mlx-llama
-
- @andersonbcdefg I don't see gibberish using the chat model, the output looks pretty reasonable to me. Maybe you could share your command so I can see if we get the sam eoutput.

**Comment by andersonbcdefg** [comment]
Just to be clear, this is not when I used the `mlx-llama` weights, it's when I rolled my own conversion from the HuggingFace models. This is the script I used to do that (adapted from the convert script for meta weights).

```
import fire
from itertools import starmap
from transformers import AutoModelForCausalLM, AutoConfig
import numpy as np
import torch
import collections
import glob
import json
from pathlib import Path
from typing import Literal

import numpy as np
import torch

SHARD_FIRST = ["wv", "wq", "wk", "w1", "w3", "output"]
SHARD_SECOND = ["tok_embeddings", "wo", "w2"]
SHARD_WEIGHTS = set(SHARD_FIRST + SHARD_SECOND)


def shard_key(k):
    keys = k.split(".")
    if len(keys) < 2:
        return None
    return keys[-2]


def unshard(k, v):
    wn = shard_key(k)
    if wn not in SHARD_WEIGHTS:
        return v
    elif wn in SHARD_FIRST:
        axis = 0
    elif wn in SHARD_SECOND:
        axis = 1
    else:
        raise ValueError("Invalid weight name")
    return np.concatenate(v, axis=axis)

def convert(
    model_path: str,
    output_path: str,
    input_format: Literal["meta", "hugging_face"] = "hugging_face",
):
    if input_format == "hugging_face":
        model = (AutoModelForCausalLM.from_pretrained(model_path)
            .to(torch.float32)
            .state_dict())
        config = AutoConfig.from_pretrained(model_path)

        # things to change
        # 1. there's no "model." in the weight names
        model = {k.replace("model.", ""):v for k, v in model.items()}
        
        # 2. mlp is called feed_forward
        model = {k.replace("mlp", "feed_forward"):v for k, v in model.items()}

        # 3. up_proj, down_proj, gate_proj
        model = {k.replace("down_proj", "w2"):v for k, v in model.items()}
        model = {k.replace("up_proj", "w3"):v for k, v in model.items()}
        model = {k.replace("gate_proj", "w1"):v for k, v in model.items()}

        # 4. layernorms
        model = {k.replace("input_layernorm", "attention_norm"):v for k, v in model.items()}
        model = {k.replace("post_attention_layernorm", "ffn_norm"):v for k, v in model.items()}

        # 5. lm head
        model = {k.replace("lm_head", "output"):v for k, v in model.items()}

        # 6. token emb
        model = {k.replace("embed_tokens", "tok_embeddings"):v for k, v in model.items()}

        # 7. attention
        model = {k.replace("self_attn", "attention"):v for k, v in model.items()}
        model = {k.replace("q_proj", "wq"):v for k, v in model.items()}
        model = {k.replace("k_proj", "wk"):v for k, v in model.items()}
        model = {k.replace("v_proj", "wv"):v for k, v in model.items()}
        model = {k.replace("o_proj", "wo"):v for k, v in model.items()}



        params = {}
        params["dim"] = config.hidden_size
        params["hidden_dim"] = config.intermediate_size
        params["n_heads"] = config.num_attention_heads
        if hasattr(config, "num_key_value_heads"):
            params["n_kv_heads"] = config.num_key_value_heads
        params["n_layers"] = config.num_hidden_layers
        params["vocab_size"] = config.vocab_size
        params["norm_eps"] = config.rms_norm_eps
        


        # then save
        np.savez(Path(output_path) / "weights.npz", **model)
        json.dump(params, open(Path(output_path) / "params.json", "w"))

if __name__ == "__main__":
    fire.Fire(convert)
```

After I did this conversion to npz, I find that running llama.py with temp 0.7 and prompt "Hi what's up" (tokenized according to the chat template matching the model) produces some coherent words and lots of gibberish / random symbols with traditional RoPE, but perfect coherent responses when I set traditional RoPE to False. Totally possible I botched the conversion, but I think it's hard to get coherent text by accident (every time I got gibberish before I had forgotten to convert a weight, haha).

**Comment by awni** [comment]
Which llama model were you testing? Could you point me to the HF repo?

I tested llama-2-7b-chat from meta directly and it works with `traditional=True` but it's possible the version you are using was fine-tuned with `traditional=False` or something like that.  But I agree with you it's unlikely it would generate good responses if it wasn't expecting that setting.

**Comment by andersonbcdefg** [comment]
Yeah, it's odd, I'm not sure how Meta or HF would turn one type of RoPE into another even if they wanted to! LOL.

Here's the model I only got to work with traditional=False:

https://huggingface.co/TinyLlama/TinyLlama-1.1B-Chat-v0.6/tree/main

Note that this one was pretrained from scratch, so it's possible the guy used a different RoPE setting. However, I experience the same thing when using this model: https://huggingface.co/meta-llama/Llama-2-7b-chat-hf

**Comment by awni** [comment]
Cool we can look at porting TinyLlama. I'll close this issue as this  discussion is unrelated to the issue. Feel free to file an issue regarding TinyLlama (or comment here if you have any more questions)
