### ISSUE TITLE
Enso error when running llama-2- w/70B parameters

### ISSUE THREAD

**Issue by DDoyle1066** [ml-explore/mlx-examples#653]
Hi!
I was recently experimenting with running the llama 2 models and encountered a strange error where the 70B parameter model would just give me "enso" over and over again for any prompt (In this instance I was just testing with who is Abe Linconl which the 13B and 7B parameter were able to answer) Does anybody know what could be causing this? And not sure if it is an MLX issue versus a llama 2 issue.

Thanks!

**Comment by awni** [comment]
Can you share the command you were using?

**Comment by DDoyle1066** [comment]
I ran the example script at mlx-examples/llms/llama as follows after downloading the weights as follows:
```
python src/mlx-examples/llms/llama/llama.py --model-path=models/mlx-llama-2-70b --prompt="Who is Abe Lincoln?"
```
and got the following:
```
[INFO] Loading model from models/mlx-llama-2-70b/weights.*.npz.
Press enter to start generation
------
Who is Abe Lincoln?
enso?enso?enso!enso!enso!enso!enso!enso!enso!enso!enso!enso!enso!enso!enso!enso!enso!enso!enso!
```
When I did this changing to the path for the 7B weights I got this:
```
[INFO] Loading model from models/mlx-llama-2-7b/weights.npz.
Press enter to start generation
------
Who is Abe Lincoln?

Abraham Lincoln was the 16th President of the United States, serving from March 1861 until his assassination in April 1865. Lincoln led the United States through its Civil War—its bloodiest war and perhaps its greatest moral, constitutional, and political crisis. In doing so, he preserved the Union, abolished slavery, strengthened the federal government, and modernized the U.S. economy.
Lincoln was born in
------
[INFO] Prompt processing: 4.608 s
[INFO] Full generation: 7.864 s
```

**Comment by awni** [comment]
Got it. Yes that llama example is not well tested with the larger models. I think some configuration or weights might be off.

If you can, try using MLX LM instead, you can use this model: [mlx-community/llama2-70b-qnt4bit](https://huggingface.co/mlx-community/llama2-70b-qnt4bit)

E.g. ` python -m mlx_lm.generate --model mlx-community/llama2-70b-qnt4bit --max-tokens 512 --prompt "Write a quick sort in Python"`

That should definitely work, if it doesn't, let me know.

**Comment by DDoyle1066** [comment]
thanks for pointing me to that. however, I am now running into the following:
```
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/Users/danieldoyle/Projects/sisyphus/social-media/.venv/lib/python3.12/site-packages/mlx_lm/generate.py", line 148, in <module>
    main(args)
  File "/Users/danieldoyle/Projects/sisyphus/social-media/.venv/lib/python3.12/site-packages/mlx_lm/generate.py", line 112, in main
    model, tokenizer = load(
                       ^^^^^
  File "/Users/danieldoyle/Projects/sisyphus/social-media/.venv/lib/python3.12/site-packages/mlx_lm/utils.py", line 381, in load
    model = load_model(model_path, lazy)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/danieldoyle/Projects/sisyphus/social-media/.venv/lib/python3.12/site-packages/mlx_lm/utils.py", line 345, in load_model
    model.load_weights(list(weights.items()))
  File "/Users/danieldoyle/Projects/sisyphus/social-media/.venv/lib/python3.12/site-packages/mlx/nn/layers/base.py", line 223, in load_weights
    raise ValueError(
ValueError: Expected shape (32000, 8192) but received  shape (32000, 5120) for parameter model.embed_tokens.weight
```

**Comment by DDoyle1066** [comment]
Hi, this is still not working for me. I checked out the commit you put in and reran both the parameter generating process and the script and it is not functional

**Comment by DDoyle1066** [comment]
On the bright side, the mlx_lm.generate code is now working. Thank you!

**Comment by awni** [comment]
I only fixed `mlx_lm.generate`.. the `llama/llama.py` model does not work for the 70B model and I have no plans to update that. Use MLX LM for more model support.
