### ISSUE TITLE
Mixtral Bug 

### ISSUE THREAD

**Issue by yuhai-china** [ml-explore/mlx-examples#671]
I try to make a mlx version of my MOE model cloudyu/Mixtral_34Bx2_MoE_60B https://huggingface.co/cloudyu/Mixtral_34Bx2_MoE_60B

But the mlx version doesn't work, I don't know the reason.

it report:
mlx-examples/llms/mlx_lm/models/mixtral.py", line 137, in call
mx.argpartition(-gates, kth=ne, axis=-1)[:, :ne]
ValueError: [argpartition] Received invalid kth 2 along axis -1 for array with shape: (1,2)

I read the code
https://github.com/ml-explore/mlx-examples/blob/main/llms/mlx_lm/models/mixtral.py

at 130 line:

it should be ne = self.num_experts_per_tok - 1  instead of ne = self.num_experts_per_tok

ne = self.num_experts_per_tok that means 1+self.num_experts_per_tok experts working.

**Comment by awni** [comment]
Yup, that's a bug.. do you want to send a PR with your suggested fix?

**Comment by yuhai-china** [comment]
> Yup, that's a bug.. do you want to send a PR with your suggested fix?

https://github.com/ml-explore/mlx-examples/pull/673
