### ISSUE TITLE
llama3 70B 4bit seems to be generating garbage, but 8 bit works fine

### ISSUE THREAD

**Issue by mzbac** [ml-explore/mlx-examples#692]
4 quant by `mlx_lm.convert --hf-path meta-llama/Meta-Llama-3-70B-Instruct -q`
8 quant by `mlx_lm.convert --hf-path meta-llama/Meta-Llama-3-70B-Instruct --q-bits 8 -q`

**Comment by mzbac** [comment]
Just tried reinstalling from the main branch of mlx and mlx-lm, but it's still generating garbage output.

**Comment by awni** [comment]
Looking.. not sure what the problem is yet. Seems like a bug though.

**Comment by mzbac** [comment]
The good news is that the 8-bit speed on the M2 Ultra 60GPU is quite fast, reaching around 8 tokens per second.

```bash
mlx_lm.generate --model llama-70b-8bit-mlx --prompt 'write game of life in python' --max-tokens 2000 --eos-token "<|eot_id|>"   
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
==========
Prompt: <|begin_of_text|><|start_header_id|>user<|end_header_id|>

write game of life in python<|eot_id|><|start_header_id|>assistant<|end_header_id|>


Here is a simple implementation of the Game of Life in Python:

\`\`\`
import random
import time
import os

def create_board(rows, cols):
    board = [[random.choice([0,1]) for _ in range(cols)] for _ in range(rows)]
    return board

def print_board(board):
    os.system('cls' if os.name == 'nt' else 'clear')
    for row in board:
        print(' '.join(['*' if cell else ' for cell in row]))

def count_neighbors(board, row, col):
    neighbors = 0
    for r in range(max(0, row-1), min(len(board), row+2)):
        for c in range(max(0, col-1), min(len(board[0]), col+2)):
            if (r!= row or c!= col) and board[r][c]:
                neighbors += 1
    return neighbors

def next_generation(board):
    new_board = [[0 for _ in range(len(board[0]))] for _ in range(len(board))]
    for r in range(len(board)):
        for c in range(len(board[0])):
            live_neighbors = count_neighbors(board, r, c)
            if board[r][c] and (live_neighbors < 2 or live_neighbors > 3):
                new_board[r][c] = 0
            elif board[r][c] and (live_neighbors == 2 or live_neighbors == 3):
                new_board[r][c] = 1
            elif not board[r][c] and live_neighbors == 3:
                new_board[r][c] = 1
    return new_board

def game_of_life(rows, cols, generations):
    board = create_board(rows, cols)
    for _ in range(generations):
        print_board(board)
        time.sleep(1)
        board = next_generation(board)

game_of_life(20, 20, 100)
\`\`\`

This program creates a 20x20 grid and runs the Game of Life for 100 generations. The `create_board` function creates a random initial board. The `print_board` function prints the current state of the board. The `count_neighbors` function counts the number of live neighbors for a given cell. The `next_generation` function calculates the next state of the board based on the rules of the Game of Life. The `game_of_life` function runs the game for a specified number of generations.

Please note that the `os.system('cls' if os.name == 'nt' else 'clear')` line is used to clear the console before printing the next generation. This line may not work on all systems.
==========
Prompt: 17.230 tokens-per-sec
Generation: 8.628 tokens-per-sec
```

**Comment by mzbac** [comment]
I also tried the old versions mlx 0.6.0 and mlx-lm 0.4.0 without even quantizing lm_head and embedding, but it still produced garbage output. The issue doesn't seem to be related to recent quantization changes.

**Comment by awni** [comment]
I'm starting to wonder if the 70B model might not be so amenable to the simple linear 4-bit quantization. Some tests which don't bode well:

1. Quantize to 4-bit -> dequantize -> generate also gives very similar garbage output. So if there's a bug it would be in the quantization step.
2. Looking at some of the weight magnitudes they are pretty massive but more importantly very very spiky:

For example the following weight matrix:

```python
v = weights["model.layers.0.self_attn.v_proj.weight"]
v = np.array(v.astype(mx.float16))
print("Max", np.max(v))
print("Min", np.min(v))
print("Median", np.median(v))
```

gIves:

```
Max 92.5
Min -79.5
Median 5.3e-06
```

**Comment by ivanfioravanti** [comment]
llama.cpp is working with q4_0 quantization, at least this one on ollama: ollama run llama3:70b-instruct-q4_0 from here: https://ollama.com/library/llama3:70b-instruct-q4_0

**Comment by awni** [comment]
Thanks @ivanfioravanti that's a very useful data point!

**Comment by ivanfioravanti** [comment]
It works initially on llamacpp but over time I see garbage there too. Definitely something with q4 is not working well here.

**Comment by hggz** [comment]
> The good news is that the 8-bit speed on the M2 Ultra 60GPU is quite fast, reaching around 8 tokens per second.
> 
> ```shell
> mlx_lm.generate --model llama-70b-8bit-mlx --prompt 'write game of life in python' --max-tokens 2000 --eos-token "<|eot_id|>"   
> Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
> ==========
> Prompt: <|begin_of_text|><|start_header_id|>user<|end_header_id|>
> 
> write game of life in python<|eot_id|><|start_header_id|>assistant<|end_header_id|>
> 
> 
> Here is a simple implementation of the Game of Life in Python:
> 
> \`\`\`
> import random
> import time
> import os
> 
> def create_board(rows, cols):
>     board = [[random.choice([0,1]) for _ in range(cols)] for _ in range(rows)]
>     return board
> 
> def print_board(board):
>     os.system('cls' if os.name == 'nt' else 'clear')
>     for row in board:
>         print(' '.join(['*' if cell else ' for cell in row]))
> 
> def count_neighbors(board, row, col):
>     neighbors = 0
>     for r in range(max(0, row-1), min(len(board), row+2)):
>         for c in range(max(0, col-1), min(len(board[0]), col+2)):
>             if (r!= row or c!= col) and board[r][c]:
>                 neighbors += 1
>     return neighbors
> 
> def next_generation(board):
>     new_board = [[0 for _ in range(len(board[0]))] for _ in range(len(board))]
>     for r in range(len(board)):
>         for c in range(len(board[0])):
>             live_neighbors = count_neighbors(board, r, c)
>             if board[r][c] and (live_neighbors < 2 or live_neighbors > 3):
>                 new_board[r][c] = 0
>             elif board[r][c] and (live_neighbors == 2 or live_neighbors == 3):
>                 new_board[r][c] = 1
>             elif not board[r][c] and live_neighbors == 3:
>                 new_board[r][c] = 1
>     return new_board
> 
> def game_of_life(rows, cols, generations):
>     board = create_board(rows, cols)
>     for _ in range(generations):
>         print_board(board)
>         time.sleep(1)
>         board = next_generation(board)
> 
> game_of_life(20, 20, 100)
> \`\`\`
> 
> This program creates a 20x20 grid and runs the Game of Life for 100 generations. The `create_board` function creates a random initial board. The `print_board` function prints the current state of the board. The `count_neighbors` function counts the number of live neighbors for a given cell. The `next_generation` function calculates the next state of the board based on the rules of the Game of Life. The `game_of_life` function runs the game for a specified number of generations.
> 
> Please note that the `os.system('cls' if os.name == 'nt' else 'clear')` line is used to clear the console before printing the next generation. This line may not work on all systems.
> ==========
> Prompt: 17.230 tokens-per-sec
> Generation: 8.628 tokens-per-sec
> ```

Do you have any other settings for your system to run at that speed? I'm doing a dry run on mlx_lm with stock settings and getting some pretty low numbers. I also haven't restarted my machine in a bit. It does run, just slowly ~0.45 tokens a second

**Comment by awni** [comment]
Try `sudo sysctl iogpu.wired_lwm_mb=100000`

Unfortunately, sometimes restarting the system also helps. We're still trying to debug/fix the need for that.

**Comment by mzbac** [comment]
I am using the M2 Ultra 128 as a headless server, so it doesn't use any memory for GUI. The memory was enough to run the 70B 8-bit sufficiently. If you are experiencing slow token generation, you can try running it in headless mode to save some memory.

**Comment by mzbac** [comment]
> I'm starting to wonder if the 70B model might not be so amenable to the simple linear 4-bit quantization. Some tests which don't bode well:
> 
> 1. Quantize to 4-bit -> dequantize -> generate also gives very similar garbage output. So if there's a bug it would be in the quantization step.
> 2. Looking at some of the weight magnitudes they are pretty massive but more importantly very very spiky:
> 
> For example the following weight matrix:
> 
> ```python
> v = weights["model.layers.0.self_attn.v_proj.weight"]
> v = np.array(v.astype(mx.float16))
> print("Max", np.max(v))
> print("Min", np.min(v))
> print("Median", np.median(v))
> ```
> 
> gIves:
> 
> ```
> Max 92.5
> Min -79.5
> Median 5.3e-06
> ```

By looking at the gguf q4_0 quantization, it looks similar to mlx quantization (only norm layer is converted to fp32). If the q4_0 is working fine, then mlx should work too. I will try to load the gguf q4_0 via mlx and see if it works.

**Comment by awni** [comment]
@mzbac I already tried that exact test and it works fine. We are narrowing in on a fix already (rather @angeloskath is).

The basic problem is our the quantization operation doesn’t handle these weights well so we are improving it.

**Comment by angeloskath** [comment]
@mzbac feel free to test #1016. On my end it fixes the problem and I can generate at ~15 tps :-)

**Comment by ghogan42** [comment]
Fantastic. I don't suppose that the older quantized weights can be fixed?
These models are quite a big download so if there was some way to run a script and fix the model, that would be cool.

**Comment by vgoklani** [comment]
@mzbac how are you running it in `headless` mode? thanks!

**Comment by mzbac** [comment]
> @mzbac how are you running it in `headless` mode? thanks!

Just run it without gui, only access it via ssh connection

**Comment by angeloskath** [comment]
@ghogan42 if you only have the quantized weights unfortunately not as it basically changes the bias slightly to make sure 0 is represented as 0 so a lot of weights can be falling in a nearby bin but since they are quantized we cannot properly recompute that.

I know that the full weights are ~150GB but if you can spare the disk space (and weight for the download) it is almost always a good idea to download the full weights as quantizing them yourself with MLX is plenty fast and doesn't require a lot of RAM either.

**Comment by angeloskath** [comment]
@mzbac I would also advise to use group size of 32 for the 4 bit quantization. It seems to work with 64 but it is much much better with 32...

**Comment by ivanfioravanti** [comment]
I'm still getting garbage when downloading latest model converted and uploaded by @mzbac just few hours ago. Is it working for you?

I'm now trying with a locally converted one to see if it works.

❯ python -m mlx_lm.generate --model mlx-community/Meta-Llama-3-70B-Instruct-4bit --prompt "Write a snake game in python" --temp 0
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
==========
Prompt: <|begin_of_text|><|start_header_id|>user<|end_header_id|>
Write a snake game in python<|eot_id|><|start_header_id|>assistant<|end_header_id|>
\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\

**Comment by hggz** [comment]
Just chiming in, tried the new 4bit instruct quant and it's running blazing fast and well on a 128gb MBP. Thanks so much for your effort guys, cheers to the future of local inference on apple silicon ❤️!

**Comment by fredsco** [comment]
Unforunately the issue is still here. Now the behaviour is completely different. 

I have deleted the huggingface cache dir + upgraded the mlx library. 

<img width="911" alt="image" src="https://github.com/ml-explore/mlx-examples/assets/14234528/02e25447-29eb-4aec-9e85-2051fdb27e80">

**Comment by fredsco** [comment]
If I remove the temp and max tokens flag I do get a response but then python crashes...
<img width="759" alt="image" src="https://github.com/ml-explore/mlx-examples/assets/14234528/d42fee91-185a-41c2-bcef-89876b61b6ff">

**Comment by vgoklani** [comment]
@awni Hey there, what does  `sudo sysctl iogpu.wired_lwm_mb=100000` do exactly? I couldn't find any documentation, thanks!
