### ISSUE TITLE
Feature request: Add a `--use-temp-file` option in mlx_lm.convert

### ISSUE THREAD

**Issue by sealad886** [ml-explore/mlx-examples#699]
llama.cpp recently addeed a `--use-temp-file` option to their convert script and it's solved the issue of running out of memory during the conversion process. Haven't gone all the way into it, but it looks like it enabled a flag that already existed in deeper function calls. Does anything like this exist in mlx?

**Comment by awni** [comment]
We don't really need this as it's mostly handled in `mlx_lm.convert` with sharding + lazy loading. The OS will also use swap (e.g. disk/flash) if needed by default.

I wrote a little post about how it works in slightly more detail here: https://x.com/awnihannun/status/1773185727997825406
