### ISSUE TITLE
Mistral is not working on M1 pro !!!

### ISSUE THREAD

**Issue by muditbhargava66** [ml-explore/mlx-examples#72]
For me, the output gets stuck for the given example as well as for the other prompts.

```bash
[INFO] Loading model from disk.
[INFO] Starting generation...
It is a truth universally acknowledged,
```

**Comment by awni** [comment]
Yea probably you are running into RAM issues if you have < 24GB (see #38). We are working on quantization / efficiency to address this. Feel free to comment here if you think it is a different issue.

**Comment by muditbhargava66** [comment]
Yes, i have 16 GB RAM.
