### ISSUE TITLE
Model type openelm not supported

### ISSUE THREAD

**Issue by mobile-appz** [ml-explore/mlx-examples#723]
When attempting to run the example code below for OpenELM, found on Hugging Face, there is an error "ValueError: Model type openelm not supported". It says "ModuleNotFoundError: No module named 'mlx_lm.models.openelm'"

```
from mlx_lm import load, generate
model, tokenizer = load("mlx-community/OpenELM-1_1B-instruct-4bit")
```

**Comment by awni** [comment]
There is an outstanding PR for this https://github.com/ml-explore/mlx-examples/pull/719

**Comment by duranbe** [comment]
For Posterity - Make sure to get the last release of mlx-lm when trying openELM 

``` pip install --upgrade mlx_lm```
