### ISSUE TITLE
[Feature request] A version of mlx_lm.utils.generate() that acts as an iterator

### ISSUE THREAD

**Issue by simonw** [ml-explore/mlx-examples#728]
This function here:

https://github.com/ml-explore/mlx-examples/blob/c012eb173f0f632e369ec71f08be777df3aede08/llms/mlx_lm/utils.py#L197-L281

Currently it prints tokens using `print()` as it runs, or it can pass them to a `formatter()` callable.

I'd really like it if there was a version of this function that acted like an iterator/generator instead, so I could do something like this:

```python
for chunk in generate(model="...", prompt="prompt goes here"):
    print(chunk, end="")
```
I can build it myself by copying and pasting code from the `generate()` function, but it would be more convenient if the `mlx_lm.utils` module provided that for me. The existing `generate()` function could even be refactored to use the new iterator-based one.

**Comment by awni** [comment]
What do you think about using [`generate_step`](https://github.com/ml-explore/mlx-examples/blob/c012eb173f0f632e369ec71f08be777df3aede08/llms/mlx_lm/utils.py#L113)? It's almost the same as `generate` but it doesn't check the stopping criteria or print anything.

Is there something you want in the iterator that `generate_step` doesn't do? `generate_step` is kind of intended to be more flexible to be used as an iterator and leave more control to the caller (e.g. around when to stop / when to print / etc).

**Comment by awni** [comment]
Closing as inactive.
