### ISSUE TITLE
Phi 3 mini 4k , 128k does nor work LORA

### ISSUE THREAD

**Issue by kishoretvk** [ml-explore/mlx-examples#733]
LORA  fine tuning does not work for phi 3 models  using LORA , 
For mistral 7b when giving  all parameters 
Other than 
Model 
Dataset 
Batch size 
Iterations 

I see Nan for val  ( using  LORA)

**Comment by awni** [comment]
Could you share the command you ran that produced the NaN?

**Comment by awni** [comment]
I ran the following for 1K iterations and did not see a NaN:
```
python -m mlx_lm.lora --model microsoft/Phi-3-mini-4k-instruct --train --data ../lora/data --iters 1000
```

Closing for now. If you share a command that repros NaN then we can reopen and investigate.
