### ISSUE TITLE
generate mlx-community/Meta-Llama-3-70B-Instruct-4bit doesn't halt at <|eot_id|>

### ISSUE THREAD

**Issue by kechan** [ml-explore/mlx-examples#737]
```
from mlx_lm import load, generate
message = "What is the capital of France?"
prompt = tokenizer.apply_chat_template([{'role': 'user', 'content': message}], tokenize=False)
print(prompt)
```
the prompt printed:
<|begin_of_text|><|start_header_id|>user<|end_header_id|>
What is the capital of France? <|eot_id|>

I used the HG chat template helper to generate this. However, when I run 

```
response = generate(model, 
                    tokenizer, 
                    prompt=prompt, 
                    temp=0.5, 
                    verbose=True, 
                    max_tokens=100, 
                    top_p=0.85,
                    repetition_penalty=1.5
                    )
```

it doesnt halt at <|eot_id|>, assuming this is indeed the right "end of text" for this model tokenizer. A little debug inside generate (at mlx_lm.utils.py), it seems to be hardcoded like:

```
if token == tokenizer.eos_token_id:
      break
```

so I decided to do a hack:

```
if token == tokenizer.encode('<|eot_id|>')[0]:
    break
```

I am not familiar with the usual convention how HF or mlx handle this, is this something that should be fixed? or there's something wrong with the way I use tokenizer.apply_chat_template?

**Comment by kechan** [comment]
A better "hack":

tokenizer.eos_token_id = tokenizer.encode('<|eot_id|>')[0]

Or I found out one can just fix the config json, but this requires me to do this every time I update the module, so the above is better for my case since I can just adjust this at runtime.

**Comment by awni** [comment]
I think if we update the special tokens map it should work. I just changed it to be `<|eot_id|>` here https://huggingface.co/mlx-community/Meta-Llama-3-70B-Instruct-4bit/blob/main/special_tokens_map.json#L10

**Comment by plurch** [comment]
Yes I meant the server cli, it could be a useful fix. Thanks!
