### ISSUE TITLE
MNIST Example Error: 403 Forbidden

### ISSUE THREAD

**Issue by AKLABZ** [ml-explore/mlx-examples#748]
MNIST isn't MNIST-ing like it used to..

Encountering an issue while trying to access/download the MNIST dataset using the provided Python code. To reproduce the error, simply navigate to the `mlx-examples/mnist` directory and run the following command: `python main.py`

My Silly Workaround:
I was able to modify the `mnist.py` file to load the datasets from a local directory, which did end up solving this issue. Since this doesn't seem isolated to MLX specifically (I came across several workarounds for PyTorch and TensorFlow, for example), it may not be mendable by the MLX team.

Possible Long-term Solution:
Updating the `base_url` argument in the `mnist.py` file to a more reliable 3rd-party host could be worth it. I haven't tried this solution since I already had the dataset saved from another project, but I don't see why it wouldn't work. The only problem I can think of would be an ethical one, where Apple isn't directly sourcing the data from the official publisher.

Regardless, this isn't a major issue, and the impact is negligible. I just figured it was worth taking a look at for people simply exploring the provided examples or for anyone who might be trying to implement MLX into their own projects.

**Comment by awni** [comment]
Yes this has been an issue lately. Changed the URL to something more stable in 749

**Comment by AKLABZ** [comment]
@awni sorry for creating a new issue, I swear I looked through the repo for this but couldn't find anything. Thanks x10

**Comment by AKLABZ** [comment]
> Yes this has been an issue lately. Changed the URL to something more stable in 749

sorry for creating a new issue, I swear I looked through the repo for this but couldn't find anything. Thanks x10

**Comment by awni** [comment]
I just made that PR right after you filed the issue ;)

**Comment by AKLABZ** [comment]
this tomfoolery will not stand!
