### ISSUE TITLE
[Feature Request] When generating using mlx_lm, specify data format

### ISSUE THREAD

**Issue by konarkm** [ml-explore/mlx-examples#761]
Regarding [llms/mlx_lm/LORA.md](https://github.com/ml-explore/mlx-examples/blob/main/llms/mlx_lm/LORA.md)

The instructions specify chat, completions, and text for the dataset. However in the [Generate](https://github.com/ml-explore/mlx-examples/blob/main/llms/mlx_lm/LORA.md#generate) usage there aren't instructions for how to use one of those three formats.
For example, I'm not sure how I would add a system prompt as well as a user message when calling the mlx_lm.generate command.

Not sure if this is something that is supported but not documented in LORA.md, or maybe I missed something!

**Comment by awni** [comment]
So usually in generate it uses the models default chat template (so it's a chat). You can use the raw prompt (so it's just the tests) by specifying `--ignore-chat-template`.  There is currently no way to do the `completion` version in the CLI. But if you use the API you could do it like this:


```python
from mlx_lm import load, generate

model, tokenizer = load("mistralai/Mistral-7B-Instruct-v0.1")

prompt = ""
completion = ""

text = tokenizer.apply_chat_template(
    [
        {"role": "user", "content": prompt},
        {"role": "assistant", "content": completion},
    ],
    tokenize=False,
    add_generation_prompt=True,
)

response = generate(model, tokenizer, prompt=text)
```

**Comment by konarkm** [comment]
I see, thank you!

In case it helps anyone down the line:
My goal was to generate using fine tuned adapters, as well as with a system prompt and user prompt in the chat format.

Based on generate.py and utils.py, I load the model with the adapters like this:
```
from mlx_lm import load, generate

model_repo = "mlx-community/Meta-Llama-3-8B-Instruct-4bit"
adapter_path = "/adapters"

model, tokenizer = load(model_repo, adapter_path=adapter_path)
```

Then, I can generate:

```
system_prompt = "Be a helpful assistant"
prompt = "Hey, tell me about Llama"

text = tokenizer.apply_chat_template(
    [
        {"role": "system", "content": system_prompt},
        {"role": "user", "content": prompt},
    ],
    tokenize=False,
    add_generation_prompt=True,
)

response = generate(model, tokenizer, prompt=text, verbose=True)
```

**Comment by chigkim** [comment]
Still it would be very convenient if users can specify system prompt with mlx_lm.generate! Something like --system flag. That way users don't have to rely on Python or mess with raw prompt template which can sometimes get complicated.

**Comment by awni** [comment]
Added in #1100
