### ISSUE TITLE
KV Cache can only process more than self.step tokens if offset % step == 0

### ISSUE THREAD

**Issue by ianbulovic** [ml-explore/mlx-examples#765]
It seems like the current implementation of KVCache only expands when `offset % step == 0`. This works great for the standard generation use case where the prompt is processed first, then inference is one token at a time. However, it can cause issues when more than one token is processed in subsequent steps.

I'm working on a project where I'm reusing a large portion of a prompt, so I'm trying to precompute a KVCache for e.g. the first 200 tokens, then append an additional 100 tokens to the prompt, and continue evaluation using the precomputed cache. However, this causes an error because the cache is not large enough to accommodate the additional 100 tokens, and does not expand because the offset is not a multiple of step.

The error can be reproduced with the following code:
```python
import mlx.core as mx
from mlx_lm import load
from mlx_lm.models.base import KVCache

# load the model
model, tokenizer = load("mistral-7b-instruct-0.2-q4")

# create cache
cache = [KVCache(model.head_dim, model.n_kv_heads) for _ in range(len(model.layers))]

# ingest a single token, so offset is 1
token = [1]
x = mx.array(token)
model(x[None], cache=cache)

# this works, 255 tokens can fit in the cache
x = mx.array(token * 255)

# this fails, 256 tokens are too much
# x = mx.array(token * 256)

model(x[None], cache=cache)
```

Thanks so much for all your hard work on this project!

**Comment by awni** [comment]
#766 should fix this. LMK if it does not work for you.

**Comment by ianbulovic** [comment]
Works like a charm, thanks for the quick fix!
