### ISSUE TITLE
Enhance load function to support model configuration editing

### ISSUE THREAD

**Issue by JosefAlbers** [ml-explore/mlx-examples#771]
The current implementation of the `load` function lacks the flexibility to adjust specific configuration parameters. I propose enhancing the `load` function to support a `model_config` parameter, enabling users to modify these parameters dynamically upon loading a model. For example, this enhancement would allow increasing the context window with position interpolation or adjusting the base frequency of RoPE on the fly.

Recent advancements in language model research have introduced techniques that can significantly enhance the capabilities of base language models (LLMs) without requiring additional fine-tuning. By enabling dynamic model configuration adjustments with the `model_config` parameter, users can leverage these techniques seamlessly within our framework.

**Related Pull Request:** #770

**Comment by awni** [comment]
Added in #770
