### ISSUE TITLE
Support for full set of output formats - e.g. vtt, json and json-full 

### ISSUE THREAD

**Issue by stephenmcconnachie** [ml-explore/mlx-examples#772]
The speed benefits over whisper.cpp on Apple GPU are amazing, but I believe only text / segments / words output format is currently supported.

It would be amazing if the set of outputs that whisper.cpp supports, could be added to lightning-whisper-mlx - especially the vtt, json and json-full outputs.

Docs at whisper.cpp repository:
https://github.com/ggerganov/whisper.cpp/blob/73d13ad19a8c9c4da4f405088a85169b1a171e66/README.md?plain=1#L124

**Comment by awni** [comment]
I would recommend you file an issue to lightning-whisper-mlx unless there is something we need to change here to enable support of that?

**Comment by stephenmcconnachie** [comment]
Thank you - I've raised an issue there.

**Comment by awni** [comment]
We have these [now via the CLI](https://github.com/ml-explore/mlx-examples/tree/main/whisper#cli)
