### ISSUE TITLE
Fine tuned a Mixtral-8x7B-Instruct-v0.1 model and unable to load with AutoModelForCausalLM

### ISSUE THREAD

**Issue by chimezie** [ml-explore/mlx-examples#777]
I originally fine-tuned a Mixtral-8x7B-Instruct-v0.1 model by:

1. Locally 4-bit / float32  quantizing **mistralai/Mixtral-8x7B-Instruct-v0.1** from the HF hub
2. QLoRA training adapters against the resulting model
3.  Fusing them with ```mlx_lm.fuse --model /local/model/from/step1 --save-path /local/fused/model --adapter-path /local/path/to/adapters```

When I try:

```python
from transformers import AutoModelForCausalLM; import torch
AutoModelForCausalLM.from_pretrained('/local/fused/model', device_map="mps")
```

I get:

```
ValueError: Trying to set a tensor of shape torch.Size([32000, 512]) in "weight" (which has shape torch.Size([32000, 4096])), this look incorrect.
```

I then tried fusing the adapters with **mlx-community/Mixtral-8x7B-Instruct-v0.1-4bit**,  removing everything from /local/fused/model  beforehand

```bash
$ mlx_lm.fuse --model mlx-community/Mixtral-8x7B-Instruct-v0.1-4bit \
              --save-path /local/fused/model --adapter-path /local/path/to/adapters
```

But get the same error loading /local/fused/model .

**Comment by awni** [comment]
I think you need to dequantize to use the model with Transformers. Pass `--de-quantize` when you fuse the model.

Let me know if that's not the issue and we can re-open.
