### ISSUE TITLE
OS system requirement for mlx

### ISSUE THREAD

**Issue by palLiHua** [ml-explore/mlx-examples#785]
My os system is 13.0, and I have tried mlx v0.13 to mlx v0.7, it all reports:
libmlx.dylib (built for macOS 13.5 which is newer than running OS)

I wonder how could I find out the requirements for os system under different version of mlx, cause later on my model may be run on another machine, whose os system is probably different from mine.

**Comment by awni** [comment]
Sorry I missed this. MLX works on macOS 13.5 and greater, you can find it [in the documentation](https://ml-explore.github.io/mlx/build/html/install.html#python-installation).
