### ISSUE TITLE
Request for Example on Full Parameter and Training for LLM Model

### ISSUE THREAD

**Issue by arthasyou** [ml-explore/mlx-examples#796]
Hi,

Could you please provide an example of a large language model (LLM) with full parameters and training?

This would be incredibly helpful for understanding how to effectively train and utilize LLMs within the MLX framework.

Thank you very much!

**Comment by awni** [comment]
> full parameters and training?

Do you mean fine-tuning all the parameters of an LLM? There is a PR for that you could check out if so: #645

**Comment by arthasyou** [comment]
Not fine-tuning. I mean pre-train the model.

**Comment by awni** [comment]
> Like llama model, I want to add some tokens and retrain it.

Based on your comment it sounds like you want to fine tune the model. But are you saying you want an example which trains something like a Llama model from scratch? That is very computationally expensive.

**Comment by arthasyou** [comment]
Yes. Because mac studio is much cheaper than nvida
On a Mac with 192G memory, I want to try to see if I can train a model like llama from scratch.
