### ISSUE TITLE
Mixtral weights to MLX

### ISSUE THREAD

**Issue by ptogias** [ml-explore/mlx-examples#83]
Hi,

First of all thank you so much for introducing mlx. 

I was looking at the Mixtral `convert.py` code and I think that line 19

```state = torch.load(str(model_path / "consolidated.00.pt"))``` 

should be 

```state = torch.load(str(model_path / "consolidated.00.pth"))```

Combine part from readme:
```
cd mixtral-8x7b-32kseqlen/
cat consolidated.00.pth-split0 [...] consolidated.00.pth-split10 > consolidated.00.pth
```

**Comment by casbeebc** [comment]
Fixed in https://github.com/ml-explore/mlx-examples/pull/84

**Comment by awni** [comment]
Sorry about that !
