### ISSUE TITLE
mlx_lm stops generating

### ISSUE THREAD

**Issue by stefanvarunix** [ml-explore/mlx-examples#836]
Hardware:
Mac Studio M1 Ultra, 128 GB.

Problem:
mlx_lm stops generating unexpectedly.
Model: Mixtral 8x22b 4bit (https://huggingface.co/mlx-community/Mixtral-8x22B-Instruct-v0.1-4bit)

Command:
`python3 -m mlx_lm.generate --model ../mlx_models/Mixtral-8x22B-Instruct-v0.1-4bit --prompt "Hi! Tell a long story"
`

Result:
```
==========
Prompt: <s> [INST] Hi! Tell a long story [/INST]
Once upon a time, in a land far, far away, there was a small village named Harmonia. This village was unique because it was home to people of all different races, religions, and backgrounds. Despite their differences, the villagers of Harmonia lived in harmony and worked together to create a peaceful and prosperous community.

In the heart of Harmonia, there was a wise old man named Alaric. Alaric was the village elder and was known for
==========
```

The problem is reproducible multiple times, including using the server `python3 -m mlx_lm.server`

I restartet the computer, tried some older versions of mlx_lm etc. Nothing helped.

**Comment by awni** [comment]
I think you just need to specify `--max-tokens <some large number>`. The default is 100.

You can always see supported options and their meaning by doing `mlx_lm.generate --help`
