### ISSUE TITLE
lora resume error

### ISSUE THREAD

**Issue by l0d0v1c** [ml-explore/mlx-examples#841]
command:

python -m mlx_lm.lora --model ./Phi-3-mini-128k-instruct --adapter-path adapters-pluc100 --resume-adapter-file adapters-pluc100 --data ./data-pluc100  --train --iters 200 --lora-layers 8

worked in previous version (0.14) but now it gives with 0.14.3

File "/Users/pro/mambaforge/envs/torch/lib/python3.11/site-packages/mlx_lm/lora.py", line 173, in train_model
    print(f"Loading pretrained adapters from {resume_adapter_file}")
                                              ^^^^^^^^^^^^^^^^^^^
NameError: name 'resume_adapter_file' is not defined

**Comment by shenshuihai01** [comment]
me too

**Comment by awni** [comment]
This is fixed on main. We will do a release soon with the update.
