### ISSUE TITLE
gpt-neox

### ISSUE THREAD

**Issue by aPaleBlueDot** [ml-explore/mlx-examples#847]
Hi, 
Are there any plans to support gpt-neox models? HF has quite a few useful models based on this architecture. 
Cheers.

**Comment by meirm** [comment]
I would also like to see support to it. Is there a work around in the meantime? like converting them to another format?

**Comment by awni** [comment]
GPT-NeoX landed in MLX LM. We will do a new dist soon to update the package. I will close this for now.

Regarding support for Swift. If that is still of interest, please file an issue against the [MLX Swift example repo](https://github.com/ml-explore/mlx-swift-examples).
