### ISSUE TITLE
Feature Request - Generate function, which returns response and logprobs for the response?

### ISSUE THREAD

**Issue by Pa-Sto** [ml-explore/mlx-examples#862]
Hello,

I would like to make an analysis of the response of LLMs and see what words are considered for each answer. So that the generate function can return additionally the logprobs which hold the raw softmax output over the vocabulary and not only the highest probable word so that we can use it in a simple way:

_from mlx_lm import load, generate

model, tokenizer = load("mlx-community/Mistral-7B-Instruct-v0.3-4bit")

response, logprobs = generate(model, tokenizer, prompt="hello", verbose=True, return_logprobs=True)_

Help would be greatly appreciated!

**Comment by awni** [comment]
This can be done with a fairly simple wrapper around `generate_step` like so:

```
import mlx.core as mx
from mlx_lm.utils import generate_step

def generate_with_logprobs(model, tokenizer, prompt, max_tokens, **kwargs):
    prompt_tokens = mx.array(tokenizer.encode(prompt))
    detokenizer = tokenizer.detokenizer

    detokenizer.reset()
    all_logprobs = []
    for (token, logprobs), n in zip(
        generate_step(prompt_tokens, model, **kwargs),
        range(max_tokens),
    ):
        if token == tokenizer.eos_token_id:
            break
        detokenizer.add_token(token)
        all_logprobs.append(logprobs)

    detokenizer.finalize()
    return detokenizer.text, all_logprobs
```

You can use that for now (?). I will look into if it makes sense to add it as an option. Generally I think we prefer making these functions easy to extend / customize rather than providing lot's of configurations params. But any feedback on that point would be useful.

**Comment by Pa-Sto** [comment]
Thanks for the quick help! Yes, this works for my purpose for now :)
