### ISSUE TITLE
LoRA  tune ibm geanite 8b insteuct 

### ISSUE THREAD

**Issue by kishoretvk** [ml-explore/mlx-examples#864]
IbM granite 7b or 8b 
Fails to work, throws error saying model type not supported 
Used LORA.py

**Comment by kishoretvk** [comment]
Inference works fine 
LoRA does not work though

**Comment by awni** [comment]
You'd need to use MLX LM for that. So concretely:

1. `pip install -U mlx-lm`
2. `mlx_lm.lora --train --model  mlx-community/granite-3b-code-base-4bit --data <path/to/data> --batch-size 4 --iters 10`        

[More documentation here](https://github.com/ml-explore/mlx-examples/blob/main/llms/mlx_lm/LORA.md)
