### ISSUE TITLE
Unlike the document, the code here didn't force a graph evaluation for the optimizer's parameters.

### ISSUE THREAD

**Issue by baixianger** [ml-explore/mlx-examples#869]
https://github.com/ml-explore/mlx-examples/blob/1e05aef344907d2697f82b3a5b5c00cdf21c298c/mnist/main.py#L82

In your document, I found the code in the tutorial is, 
```
        mx.eval(model.parameters(), optimizer.state)
```
It looks like you didn't force a graph evaluation for the optimizer's parameters.

What's the different?

**Comment by awni** [comment]
Since it's just SGD there, the optimizer doesn't have any state. In general it's good practice to eval the `optimizer.state`.
