### ISSUE TITLE
Can mlx_lm.fust model convert to Huggingface model？

### ISSUE THREAD

**Issue by 100ZZ** [ml-explore/mlx-examples#872]
1. mlx_lm.lora huggingface model
2. mlx_lm.fuse adapters+huggingface model=new model

this new model can only run as MLX？can convert to huggingface format？

**Comment by awni** [comment]
It depends on two things really:

1. The model type. For most models we don't change the weight dictionary so they are compatible with both MLX and Hugging Face. There are some exceptions like MOEs where we have to change the underlying weights for efficiency reasons.
2. The precision. If the fused model is in 16-bit (float of bfloat) then it should work with Hugging Face. If it is quantized then that is MLX specific.
