### ISSUE TITLE
gemma-2-27b-it-4bit generate only <pad>

### ISSUE THREAD

**Issue by katopz** [ml-explore/mlx-examples#876]
Run
```
python3 -m venv .venv                  
source .venv/bin/activate
python3 -m pip install -U mlx-lm
python3 -c "import mlx_lm; print(mlx_lm.__version__)"

MODEL=mlx-community/gemma-2-27b-it-4bit
python3 -m mlx_lm.generate --model ${MODEL} --prompt "hello"
```

Get
```
0.15.0
None of PyTorch, TensorFlow >= 2.0, or Flax have been found. Models won't be available and only tokenizers, configuration and file/data utilities can be used.
Fetching 9 files: 100%|███████████████████████| 9/9 [00:00<00:00, 179755.89it/s]
==========
Prompt: <bos><start_of_turn>user
hello<end_of_turn>
<start_of_turn>model

<pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad>
==========
Prompt: 22.225 tokens-per-sec
Generation: 21.883 tokens-per-sec
```

Refer to: https://huggingface.co/google/gemma-2-27b-it/discussions/16
I guess i will need `torch_dtype=torch.bfloat16` but I'm not sure where to or how to do it?
Or maybe I miss something.

Thanks

**Comment by ElviiAi** [comment]
Having the exact same issue, although I converted it to 8bit with group size of 32 (`mlx_lm.convert --hf-path . --quantize  --q-group-size 32 --q-bits 8`) first, thought that may have been the issue.

If it helps, it also seems to be a case that the model gets "stuck". Took a long time, unfortunately didn't time it, but about 20mins to generate output, yet the t/s log at the end is about as expected - codestral at 22bn generates at ~13t/s with the same prompt.

Model output:
```
<start_of_turn>model

<pad>...<pad>
```

Note also the number of `<pad>` tokens == `--max-tokens` I've set (8192). And below is the incorrect (but expected t/s for M2Max w/ 96GB RAM)

T/s:

```
Prompt: 149.805 tokens-per-sec
Generation: 8.055 tokens-per-sec
```

Haven't had time to dig deeper but hope this helps!

**Comment by ElviiAi** [comment]
Ah just noticed @katopz above also used a quantised model. Went back to double check and the below works, so seems to be an issue with the quantisation rather than the model fix implementation, as the code below works just fine:

`mlx_lm.generate --trust-remote-code --model . --prompt "Write me a game of Tetris in python" -m 8192`

(P.S. @katopz you can download and convert the model to MLX directly using `mlx_lm.convert --hf-path <model_path> --dtype bfloat16`)

**Comment by awni** [comment]
There was an issue with Gemma 27B generations that was fixed recently but has not been deployed to PyPi. Let me send a patch distribution and this should be resolved.

**Comment by awni** [comment]
Relevant PR: https://github.com/ml-explore/mlx-examples/pull/857

**Comment by awni** [comment]
Ok, I just sent 15.1 to PyPi. You can `python -m pip install -U mlx-lm` and the model should work much better now. I'm closing this but lmk if you still have any issues.

**Comment by ElviiAi** [comment]
I've built from source yesterday, so I don't think its related (running `mlx-0.15.2.dev20240706+20bb3011`) @awni 

Just doing a sanity check now but its already taking longer (struck at the output below - I guess the `<pad>`'s will again take a while to come out) at 8bit than it at bfloat16. 

```
mlx_lm.generate --trust-remote-code --model . --prompt "Write me a game of tetris in python" -m 8192
==========
Prompt: <bos><start_of_turn>user
Write me a game of tetris in python<end_of_turn>
<start_of_turn>model
```

After quantising (again, for comparison codestral with the same prompt and quant. parameters is fast at ingesting the prompt):

```
mlx_lm.convert --hf-path . --quantize  --q-group-size 32 --q-bits 8
[INFO] Loading
[INFO] Quantizing
```

Something odd with quantising the model I think, sorry can't be of much more help - I've only just started playing around with MLX.

**Comment by ElviiAi** [comment]
Correction; output duration is related to `--max-tokens`, but every token after quantising is `<pad>`:

```
mlx_lm.generate --trust-remote-code --model . --prompt "Write me a game of tetris in python" -m 50
==========
Prompt: <bos><start_of_turn>user
Write me a game of tetris in python<end_of_turn>
<start_of_turn>model

<pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad>
==========
Prompt: 27.031 tokens-per-sec
Generation: 11.106 tokens-per-sec
```

**Comment by awni** [comment]
> I've built from source yesterday, so I don't think its related

This is related to MLX LM, not MLX. So `pip install -U mlx-lm` should fix it.

**Comment by ElviiAi** [comment]
Ah, understood. Was a little confused with how the two work together. Thanks!

**Comment by ElviiAi** [comment]
Thanks for the clarification and sorry to resurrect this again, @awni. I appreciate your quick response and the update to PyPi. I'd like to share my experience trying to build MLX-LM from source, as it might be helpful for others and could highlight some areas for potential documentation improvement.

I found a method (without obvious sources in the docs, unless I totally missed them - my bad in that case - but I did a bit googling and looking through the docs in mlx-examples) for compiling MLX-LM from source. Here's the zsh snippet I used:

```zsh
#!/bin/zsh

git clone https://github.com/ml-explore/mlx-examples.git
cd mlx-examples/llms

git clone https://github.com/ml-explore/mlx.git
cd mlx
pip install git+https://github.com/wjakob/nanobind.git@2f04eac452a6d9142dedb957701bdb20125561e4
env CMAKE_BUILD_PARALLEL_LEVEL="" pip install -e .
cd ..

pip install -r requirements.txt
pip install -e .

python -m unittest discover tests
```

I was a bit confused about building MLX-LM from source, as the documentation isn't as clear as it is for MLX. I'm wondering if there might be any downsides to this approach, especially considering MLX-LM (`mlx-lm==0.16.0` when build from source) might be ahead in versioning compared to MLX currently.

In addition, when running the tests, I encountered the following error:

```
ERROR: test_hf (test_datsets.TestDatasets.test_hf)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/jaro/dev/mlx-examples/llms/tests/test_datsets.py", line 90, in test_hf
    train, valid, test = datasets.load_dataset(args, tokenizer)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jaro/dev/mlx-examples/llms/mlx_lm/tuner/datasets.py", line 97, in load_dataset
    import datasets
ModuleNotFoundError: No module named 'datasets'

----------------------------------------------------------------------
Ran 41 tests in 18.878s

FAILED (errors=1, skipped=1)
```

It seems the 'datasets' module is missing (note that MLX is already installed in that conda env, having built it from source using pip) - I'm guessing this is the downside of installing a non-release version, but just in-case you were not aware!

I'm curious if documenting the process of building MLX-LM from source might be beneficial for the community. It could help users like me who are trying to ensure version parity between MLX and MLX-LM when working with development versions (and perhaps a dev build too).

Thanks again for your work on this project. I'm excited to continue exploring MLX-LM and would be happy to provide any additional information that might help improve the documentation or installation process.

Its just that you guys and girls are rolling out efficiency/compatibility improvements are so fast that its one of those libraries I'd like to compile from source while developing.

(P.S: I've at least tested the source compilation `mlx-lm==0.16.0` with Gemma2 and it work just as well as `mlx-lm==0.15.2 on PyPi)

**Comment by awni** [comment]
> especially considering MLX-LM (mlx-lm==0.16.0 when build from source) might be ahead in versioning compared to MLX currently

The versions aren't tied. It's just a coincidence that they are at similar version numbers right now.

> In addition, when running the tests, I encountered the following error:

Indeed we have extra requirements that are needed for running the tests. I'll need to setup the build documentation to add those.

> I'm curious if documenting the process of building MLX-LM from source might be beneficial for the community

Yes some docs there would be handy. It should be very simple to do:

1. Clone the repo and `cd llms`
2. `pip install .`

For running the tests we'd need to add an extra install for `datasets` but that should be a fix on the packaging side.

**Comment by davideuler** [comment]
mlx-lm 0.18.2  works on my mac for gemma-2-27b-it-8bit.
pip install mlx-lm==0.18.2

**Comment by my-other-github-account** [comment]
This is broken again in mlx-lm >= 0.19.1 - I am on 0.20.5 and only get <pad>.

**Comment by awni** [comment]
Yea.. actually the 27B model has issues with fp16.. IIRC I dug into this and it was overflowing in some of the matmuls in the MLP. We should deprecate the fp16 quantst. You can use the bf16 quants instead they should work and be about the same speed. E.g. use `mlx-community/gemma-2-27b-it-bf16-4bit`

**Comment by prabhu** [comment]
Thank you. Passing `--dtype bfloat16` fixes this issue.
