### ISSUE TITLE
Finetuning gemma-2-27b-8bits error

### ISSUE THREAD

**Issue by l0d0v1c** [ml-explore/mlx-examples#881]
I try to finetune (16 layers and 8 layers) https://huggingface.co/mlx-community/gemma-2-27b-it-8bit with a M2Max 96Gb but I get this error after the first step.

```
Loading pretrained model
Loading datasets
Training
Trainable parameters: 0.007% (1.966M/27227.128M)
Starting training..., iters: 600
Iter 1: Val loss 2.829, Val took 195.727s
libc++abi: terminating due to uncaught exception of type std::runtime_error: [METAL] Command buffer execution failed: Internal Error (0000000e:Internal Error)
mlx-finetune.sh: line 38:  9824 Abort trap: 6
```

**Comment by awni** [comment]
Unfortunately this is a known issue without a simple fix. You can see [comments here](https://github.com/ml-explore/mlx-examples/issues/866#issuecomment-2210920025) for some possible work-arounds. 

Closing this for now as a dup of https://github.com/ml-explore/mlx/issues/1231.
