### ISSUE TITLE
When I use mlx-community/clip-vit-base-patch32, the bug "FileNotFoundError: No safetensors found in mlx_model" happens.

### ISSUE THREAD

**Issue by QianboZang** [ml-explore/mlx-examples#896]
Dear Sir or Madam,

Hi, I follow your tutorial for "mlx-community/clip-vit-base-patch32".

```
model, tokenizer, img_processor = clip.load("mlx_model")
```
has a bug "FileNotFoundError: No safetensors found in mlx_model".

Here is the folder of mlx_model, which is download by: 
```
pip install huggingface_hub hf_transfer

export HF_HUB_ENABLE_HF_TRANSFER=1
huggingface-cli download --local-dir <LOCAL FOLDER PATH> mlx-community/clip-vit-base-patch32
```
<img width="260" alt="截屏2024-07-19 11 13 36" src="https://github.com/user-attachments/assets/cfbb0c2f-1491-45b5-b6e6-02bb1f2d9fdc">

Can you tell me how to fix this problem?

Best,

**Comment by awni** [comment]
The `clip/` example only works with `safetensors`. You can convert this one `openai/clip-vit-base-patch32`  following the [instructions in the README](https://github.com/ml-explore/mlx-examples/tree/main/clip#readme)
