### ISSUE TITLE
 install mlx-lm version 0.16.0 : ERROR: Could not find a version that satisfies the requirement mlx-lm==0.16.0

### ISSUE THREAD

**Issue by Jason-Chen-2017** [ml-explore/mlx-examples#901]
The Model [mlx-community/Mistral-Nemo-Instruct-2407-8bit](https://huggingface.co/mlx-community/Mistral-Nemo-Instruct-2407-8bit) was converted to MLX format from [mistralai/Mistral-Nemo-Instruct-2407](https://huggingface.co/mistralai/Mistral-Nemo-Instruct-2407) using mlx-lm version 0.16.0.

But:

pip install mlx-lm==0.16.0   

ERROR: Could not find a version that satisfies the requirement mlx-lm==0.16.0 (from versions: 0.0.1, 0.0.2, 0.0.3, 0.0.5, 0.0.6, 0.0.7, 0.0.8, 0.0.9.dev0, 0.0.9, 0.0.10, 0.0.11, 0.0.12, 0.0.13, 0.0.14, 0.1.0, 0.2.0, 0.3.0, 0.4.0, 0.5.0, 0.6.0, 0.7.0, 0.8.0, 0.9.0, 0.10.0, 0.11.0, 0.12.0, 0.12.1, 0.13.0, 0.13.1, 0.14.0, 0.14.1, 0.14.2, 0.14.3, 0.15.0, 0.15.1, 0.15.2, 0.15.3)
ERROR: No matching distribution found for mlx-lm==0.16.0

**Comment by awni** [comment]
I just uploaded the 0.16.0 distribution to PyPi, it should work now.
