### ISSUE TITLE
rope_scaling errors when loading Llama-3.1-8B-Instruct

### ISSUE THREAD

**Issue by cdrouin** [ml-explore/mlx-examples#909]
Hey all. I have a project that's been working well with Llama-3-8B-Instruct, and I figured I'd drop version 3.1 in to take advantage of the larger context window. It throws an exciting new error when trying to load the model:

```File "/opt/homebrew/Caskroom/miniconda/base/lib/python3.10/site-packages/mlx_lm/utils.py", line 385, in load
    model = load_model(model_path, lazy)
File "/opt/homebrew/Caskroom/miniconda/base/lib/python3.10/site-packages/mlx_lm/utils.py", line 322, in load_model
    model_args = model_args_class.from_dict(config)
File "/opt/homebrew/Caskroom/miniconda/base/lib/python3.10/site-packages/mlx_lm/models/base.py", line 9, in from_dict
    return cls(
File "<string>", line 14, in __init__
File "/opt/homebrew/Caskroom/miniconda/base/lib/python3.10/site-packages/mlx_lm/models/llama.py", line 31, in __post_init__
    raise ValueError(f"rope_scaling must contain keys {required_keys}")

ValueError: rope_scaling must contain keys {'type', 'factor'}
```

This known issues post for vLLM on Llama 3.1 may be relevant:

https://github.com/vllm-project/vllm/issues/6689

`type` missing from the dictionary may be because HuggingFace apparently renamed that key to `rope_type` for these models. Just guessing here, but it may also be necessary to implement other rope_scaling type(s here (the mlx codebase suggests only `linear` is supported and I guess this model may be `extended`).

Guess I will go back to standard Llama-3-8B-Instruct for now while this gets worked out.

**Comment by awni** [comment]
I think you just need to update MLX LM to 0.16.1

If that doesn’t solve your problem let us know

**Comment by cdrouin** [comment]
Confirmed that (and updating transformers) fixed it!

**Comment by sourceful-tolu** [comment]
@cdrouin - Facing the same issue trying to train a model on a M3 Mac. I just updated MLX LM and still the same snag! When you say "(and updating transformers)" what do you mean? Any pointers?

**Comment by awni** [comment]
What version of MLX LM do you use?

```
python -c "import mlx_lm; print(mlx_lm.__version__)"
```

Also could you share the error message you got?

**Comment by devanshg03** [comment]
I also have the same issue with MLX version 0.16.1 and having updated transformers.

**Comment by awni** [comment]
Just to be clear you  need to upgrade MLX LM (not MLX): `pip install -U mlx-lm`

**Comment by devanshg03** [comment]
> Just to be clear you need to upgrade MLX LM (not MLX): `pip install -U mlx-lm`

This worked, thank you so much. So the fix is to update mlx, mlx-lm and transformers.

**Comment by sourceful-tolu** [comment]
mlx_lm version - 0.16.1

Full error below:
`% python mlx-examples/lora/lora.py --model mlx-community/Meta-Llama-3.1-8B-Instruct-8bit \
                       --train \
                       --iters 100 \
                       --steps-per-eval 10 \
                       --val-batches -1 \
                       --learning-rate 1e-5 \
                       --lora-layers 16 \
                       --test
None of PyTorch, TensorFlow >= 2.0, or Flax have been found. Models won't be available and only tokenizers, configuration and file/data utilities can be used.
Loading pretrained model
Fetching 7 files: 100%|███████████████| 7/7 [00:00<00:00, 127100.12it/s]
Traceback (most recent call last):
  File "...../workspace/mlx-examples/lora/lora.py", line 336, in <module>
    model, tokenizer, _ = lora_utils.load(args.model, tokenizer_config)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "...../workspace/mlx-examples/lora/utils.py", line 149, in load
    model_args = models.ModelArgs.from_dict(config)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "...../workspace/mlx-examples/lora/models.py", line 40, in from_dict
    return cls(
           ^^^^
  File "<string>", line 14, in __init__
  File "...../workspace/mlx-examples/lora/models.py", line 33, in __post_init__
    raise ValueError(f"rope_scaling must contain keys {required_keys}")
ValueError: rope_scaling must contain keys {'type', 'factor'}`

I traced this through a debug run, I spotted that the self.rope_scaling object holds an entry `'rope_type' ='llama3'` (line 32 in models.py). I changed this locally to `'type' ='llama3'` then I get a different error that's expecting the value 'linear'. Full error for that below:

`None of PyTorch, TensorFlow >= 2.0, or Flax have been found. Models won't be available and only tokenizers, configuration and file/data utilities can be used.
Loading pretrained model
Fetching 7 files: 100%|██████████████████████████████████████████| 7/7 [00:00<00:00, 146070.29it/s]
Traceback (most recent call last):
  File "...../workspace/mlx-examples/lora/lora.py", line 336, in <module>
    model, tokenizer, _ = lora_utils.load(args.model, tokenizer_config)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "...../workspace/mlx-examples/lora/utils.py", line 149, in load
    model_args = models.ModelArgs.from_dict(config)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/mlx-examples/lora/models.py", line 40, in from_dict
    return cls(
           ^^^^
  File "<string>", line 14, in __init__
  File "...../workspace/mlx-examples/lora/models.py", line 36, in __post_init__
    raise ValueError("rope_scaling 'type' currently only supports 'linear'")
ValueError: rope_scaling 'type' currently only supports 'linear'`

**Comment by awni** [comment]
For LoRA you should use the MLX LM Lora:

`mlx_lm.lora <args here>`

[Here's the docs](https://github.com/ml-explore/mlx-examples/blob/main/llms/mlx_lm/LORA.md)

The lora in `examples/lora` is not actively updated and does not have wide model support.

**Comment by sourceful-wing** [comment]
thanks @awni that sounds good, but just noting that the Main README of this REPO points to the examples/lora so many people will end up there, if it is not actively updated, should there be a clearer warning/docs update?

**Comment by awni** [comment]
That's a good point. We should probably make a note in the README about it.

**Comment by origintopleft** [comment]
Hi,

Is this repository still maintained? The examples appear to be incompatible with modern MLX. I ended up having to call upstream directly using `python -m mlx_lm.lora --help`.

**Comment by awni** [comment]
Yup it's still maintained. You can use [mlx lm](https://pypi.org/project/MLx-lm) for LoRA / token generation.
