### ISSUE TITLE
Example of an async data-loader that automatically pre-fetches batches for training

### ISSUE THREAD

**Issue by vgoklani** [ml-explore/mlx-examples#924]
Our code is setup as follows:

```python
self.model.train(mode=True)

batch = next(train_iterator)

state = [self.model.state, self.optimizer.state]

@partial(mx.compile, inputs=state, outputs=state)
def step(input_ids: mx.array, targets: mx.array, lengths: mx.array):
    calculate_loss_and_grad_fn = nn.value_and_grad(self.model, loss_fn)

    (loss, number_tokens), grads = calculate_loss_and_grad_fn(
        self.model, input_ids, targets, lengths
    )

    clipped_grads, total_norm = optim.clip_grad_norm(
        grads, max_norm=self.args.grad_norm
    )

    self.optimizer.update(self.model, grads)

    return loss, number_tokens, total_norm

for train_step in range(self.args.train_steps):
    self.optimizer.learning_rate = self.get_learning_rate(step=train_step)

    loss, number_tokens, total_norm = step(
        batch["input_ids"], batch["targets"], batch["lengths"]
    )

    mx.eval(self.model.parameters(), self.optimizer.state, loss, total_norm)
    batch = next(train_iterator)
```

Unfortunately we are not saturating the GPU; I see 90-95% GPU usage from mactop.

We are building batches on the fly (as we do with pytorch) using an iterable-style dataset.

Is there a robust data-loader that pre-fetches batches and queues them up efficiently.

Looking for something that's equivalent to pytorch. Thanks!

**Comment by awni** [comment]
You could try something pretty simple like the following which prefetches data given an iterator in a separate process and puts it in a queue.

```python
import multiprocessing as mp

def prefetch(iterator):
    def f(iterator, queue):
        for sample in iterator:
            queue.put(sample)
    queue = mp.Queue(10)
    process = mp.Process(target=f, args=(iterator, queue))
    process.start()
    while True:
        sample = queue.get()
        yield sample
    process.join()
    
dataset = prefetch(dataset)
```

But I would recommend you perf first to see why you are not saturating the GPU. It may not have to do with data loading... a simple hack you can try is to use a dummy data batch that is fixed and see if that resolves the perf issues. That would point to data loading as worth fixing. Also 90-95% is not that bad.. I'm not sure how much headroom you have there.

I'm closing this as it's a bit outside the scope of MLX. But if you get evidence which suggests a performance bug or enhancement needed in MLX let us know.

**Comment by vgoklani** [comment]
@awni Thanks for the response!

We did end up writing a multi-*threaded* data-loader (presumably MLX drops the GIL) - we now hit a **constant** 98% on the GPU, which is pretty cool given that we are streaming over the files... the only drop is when we save checkpoints, which are not being saved async...
