### ISSUE TITLE
Update whisper/convert.py to save as safetensors instead of npz

### ISSUE THREAD

**Issue by thelastnode** [ml-explore/mlx-examples#938]
This will make it easier to load in Swift (where npz loading is currently supported).

Context from X: https://x.com/awnihannun/status/1824197443216609733

**Comment by CrispStrobe** [comment]
you can convert _from_ safetensors as illustrated here: https://github.com/CrispStrobe/mlx-examples/blob/main/whisper/convert_safetensors.py
