### ISSUE TITLE
Support for Phi-2 model

### ISSUE THREAD

**Issue by lostmygithubaccount** [ml-explore/mlx-examples#95]
I'd be interested in helping contribute this but would need some guidance. right now, it doesn't seem like other `convert.py` scripts will work out of the box

Microsoft has released the weights in `.safetensors` format on huggingface: https://huggingface.co/microsoft/phi-2/tree/main

would be great to be able to run this with MLX!

**Comment by awni** [comment]
Done!

**Comment by lostmygithubaccount** [comment]
PR for anyone interested: https://github.com/ml-explore/mlx-examples/pull/97

thanks for adding so quickly! looking forward to trying this
