### ISSUE TITLE
MNIST test accuracies differ drastically with --gpu flag on and off on Apple M3

### ISSUE THREAD

**Issue by yaoxingcheng** [ml-explore/mlx-examples#951]
I've installed the latest mlx (`mlx==0.17.0`) with pip in a conda environment. After running the mnist example with and without `--gpu`, I find the results differ drastically (and with gpu on it is somehow slower).
<img width="402" alt="image" src="https://github.com/user-attachments/assets/c9fb58d1-ad04-4e49-b2ae-ea5f97a1acf3">
I believe the test accuracy should be exactly the same.

Some of the context:
 - My OS Version: MacOS 14.5
 - MLX Version 0.17.0
 - My Chip: Apple M3
 - Complete conda info:
<img width="539" alt="image" src="https://github.com/user-attachments/assets/6d9d145c-a27c-40aa-b198-25d2c789308d">

**Comment by angeloskath** [comment]
It's a bug in boolean all reduce that was introduced by the reduction refactoring. Submitted a PR (https://github.com/ml-explore/mlx/pull/1355), it should be merged and released in a few minutes.

**Comment by angeloskath** [comment]
It is now fixed and PyPI updated, so please run `pip install -U mlx` and reopen if there is any issue.
