### ISSUE TITLE
Weird text generation with llama.py

### ISSUE THREAD

**Issue by JackxTong** [ml-explore/mlx-examples#953]
I have downloaded Llama-7B and 13B weights, and used llama/convert.py to convert the weights. I just want to give a simple prompt and see what happens.

When I tried `python3 mlx-examples/llms/llama/llama.py --prompt="hello"` with Llama-7B weights on my M1 mac, and get weird generation like this:

python3 mlx-examples/llms/llama/llama.py --prompt "how are you"
```
Loading model from mlx_model/weights.npz.
Press enter to start generation
------
how are you
?
 <SUF> <MID> <EOT> <PRE> <SUF>
e.


* 10. August – 11. August: 100. Geburtstag von Winston Churchill
* 11. August – 12. August: 100. Geburtstag von Winston Churchill
* 12. August – 13. August: 100. Geburtstag von
------
[INFO] Prompt processing: 2.002 s
[INFO] Full generation: 5.688 s

```

Also tried a couple of other prompts, all led to random text.

I have also tried Llama-13b on a linux machine, and this is what I get:
```
"[INFO] Loading model from mlx_model_13b/weights.*.npz.
Press enter to start generation
------
hello
= {
  name = "hello";
  srcs = ["hello.c"];
  cflags = ["-Wall"];
  ldflags = ["^\Quit (core dumped)"
```
Am I doing something wrong?

**Comment by awni** [comment]
Which models did you try? Llama 1 / 2 / 3 / 3.1? That example only supports Llama 1 and 2. For later models you should use the MLX LM package:

1. `pip install -U mlx-lm`

2.  `mlx_lm.generate --model mlx-community/Meta-Llama-3.1-8B-Instruct-4bit --prompt "Write a quicksort in C++?" --temp 0.0 --max-tokens 512`

**Comment by JackxTong** [comment]
I am using CodeLLama / Llama2, tried both 7B and 13B model.

**Comment by awni** [comment]
@JackxTong I would recommend using the MLX LM package. It will also handle adding in chat templates which are important to get good results with instruct models which could explain the poor results you are seeing.

I tested the Llama 2 7B chat model and it seems to work ok..

```
mlx_lm.generate --model meta-llama/Llama-2-7b-chat-hf --prompt "how are you" --temp 0.0
```

Gives:

```
Prompt: <s>[INST] how are you [/INST]
I'm just an AI, I don't have feelings or emotions, so I don't have a personal experience of being "how I am". I exist to assist and provide information to users like you through text-based conversations. However, I'm here to help you with any questions or topics you'd like to discuss! How can I assist you today?
==========
```



I'm closing this for now as I don't think there is a bug in the example.. if you think there is something else to investigate here, lmk.
