### ISSUE TITLE
Converting Command R Plus to 4 bits produces garbage output

### ISSUE THREAD

**Issue by vlbosch** [ml-explore/mlx-examples#967]
After conversion of Command R Plus (latest commit on the HF-repo) to MLX quantized to 4 bits, the model only produces garbage outputs. With the default parameters, I only get <PAD> which goes on infinitely. With group-sizes 32 or 128, it produces some random text and goes on infinitely as well. I tried changing the tokenizer, as was suggested in another issue with this model, but it doesn't fix the issue. 

MLX version: 0.17.1 
macOS Sequoia 15 DP5

**Comment by vlbosch** [comment]
I am about to start the download for the just released command-r-plus-08-2024 (and the regular command-r-08-2024). I will report whether they have the same issue. Do you have an idea what might be the issue and/or can I check something specifically?

Thanks for the quick reply!

**Comment by awni** [comment]
> Do you have an idea what might be the issue and/or can I check something specifically?

Not yet.. but I can see that it used to work in an old version of MLX.. so something must have changed since then..

**Comment by awni** [comment]
It doesn't like having the embedding quantized 🤔 ..

**Comment by vlbosch** [comment]
Ahh, that sounds reasonable given how sensitive the model was with for example also repeat penalty. 

How can I exclude the embedding (and output) layers with mlx convert?

**Comment by awni** [comment]
> How can I exclude the embedding (and output) layers with mlx convert?

There isn't an option for that. You can hack the code for a quick fix. Change [this line](https://github.com/ml-explore/mlx-examples/blob/main/llms/mlx_lm/utils.py#L667) to:
```python
    class_predicate = lambda _, m: hasattr(m, "to_quantized") and not isinstance(m, nn.Embedding)
    nn.quantize(model, q_group_size, q_bits, class_predicate)  
```

Also, it may be the case that the new versions are not sensitive to quantizing the embedding.. that would be simpler.

**Comment by awni** [comment]
Current hypothesis is there is a bug in the fast quantization for large arrays as this has a really high error:

```python
import mlx.core as mx

w = mx.random.uniform(shape=(256000, 12288))
wq, scales, biases = mx.quantize(w, bits=8, group_size=32)
what = mx.dequantize(wq, scales=scales, biases=biases, bits=8, group_size=32)

print((w - what).abs().max())
```

@barronalex is looking into it. So maybe best to delay quantizing the large cohere model until we know more.

**Comment by awni** [comment]
@vlbosch quantizing Command R Plus should work now, however; this will require using the main branch of MLX or waiting until the next release (hopefully next week).

You can install the main branch locally like so (it may take a couple minutes to build):

```
CMAKE_BUILD_PARALLEL_LEVEL="" pip install git+https://github.com/ml-explore/mlx.git
```

**Comment by vlbosch** [comment]
Thanks @awni and @barronalex for this quick fix! I just tried to convert the new Command R Plus-0824 model and it works. Output is as expected. I will let you know if I still find anything weird.

Btw, on macOS 15 DP you need to change Xcode-select with xcode-select --switch /Applications/Xcode-Beta.app/Contents/Developer or else you'll run into errors when building from git.
