### ISSUE TITLE
[ Suggestion ] Add KV cache features to the Python API

### ISSUE THREAD

**Issue by ibehnam** [ml-explore/mlx-examples#970]
Caching the prompt (https://github.com/ml-explore/mlx-examples/blob/main/llms/mlx_lm/cache_prompt.py) and loading cache when generating (https://github.com/ml-explore/mlx-examples/blob/main/llms/mlx_lm/generate.py) are implemented for the command line. But the Python API still doesn't know about these (https://github.com/ml-explore/mlx-examples/blob/3c6e8b11af9dda55ee8d38ee9f612a65118f7793/llms/mlx_lm/utils.py#L313).

It would be nice to have the KV caching parameters available in the API too.

**Comment by awni** [comment]
The latest MLX LM enables this. You can pass a `prompt_cache` to `generate`, `stream_generate` or `generate_step` to maintain the cache. We also added `mlx_lm.chat` as an example of how to use it. The chat mode preserves the model cache across the dialogue.

There are also APIs for saving and loading the prompt cache in `mlx_lm.models.cache`:
- `save_prompt_cache`
- `load_prompt_cache`
- `make_prompt_cache`

A simple example usage of the APIs [here](https://github.com/ml-explore/mlx-examples/blob/main/llms/mlx_lm/examples/chat.py).
