### ISSUE TITLE
is mlx-examples/llms/CONTRIBUTING.md still up-to-date?

### ISSUE THREAD

**Issue by Jonathan-Dobson** [ml-explore/mlx-examples#976]
Just looking to confirm that the markdown files still have up-to-date instructions for us new folks. It looks like the last update was 6 months ago.

Mainly this file:
`mlx-examples/llms/CONTRIBUTING.md`

But also, the models:
`mlx-examples/llms/gguf_llm`
`mlx-examples/llms/llama`
`mlx-examples/llms/mistral`
`mlx-examples/llms/mixtral`
`mlx-examples/llms/speculative_decoding`

**Comment by awni** [comment]
Yes CONTRIBUTING.md is up-to-date. It doesn't change frequently.
