### ISSUE TITLE
Possible bug with prompt cache

### ISSUE THREAD

**Issue by awni** [ml-explore/mlx-examples#977]
I'm not certain yet, but I think the two should have equivalent output:

### No cache
Works fine:
```python
mlx_lm.generate --model mlx-community/Meta-Llama-3.1-8B-Instruct-4bit --prompt "Hi! What are you up to?" --temp 0.0
```

### Cache
Gives bad results:

```
mlx_lm.cache_prompt --model mlx-community/Meta-Llama-3.1-8B-Instruct-4bit --prompt 'Hi! ' --kv-cache-file cache.safetensor
```

```
mlx_lm.generate --prompt "What are you up to?" --kv-cache-file cache.safetensors  --temp 0.0 
```

**Comment by mark-lord** [comment]
Not at computer at the moment so can’t elaborate on this further; just wanted to mention before I forget that if anyone begins investigating this issue, —ignore-chat-template would also be needed to get the outputs to be equivalent; else cached example would have user chat template / format applied to both “Hi!” and “What are you up to?” separately, versus non cached example would have “Hi! What are you up to?” As a single user turn (which can subtly affect model response)

But also when I was getting the bug, it was producing straight up gibberish anyway so would be easy to tell anyhow lol

**Comment by angeloskath** [comment]
Found the bug. There should be a quick fix. We are saving the whole KV cache state even though most of it is empty ie 0s. Making a PR shortly. I guess most of my testing has been with large prompts which hid this pretty well ... oops.

**Comment by angeloskath** [comment]
@mark-lord the ignore chat template is not actually needed. We are truncating the chat template in `cache_prompt` and when generating with a cache from a file so it should be identical.
