### ISSUE TITLE
Adding an equivalent pytorch or tensorflow of the models for true benchmark

### ISSUE THREAD

**Issue by thegodone** [ml-explore/mlx-examples#986]
That would be really amazing to get the equivalent model in TF or Torch (unfortunately torch on Silicon not always works...) for benchmarking and detect any layers/functions that need to be improved. This will also show the capability of the MLX over those two AI packages. This is also inline with one question on the Roadmap for developers: https://github.com/ml-explore/mlx/issues/1411.

**Comment by awni** [comment]
We don't intend to do this for all the models in this package. Though would be great to see community projects around that and any interesting benchmarks.
